### ISSUE TITLE
Format string appearing in vehicle map popover

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1004]
![format](https://cloud.githubusercontent.com/assets/2254/24075153/77fc1efa-0bd3-11e7-860b-a4e92c1d04bd.png)

**Comment by ualch9** [comment]
I can't seem to find what's causing this, there is no string literal in this repo that would generate `trip_status.last_report_format` as the string unless something is wrong with `NSLocalizationString`, but I am not familiar with it.

<img width="293" alt="delete" src="https://cloud.githubusercontent.com/assets/22162410/24118045/a793c95a-0d69-11e7-8f09-aae7772acf0f.png">

**Comment by aaronbrethorst** [comment]
`trip_status.last_update_format` in `Localizable.strings` needs to be renamed to `trip_status.last_report_format `

**Comment by ualch9** [comment]
@aaronbrethorst  whoops wasn't paying attention to spelling 🤦‍♂️. Fixed in #1009
