### ISSUE TITLE
Alarm times don't update on the Recents tab

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1008]
From a user:

> I also see all of the alarms that are currently set in the Recent screen.  Awesome!  One other thing I noticed was that the alarm is not dynamically changing based on current estimated arrival time.. does that pose additional complications? Should work, just still a big buggy?

**Comment by cathy810218** [comment]
@aaronbrethorst For this issue, I'm thinking to use KVO. But I am still wondering what's the best way to notify `Recent - alarm cells` that the time has been updated.
