### ISSUE TITLE
Inactive regions are being shown in UI

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#1011]
### Expected behavior

In the Regions API (http://regions.onebusaway.org/regions-v3.json), there is a boolean field `active` that indicates whether or not a region server is active.  This allows us to dynamically turn off certain regions (e.g., in case a beta region shuts down).  This is the case for Region ID 6 - Bear Transit, which is no longer active.

OBA iOS should not show inactive regions to users or use them as an option for automatic region selection, but right now it is showing "Bear Transit" under "Newest regions".

### Actual behavior

Bear Transit is showing up as a chooseable region

### Steps to reproduce the behavior

1. Tap on "Info" tab
1. Tap on "Region"

### App Version/Hardware

iPhone 7

**Comment by aaronbrethorst** [comment]
I'll get this fixed along with the region handling changes pending for the next release.

**Comment by aaronbrethorst** [comment]
Fixed in release 17.1.2.
