### ISSUE TITLE
Bookmarks tab needs better visual design

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1014]
The bookmarks tab is currently very cluttered-looking, in my opinion. (note, also: this is because of work that I did.)

At the very least, the font sizes and weights of the cells on this tab should be rethought in order to improve usability.

**Comment by dotTechnopath** [comment]
I'll try to take a shot at this, will report once I'm done

**Comment by dotTechnopath** [comment]
Here is a quick mock up I have thought of:

I used the template for the layout used in iOS mail. Readability should be improved and the new layout is now more consistant with iOS guidelines. I'm open to suggestions for any changes

Current design:                                               Proposed Changed:
![group](https://cloud.githubusercontent.com/assets/9895341/24689757/93d2b280-197d-11e7-8860-d4b1766b5bd6.png)

**Comment by aaronbrethorst** [comment]
Looks great, thank you!

**Comment by dotTechnopath** [comment]
sorry for late reply, but due to circumstances i don't have access to a mac right now. so  I dont think i can work on it right now. sorry if you were expecting a finished modification.

**Comment by aaronbrethorst** [comment]
@dotTechnopath nope, no modifications needed. I'm queueing this up for the next release. thanks for your help!
