### ISSUE TITLE
Sometimes stop information for a route is off by about 30 minutes

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1035]
From a user:

> A moderate percentage of the time the route data loaded for a specific stop bus time will be clearly the wrong data. Usually (always?) one something like half an hour later. 
> 
> For example, I took the two screenshots shown just now. The "header" for the bus shows the bus time I tapped, but the route bus below clearly isn't the on I tapped.

![attachment 1](https://cloud.githubusercontent.com/assets/2254/24635629/631bfb8c-1889-11e7-93a8-611828c99acf.jpg)
![attachment 2](https://cloud.githubusercontent.com/assets/2254/24635630/631ee91e-1889-11e7-9a2a-6246fb6a8c44.jpg)

**Comment by cathy810218** [comment]
@aaronbrethorst Not sure what this user is saying? What header is he referring to and what exactly is off by 30 mins?
