### ISSUE TITLE
Searching for stop code in unified search box shows "error connecting" 

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-iphone#1040]
- Search for a valid stop code such as 99199
- Select "Stop Number Lookup: 99199"
- Receive error "Error connecting"

Region:  San Diego
App Version 17.2.0

**Comment by devinbraun** [comment]
![stop_code_search_error](https://cloud.githubusercontent.com/assets/5028299/24874473/ab2caa16-1dd9-11e7-8b4d-45a19a34a1de.jpg)

**Comment by aaronbrethorst** [comment]
thanks, I'll take a peek.
