### ISSUE TITLE
Rethink the information and design of arrival/departure cells

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1055]
From a user:

> Not easy to understand when the bus is delayed by x minutes (in blue). The new time is the current arrival time or the initially expected?

Other problems that need solving:

- [ ] Past buses are confusing to users (maybe they should be grayed out a bit? i.e. a decrease in opacity?)
- [ ] The colors don't mean anything to users
- [ ] Users still don't understand what 'scheduled' means
- [ ] The font choices are less than ideal—there isn't a clear information hierarchy on this cell

**Comment by barbeau** [comment]
I think this users comment is related to the current discussion in the Slack #ux channel for whether clock times like 10:32am are based on realtime info or schedule info.

**Comment by dotTechnopath** [comment]
I think having a tutorial or some kind of FAQ page could help users overcome some of these issues such as the wording of 'scheduled' and the colors not meaning anything.

Another solution to 'scheduled' could be to change the word itself to something else, perhaps "predicted" or "estimated" - which might be more clear to users what it means.

**Comment by barbeau** [comment]
FWIW, we have this screen on Android under "Help->Legend":

![image](https://cloud.githubusercontent.com/assets/928045/25905146/323e1f2e-356f-11e7-9c7d-6f19ccd07db0.png)

We also have an interactive tutorial - users are asked if they want to see it on initial install, and if yes they get these types of contextual popups on first visits to features (throttled to every few views to not get too naggy - beta users were clear they didn't want these too frequently).  They can also turn it on at any time via "Help->Show tutorial":

![image](https://cloud.githubusercontent.com/assets/928045/25905307/aeda0700-356f-11e7-9d24-de3c5a4e592b.png)

**Comment by ualch9** [comment]
FYI, it appears Google made something that can recreate the contextual popups from Android that @barbeau showcased.

Link: https://material.io/components/ios/catalog/feature-highlights/

**Comment by barbeau** [comment]
Interesting! So, ironically, Google apparently doesn't have the Highlight component in their design library for Android, it exists only on iOS. On Android, we're using a 3rd party library https://github.com/amlcurran/ShowcaseView
