### ISSUE TITLE
Shrinking icons look weird

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1061]
From Devin Braun:

> In the route search view, when I zoomed out the stop info icons shrunk too. I don't think that's normal.

This is actually by design (i.e the code that exists to handle this appears to be working correctly), but I'm not convinced the design is correct. 

Let's just cut this feature out of the product. Less code = better.

![attachment 1](https://cloud.githubusercontent.com/assets/2254/25296653/3d1e516e-269e-11e7-8b78-770fa0c7ed01.jpg)

**Comment by devinbraun** [comment]
Actually, that screenshot doesn't do it justice.  It's much much smaller on an iPhone screen.

**Comment by aaronbrethorst** [comment]
Retina 2x screenshots never look right when they're displayed at 1x.

**Comment by aaronbrethorst** [comment]
Still occurring...

![attachment 1](https://cloud.githubusercontent.com/assets/2254/25369044/bd22d724-2935-11e7-9960-23b3d79d819e.jpg)
![attachment 2](https://cloud.githubusercontent.com/assets/2254/25369045/bd2725a4-2935-11e7-8a4e-8712ec3fe753.jpg)
