### ISSUE TITLE
AlertPresenter alerts lack a 'dismiss' affordance

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1094]
I received feedback from a user who mentioned that waiting for an `AlertPresenter`-based alert to time out was tedious, and I realized for the first time that the `AlertPresenter` lacks any 'Dismiss' affordances! You can tap anywhere on the screen to dismiss one of these, but there's nothing about them that suggests to the user that this is possible, which is a huge design issue and my bad :-\

A good solution for this will include some sort of 'Dismiss' button

- [x] needs design
- [ ] needs implementation 

![attachment 3](https://cloud.githubusercontent.com/assets/2254/25423573/09c993bc-2a1a-11e7-850a-5c7276ef168e.jpg)

**Comment by ualch9** [comment]
It looks like we could add a button to the alert such as `close` or `dismiss` to the Alert itself in addition to the `tap anywhere else` or `swipe up`. `SwiftMessages` appears to already have native support for buttons as shown in the attached sample screenshot.
<img src="https://cloud.githubusercontent.com/assets/22162410/25470055/004bcd30-2ad5-11e7-95e5-615848efed2d.png" height=480>

**Comment by aaronbrethorst** [comment]
@ualch9 Excellent suggestion. That button just needs to be wired up.
