### ISSUE TITLE
Selecting a bookmark in Search doesn't work

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-iphone#1095]
In this case, I have a stop bookmarked for Eastgate P&R. However, upon selecting it, it fails to open the stop and shows a "failed to find stop ID" error.

see attached screenshots

<img src="https://cloud.githubusercontent.com/assets/22162410/25452692/4fd63386-2a7b-11e7-8094-2eb0043859e0.jpg" height=480>
<img src="https://cloud.githubusercontent.com/assets/22162410/25452754/8848763e-2a7b-11e7-977d-92df2487cb14.PNG" height=480>

**Comment by aaronbrethorst** [comment]
@ualch9 this definitely needs to get fixed for the upcoming release. Let me know if you'd be interested in tackling it; otherwise, I'll take care of it as soon as I have a few spare minutes. Thanks for the detailed report!
