### ISSUE TITLE
Add trip status, alarms, and bookmarking to arrival/departure details

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1141]
The three aforementioned features should be available on this page. 

- [x] needs design
- [ ] needs implementation 

![img_2522](https://cloud.githubusercontent.com/assets/2254/25980491/bfa78480-3683-11e7-958e-e7c8df76b15e.PNG)

**Comment by dotTechnopath** [comment]
I'll attempt to design something for this, will report back once I'm done

**Comment by aaronbrethorst** [comment]
@dotTechnopath sounds good. thank you!

**Comment by dotTechnopath** [comment]
A mockup in which I added a button that we use on the previous screens that will show alarms, bookmarks, etc. 

However, I am slightly confused by "trip status". Is this the "share trip status" option on the app currently? or is it something else? Thanks

![group](https://cloud.githubusercontent.com/assets/9895341/26272908/cffbcf7a-3cd8-11e7-9f64-2a3325f8fa87.png)

**Comment by cathy810218** [comment]
I personally prefer option in the middle just because it's more visible to the users. :)
