### ISSUE TITLE
Bookmarks tab keeps showing 'loading' message incorrectly

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1154]
From a user:

> I really like the capability of being able to bookmark a specific bus at a bus stop and have it show times on the bookmark screen. I believe this is a bug with that when there are no buses scheduled in the next 30 mins. When I open the bookmark page, it flashes for a second that "no departures scheduled for next 30 mins" but then it goes to the "loading" status and never updates the status...see attached screenshot.

![attachment 2](https://cloud.githubusercontent.com/assets/2254/26746154/e9fc13ce-47a2-11e7-8b25-b501b3dfa5e2.jpg)

**Comment by mikemiksch** [comment]
I'll take a crack at this.

**Comment by aaronbrethorst** [comment]
Fixed with a recent commit: https://github.com/OneBusAway/onebusaway-iphone/pull/1269/commits/174cd326aa27529fad2239691eb6d7b5d2d79af2
