### ISSUE TITLE
Investigate what happens when region changes to inactive

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#1160]
We're looking at shutting down OBA Atlanta due to lack of local funds to keep the server running and operational.  This will be implemented in the Regions API by changing the `active` field to false for OBA Atlanta.

I’ve created a staging version of the Regions API that has Atlanta deactivated (active=false) – the raw JSON URL you can plug into OBA iOS to test is at:
https://github.com/OneBusAway/onebusaway-multiregion-support/raw/atlanta-inactive/staging/regions-v3.json

@aaronbrethorst After you have a chance to test, could you please let me know?  Thanks!

**Comment by aaronbrethorst** [comment]
Yep will do. I don't think I'll be able to until after the board call unfortunately, but I'll get this done today.

**Comment by bbodenmiller** [comment]
I think it's probably worth displaying some sort of explanation alert if a region goes from active to inactive.

**Comment by barbeau** [comment]
@aaronbrethorst Just checking in on this - I'd like to switch off Atlanta in the Regions API soon.

**Comment by aaronbrethorst** [comment]
@barbeau At next region refresh, the app will pop up the region picker dialog. Atlanta will not be present on the list. Everything looks fine. Thanks for your patience!

**Comment by barbeau** [comment]
@aaronbrethorst Also, friendly reminder to remove "Atlanta, GA" from the supported regions in the Apple App Store listing - https://itunes.apple.com/us/app/onebusaway/id329380089.

**Comment by barbeau** [comment]
Ok, I've pushed the new Regions API files with Atlanta deactivated to AWS, they should be reflected in the production Regions API at http://regions.onebusaway.org/regions-v3.json soon.

**Comment by aaronbrethorst** [comment]
@barbeau done!

**Comment by barbeau** [comment]
Thanks!
