### ISSUE TITLE
Can’t set an alarm in 17.9.0 on iOS 11

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-iphone#1178]
In iOS 11 app version 17.9.0 I get the following message when trying to set an alarm

![cfa9e95f-3915-4797-a920-1de899dc9c46](https://user-images.githubusercontent.com/5028299/30513022-fc21579c-9ab0-11e7-9f0c-e7a92aa5dfa6.jpeg)

**Comment by ualch9** [comment]
seems to work OK for me. Could this issue be region specific?
