### ISSUE TITLE
Tapping on Today extension bookmark should display that Stop

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1204]
I should be able to open the app and navigate to a stop inside of the app by tapping on a bookmark in the Today extension.

**Comment by jeffpearce** [comment]
I'd like to take a shot at this

**Comment by aaronbrethorst** [comment]
hey @jeffpearce - sure, sounds good. Feel free to hit me up on Slack if you want to talk about how this might work. I think you can reuse a lot of the code that's used for 3D Touch in the app delegate today.

**Comment by aaronbrethorst** [comment]
hey @jeffpearce - any updates on this?
