### ISSUE TITLE
'Delete Alarm' Doesn't Seem to be Deleting Alarms

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1249]
### Expected behavior

Deleting an alarm prevents it from firing notifications.

### Actual behavior

This doesn't seem to be working. Not sure if it's in obaco or in OBA.

### Steps to reproduce the behavior

1. Create alarm.
2. Delete alarm.

### App Version/Hardware

18.1.0

**Comment by samuela** [comment]
I'm also having this issue. Steps I followed:

1. Set an alarm.
2. Remove the alarm. Apparently successful.
3. Now either the menu still shows "Remove Alarm" or it now shows "Set Alarm". In either case, tapping on it takes you to the confirm-delete menu.
4. No matter what you do, you'll still be notified once the alarm hits time.

I've also been able to crash the app playing around with alarms, but I haven't figured out a consistent way to repro that yet.

Not trying to criticize at all, but it's really a shame that alarms don't work better. I think alarms could be an incredibly useful feature.

I'm on v17.9.1.

**Comment by aaronbrethorst** [comment]
@samuela I don't feel criticized. Software has bugs. This feature has two bugs.

Looking at your Github profile, it looks like you have more web experience than iOS experience. Please feel free to pitch in on the backend and help out if you'd like: https://github.com/onebusaway/onebusaway-deep-links. OBA is an open source project mostly staffed by volunteers, including me. We never have enough people to do all of the things we want to get done.

**Comment by aaronbrethorst** [comment]
https://herokuapp58523565herokucom.airbrake.io/projects/135959/groups/2154052594760249728/notices/2154052636030535772
