### ISSUE TITLE
Stop search broken in Beta 18.1.0

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-iphone#1264]
### Expected behavior
Use search box on map view to search for a valid stop number. In this case I was using 11670. The stop should be found and displayed on the map. 

### Actual behavior
After searching a red box appears stating that the server was unable to interpret the request or it is simply having some problems. 

### App Version/Hardware
18.1.0 Beta

**Comment by aaronbrethorst** [comment]
Thanks for the report. I’ll get this fixed for the next release.

**Comment by aaronbrethorst** [comment]
The URL that the app is trying to load for the aforementioned stop is:

http://realtime.sdmts.com/api/api/where/arrivals-and-departures-for-stop/11670.json?key=org.onebusaway.iphone&app_uid=8F5E797E-4333-4594-86AD-4C597F776745&app_ver=20180127.01&version=2&minutesBefore=5&minutesAfter=35

This returns the error: `java.lang.IllegalStateException: invalid agency-and-id: 11670`

Looks like I'm not properly prefixing the stop ID with the agency ID.

**Comment by aaronbrethorst** [comment]
Puget Sound is broken too. This was broken in https://github.com/OneBusAway/onebusaway-iphone/commit/d0fdeea#diff-e58805250c8bf8034c3e954244710929R272. Commenting out OBAMapViewController.m lines 272-274 fixes the issue.

The stop ID navigation target type was previously being used to _search_ for stop numbers (which is wrong, notably), and is now being used to look up fully qualified, prefixed stop numbers, which is right, but breaks the other behavior.

I think the optimal fix for this is to keep OBAMapViewController.m lines 272-274 as-is, and introduce yet another new OBANavigationTarget type that is specifically meant for user-initiated searches for stops.
