### ISSUE TITLE
Uppercase/lowercase displayed differently from data in GTFS

### ISSUE THREAD

**Issue by Heidebritta** [OneBusAway/onebusaway-iphone#1304]
Data displayed is different cases than how it is in GTFS - SPLC is displayed as Splc.

From the client "It has come to our attention that SPLC with lowercase letters (Splc) is easily mistaken for a racial epithet, according to a Hispanic family"

### Expected behavior
I would expect to see the data as it is in the GTFS. In the GTFS trips, the trip headsigns are, for example “SPLC Parking via 70th”. In stops.txt the stop is called "SPLC / SR 513". When I look at the sign interface and the mobile app, I am also seeing SPLC.
From trips.txt
route_id,service_id,trip_id,trip_headsign,direction_id,block_id,shape_id
863-16,SCH-1805-SCH-Weekday-60,542835-SCH-1805-SCH-Weekday-60,"Hospital via SPLC Parking",0,68791,8630001
863-16,SCH-1805-SCH-Weekday-60,542836-SCH-1805-SCH-Weekday-60,"SPLC Parking via 70th",1,68791,8630002

### Actual behavior

- SPLC is displayed as Splc.
- via displayed as Via
- 70th displayed as 70Th.

### Steps to reproduce the behavior

This was reported to my by a client and I don't have the app, so bear with me.

Go to Puget Sound region
Search/select stop #755005. See attached screenshot.

### Screenshot of the issue (if applicable)
In app:
![iphone_splc](https://user-images.githubusercontent.com/30128060/40984353-ab3765b0-68af-11e8-9aa3-d6d5034be8f4.png)
SPLC in web:
![web_splc](https://user-images.githubusercontent.com/30128060/40984365-b5b08648-68af-11e8-9e94-9c8a334c4b4f.png)
SPLC on signs:
![sign_splc](https://user-images.githubusercontent.com/30128060/40984372-be83c276-68af-11e8-829e-78ecdf8af4fe.png)

### App Version/Hardware
unknown

**Comment by barbeau** [comment]
Same issue on Android is at https://github.com/OneBusAway/onebusaway-android/issues/883.

FWIW, code used for text case changes as well as unit tests is at https://github.com/OneBusAway/onebusaway-android/issues/883#issuecomment-394744202.
