### ISSUE TITLE
Map/Stop Ux Improvements

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1332]
Work that fell out of #1331 that needs to be completed for 18.2.

- [x] scroll the map when the user selects an annotation so that the annotation is visible
- [x] Why is 'nearby' only showing 1 item?
- [ ] Show toolbar on embedded stop page (maybe as a pair of buttons under title?)

**Comment by wesmi** [comment]
+1 on the new design but can we have a toggle for the tap-vibration?

**Comment by aaronbrethorst** [comment]
@wesmi The feedback should've been turned off altogether. Thanks for the note. I'll get this fixed in the next build.

**Comment by aaronbrethorst** [comment]
broken into separate tasks. Closing this.
