### ISSUE TITLE
Add link to regional fare payment app

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#1336]
In OBA Android v2.3.9 rolling out now, a new option to "Pay my fare" is now available in the navigation drawer, with each region being able to designate a fare payment app.  

When you tap on "Pay my fare", if you don't have the regional fare payment app installed, you're directed to Google Play to install it.  If it's already installed, then the tap opens the app directly.

Current supported regions are:
* Tampa
* San Diego
* Puget Sound

Here's an example UI flow for San Diego:

![image](https://user-images.githubusercontent.com/928045/43667639-e33d2f10-9746-11e8-8de3-66cb7556996a.png)

If a region has a fare payment app that doesn't cover all of the transit service shown in OBA Android, they are able to provide warning text that is shown to the user - for example, for Puget Sound:

![image](https://user-images.githubusercontent.com/928045/43667774-7d1e3d18-9747-11e8-9c6b-35c469700080.png)

*Implementation details on Android*

Three new fields added to the [Regions API](http://regions.onebusaway.org/regions-v3.json):
* `paymentAndroidAppId` – The application ID for unique app listing on Google Play
    * e.g., org.sdmts.riderapp for Compass Cloud in San Diego -https://play.google.com/store/apps/details?id=org.sdmts.riderapp 
* `paymentWarningTitle` – The title of the warning dialog, if the payment app doesn’t cover all service shown in OBA
     * e.g., “Check before you buy!”
* `paymentWarningText` – The body text of the warning dialog, if the payment app doesn’t cover all service shown in OBA
    * e.g., “The mobile fare payment app for Puget Sound does not support all transit service shown in OneBusAway. Please check that a ticket is eligible for your agency and route before you purchase!”

@aaronbrethorst Any thoughts on the feasibility of something similar on iOS, and level of effort to accomplish this?  We will likely have an opportunity to pitch this for funding soon.

### Expected behavior

Give me an easy way to reach a regional fare payment transit app from within OBA iOS

### Actual behavior

No links to fare payment apps exist

### Steps to reproduce the behavior

 N/A

**Comment by aaronbrethorst** [comment]
I’m working on this now and hope to include it in the next TestFlight build. Unfortunately, because of abuse by Twitter (among others) a few years ago, Apple makes it difficult to launch arbitrary apps unless they support iOS deep links, which none of these payment apps appear to. Still, it should be possible to shoehorn something into place that’ll work at least for Tampa, SD, and PS.

**Comment by barbeau** [comment]
Awesome, thanks @aaronbrethorst!
