### ISSUE TITLE
make stop information map pull down similar to foursquares

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#134]
On foursquare's main screen when you pull down the map expands slightly. It would be cool if the stop information map did the same thing rather than displaying a grey box.

**Comment by aaronbrethorst** [comment]
I'd love to do a parallax effect in this view controller if pull to refresh is not a mutually exclusive option. I'm closing this to reduce the number of open issues, but I promise that I am mentally tracking it, as the lack of parallax drives me nuts :-\
