### ISSUE TITLE
Analytics for Fare Payment apps

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1343]
TODO: need to sort out with @barbeau 

1. Track taps on Pay My Fare table item -> App Store
2. Track taps -> apps

anything else?

**Comment by barbeau** [comment]
It's just two analytics events - one is triggered if the user doesn't have the app installed when they tap on "Pay my fare", and the other is triggered if the user does have the app installed when they tap on "Pay my fare".

Here's what the OBA Android logic looks like:

~~~
    /**
     * Launches the payment app for the provided region if it's already installed, and if not
     * directs the user to the listing in Google Play where it can be downloaded
     * @param activity Activity to use to launch the Intent
     * @param region region to launch a payment Intent for
     */
    private static void startPaymentIntent(@NonNull Activity activity, @NonNull ObaRegion region) {
        PackageManager manager = activity.getPackageManager();
        Intent intent = manager.getLaunchIntentForPackage(region.getPaymentAndroidAppId());
        if (intent != null) {
            // Launch installed app
            intent.addCategory(Intent.CATEGORY_LAUNCHER);
            activity.startActivity(intent);
            ObaAnalytics
                    .reportEventWithCategory(ObaAnalytics.ObaEventCategory.UI_ACTION.toString(),
                            Application.get().getString(R.string.analytics_action_button_press),
                            Application.get().getString(R.string.analytics_label_button_press_pay_fare_open_app));
        } else {
            // Go to Play Store listing to download app
            intent = new Intent(Intent.ACTION_VIEW);
            intent.setData(Uri.parse(Application.get().getString(R.string.google_play_listing_prefix, region.getPaymentAndroidAppId())));
            activity.startActivity(intent);
            ObaAnalytics
                    .reportEventWithCategory(ObaAnalytics.ObaEventCategory.UI_ACTION.toString(),
                            Application.get().getString(R.string.analytics_action_button_press),
                            Application.get().getString(R.string.analytics_label_button_press_pay_fare_download_app));
        }
    }
~~~

`R.string.analytics_action_button_press` = `button_press`
`R.string.analytics_label_button_press_pay_fare_open_app` = `Clicked Pay Fare Open App`
`R.string.analytics_label_button_press_pay_fare_download_app` = `Clicked Pay Fare Open App`

So they are both "button press" categories, and reported with the above strings.

IIRC you can report the same strings and then GA automatically sorts out Android vs. iOS?

I guess a quick way to tell would be to compare the iOS analytics strings and see if any match the Android analytics strings:
https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/res/values/donottranslate.xml#L82
