### ISSUE TITLE
add global offline indicator

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#137]
As originally mentioned in https://github.com/OneBusAway/onebusaway-iphone/issues/106 I think we need some kind of global offline indicator. I say this because when you are on the map and get the offline message there is no indication afterwards whether you are still offline or not. @neophit mentioned that the [Reachability](https://github.com/tonymillion/Reachability) class should help create a global offline indicator.

**Comment by aaronbrethorst** [comment]
Completed as part of 2.6.0
