### ISSUE TITLE
indicate wheelchair accessible stops

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#138]
One of the app reviews mentioned they'd like to be able to tell what stops are wheelchair accessible.

**Comment by aaronbrethorst** [comment]
I don't think the iOS app has the ability to directly influence this. I'd love to see this information incorporated into OBA, but keeping an issue open here offers false hope about my/our ability to affect positive change. I'd love to see this reopened elsewhere.

**Comment by barbeau** [comment]
OBA does actually basic support for this server-side - there is a `wheelchairBoarding` field in the stop element, which is returned in the references section of API responses:
http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/elements/stop.html

From the above:

>The following values are supported for the <wheelchairBoarding/> element:
>ACCESSIBLE
NOT_ACCESSIBLE
UNKNOWN

This obviously requires agencies to populate a wheelchairBoarding field in their GTFS stops.txt - to my knowledge no agency is providing this data, so all values in API responses are `UNKNOWN`.  There is also the issue of debating exactly what "accessible" means.
