### ISSUE TITLE
Small number of users occasionally lose ability to connect to API

### ISSUE THREAD

**Issue by maxgano** [OneBusAway/onebusaway-iphone#14]
We have a pattern of a few users simply losing the ability to connect to OBA following a data bundle update. For any given update, we hear from a half dozen or more users. This also may be occurring in relationship to other changes such as DNS updates, etc. But the most clear pattern to date is emerging in relationship to data bundle updates, after which we consistently hear from a small number of users who can't connect.

We provide the users with three possible actions to correct:

- Stop and restart OBA
- Shutdown the iPhone then restart OBA
- Reinstall OBA

It's a bit difficult to get followup from what eventually works for users, and we are attempting to gather better stats. At this point, it seems that it is fairly evenly spread across the three actions listed above.

I am entering this bug to both initiate an investigation of root causes if practical, and to also see if other OBA Operators are experiencing similar user impact.

For background, we utilize a rolling update to a pair of TDS Servers operating through a load balancer for fault tolerance. To update data bundles, the first server is disabled, updated, tested then re-enabled. Then we repeat the process for the second server. This works great, allowing four nines availability with no effective downtime for users other than the few mentioned above. Validation conducted directly against API has never resulted in failure to connect to the TDS server throgh the API, so this seems to be something to do with some condition that the native app is experiencing but not coping with consistently. We have also not had similar reports from users of either Android or Windows phones. Or at least not that I have noticed.

Happy to provide any further information / support needed. It's a gnarly one, probs, but definitely helpful to users going forward.

**Comment by aaronbrethorst** [comment]
Given that we haven't seen any movement on this in 2 years (and that I've never heard about it), I'm going to go out on a limb and speculate it's no longer an issue. If we haven't heard anything more about this in 3 months (March 7, 2016), I'm going to close it.

**Comment by barbeau** [comment]
Agreed, I haven't heard anything in Tampa on this in quite some time.

**Comment by aaronbrethorst** [comment]
closing per my last comment.
