### ISSUE TITLE
problem with search interface using VoiceOver

### ISSUE THREAD

**Issue by alanb2718** [OneBusAway/onebusaway-iphone#1402]
problem report from one of our voiceover users:

> I’m encountering some problems while trying to use the search interface with Voiceover. For example, I just searched for the bus route 40. I typed the number 40 into the search box and double tapped on the option to search for the route. First, some of the resulting stops like 1st Ave. and Republican St. for example, came up, but they don’t even include a bus with the numbers 4 or 0 in them. Second, I could not double tap on any bus stop in the search results to open its page which shows upcoming bus arrival times. Finally, I can exit the search interface without closing the app altogether. For example, after unsuccessfully opening a bus stop where the bus 40 stops, I double tapped on the clear text button. The 40 was removed from the search box, but I could not cancel the search by double tapping on the dismiss button.

**Comment by aaronbrethorst** [comment]
Hmm, I think this is unfortunately out of scope for the moment. I need to spend some more time with VoiceOver and see what I can do to fix it. I have, however, fixed the 'nearby stops' issue that is mentioned. 60b4b2452118345f25717bc6623f4ce77d3a8c31
