### ISSUE TITLE
usability issues with VoiceOver for filing bug reports

### ISSUE THREAD

**Issue by alanb2718** [OneBusAway/onebusaway-iphone#1403]
feedback from one of our VoiceOver users:

> I wanted to share some feedback about the email interface when filing a bug report through the iOS app while using Voiceover. I’m going to try to explain this but I think it is a little bit complicated to get across. Voiceover allows the user to interact with the contents of an email message or edit box rather, while interacting with the keyboard. And some of these interactions are more awkward when using this interface. For example, I can swipe up and down on the screen to navigate character by character, word by word, or line by line, depending on which setting is activated in the rotar. So, if I want to navigate the text while typing, I need not move my hands away from the keyboard. Instead, I can swipe up or down, navigate the contents, and make necessary edits with ease. However, when using this interphase, when I swipe up and down, I instead move through the contents of the keyboard like hearing the letter that I previously typed, and then nothing. To continue editing the email, I must single tap the body of the email message. Also, I can’t replicate exactly how to initiate this, but sometimes, maybe when I swipe up or down very quickly, instead of hearing contents of the email, I hear nothing after swiping up or down and I have to tap the message again to continue editing. This makes composing and editing text really awkward and could interfere with someone’s ability and patients to report a bug.

**Comment by aaronbrethorst** [comment]
I think I'll need to see an example of this in order to understand exactly what the user is seeing, unfortunately.
