### ISSUE TITLE
Bookmarks on the map table are missing some data

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1407]
### Expected behavior

The subtitle shows _something_

### Actual behavior

Nada.

### Steps to reproduce the behavior

1. Add a bookmark
2. Navigate across the map such that you can see the bookmark
3. Look at the Map Table 

### Screenshot of the issue (if applicable)

![img_21d239311c43-1](https://user-images.githubusercontent.com/2254/49774691-655c7c80-fcaa-11e8-8005-1004284eafca.jpeg)

### App Version/Hardware

18.2.2

**Comment by ajqjohnson199623** [comment]
Oh ok alright, I got my phone for app OneBusAway and I looking particular buses and nearly stops and also coach number for buses here in Seattle Area yesterday. But, I didn’t understand have an issue for me on my phone app for OneBusAway miss.

**Comment by ApolloZhu** [comment]
After some investigation, I found the cause of this issue. The text goes after is `routeShortName`

https://github.com/OneBusAway/onebusaway-iphone/blob/c9866d7a6fdc237fd5ed0996135a02967f7ddb67/OneBusAway/ui/MapTable/MapTableViewController.swift#L328

However, when saving bookmarks for stops, such field is not populated:

https://github.com/OneBusAway/onebusaway-iphone/blob/c9866d7a6fdc237fd5ed0996135a02967f7ddb67/OBAKit/Models/unmanaged/OBABookmarkV2.m#L45-L54

Therefore it is empty. Then, to solve this issue, we could 

1. Display the name only and no routes, like the bookmarks tab. (relatively easy)
2. Display the routes available at the stop, like nearby stops. Solutions I can think of are:
    1. Fetch the routes at that stop when building the view model (somewhat extra work)
    2. Save the routes in `routeShortName` when saving bookmark (need to update bookmarks tab)
    3. Create separate bookmark models for stops and routes (non-trivial)

Which one do you think I should implement? @aaronbrethorst
