### ISSUE TITLE
App fails to update data under some circumstances

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1422]
From a user:

> Hey folks - very often I find that if I’ve checked arrival times, then closed my phone, and then several minutes later I open the app again, it seems to hang when trying to update the arrival times. If I shut the app down and reopen it, it connects right away; but if I just wait, it never updates. 

Repro steps:

1. check OBA
1. look at a couple of other apps
1. lock phone
1. walk 5-10 minutes to the bus stop
1. unlock phone
1. switch back to OBA
1. then usually it won’t update. 

> if I am already, say, standing at the bus stop, and I do all the same things without the 5-10 minute interlude, it usually updates fine.

**Comment by alanborning** [comment]
There seems to be a problem sometimes when OneBusAway is on wifi, and then the user goes outside and needs to access data via cellular.  I've seen OneBusAway hang under those circumstances.  It is easy to fix by removing the app from memory and starting it again, but users shouldn't need to do this.

Could this be the cause of this bug?
