### ISSUE TITLE
Today Widget Route Directions

### ISSUE THREAD

**Issue by miklb** [OneBusAway/onebusaway-iphone#1424]
### Expected behavior
At a glance look at Today widget bookmarks and know which stop is which.
### Actual behavior
Have to click the stop to see which direction bus is traveling at that stop.

### Screenshot of the issue (if applicable)
![oba_today_widget](https://user-images.githubusercontent.com/819716/55081662-a79da400-5076-11e9-8d37-e7320f3f0b49.jpg)

If the direction (north or south in this case) were listed first rather than last, user can quickly discern the difference in the stops.

I'll note I do use larger text so perhaps that's why the direction gets truncated on the widget.

possibly related #1387

**Comment by aaronbrethorst** [comment]
Hi Michael - thanks for the report! The today widget displays the custom name that you give each bookmark displayed in it. I recommend renaming these to be something like “NB route x to work” so that it’s clear to you which is which.

**Comment by miklb** [comment]
Where do you edit that?

**Comment by miklb** [comment]
Nvm found it.
