### ISSUE TITLE
Spokane custom region not working

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1437]
see https://groups.google.com/d/msg/onebusaway-developers/JAs3DxRcfB0/n-wZQ0EEDQAJ

**Comment by barbeau** [comment]
To clarify, as of this morning Spokane is now an experimental region in the Regions API:
http://regions.onebusaway.org/regions-v3.json

**Comment by rwt88** [comment]
![Image-5](https://user-images.githubusercontent.com/17777262/62232085-42d2bd00-b37a-11e9-8a20-188db36f364a.png)
![Image-4](https://user-images.githubusercontent.com/17777262/62232087-42d2bd00-b37a-11e9-86b4-6e0ffdf06ee2.png)
![Image-3](https://user-images.githubusercontent.com/17777262/62232088-436b5380-b37a-11e9-9456-efb32d273ac5.png)

**Comment by rwt88** [comment]
![Image-6](https://user-images.githubusercontent.com/17777262/62232136-5b42d780-b37a-11e9-83aa-230d99303430.png)

**Comment by rwt88** [comment]
Also as I said when I try and add the location manually pressing the + I put in the proper input with the base URL being https://52.88.188.196/api and the location name being Spokane and the application shows a spinning circle which keep spinning. I also attempted https://53.88.188.195/api/ and it resulted in the same thing, a spinning circle that never ends.

**Comment by rwt88** [comment]
Outside of the TBD banner and the greyed out text, not being able to hit the API after I manually input it into the application might be an issue on my end. I tried to hit the above URL's from my browser, even though I have ports 443 and 8443 in my security group, I cannot seem to hit it. Ill keep checking this out on my end

**Comment by barbeau** [comment]
@rwt88 Ah - the URL I used in the Regions API used by the apps (http://regions.onebusaway.org/regions-v3.json ) is http://52.88.188.196:8080/api/.

iOS is currently stricter than Android on forcing SSL for HTTPS, so this might be the issue.

When you get HTTPS working from a web browser let me know and I can update the Regions API.

**Comment by aaronbrethorst** [comment]
This is now resolved.
