### ISSUE TITLE
Add Spokane, Washington to App Store listing

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#1440]
@aaronbrethorst A friendly reminder to add `Spokane, Washington` to the list of supported regions in the OBA iOS App Store listing.  They are now in production!

**Comment by aaronbrethorst** [comment]
Looks like I can't edit tags or description info until I submit a new version. I'll be sure to add it next update.

**Comment by aaronbrethorst** [comment]
I've added this to the description of the next version, which should be published in the next 1-2 weeks.
