### ISSUE TITLE
User feedback: Today View Widget not showing bookmarks

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1466]
User feedback:

> Widget does not work or refresh. Just always shows this. 

![today](https://user-images.githubusercontent.com/2254/72305477-c16d9f00-3628-11ea-83dc-fb2765a93332.jpg)

```
App Version = 20.1.0
iOS Version = 13.3
Bookmark Count = 1
```

**Comment by aaronbrethorst** [comment]
I'm pretty sure that this is being caused by an App Group misconfiguration issue caused by the switchover from the UW to OTSF Apple Developer accounts.

**Comment by ualch9** [comment]
I can't reproduce this bug on simulator or my device (app store 20.1.0). Clean app store install did not have the bug either. I don't think it's misconfigured app group.
