### ISSUE TITLE
data visible after a Edit bookmarks operation

### ISSUE THREAD

**Issue by ghotik** [OneBusAway/onebusaway-iphone#1468]
### Expected behavior
As in previous releases, when you confirm the edit bookmark operation you get back to the previous window with updated data
### Actual behavior
After editing, the previous window still shows the old data, though the data is actually updated and when you reload the bookmarks panel you get the correct situation
### Steps to reproduce the behavior
edit bookmark changing its name or group
confirm the operation taking not of values displayed on screen

**Comment by aaronbrethorst** [comment]
Fixed in https://github.com/OneBusAway/OBAKit
