### ISSUE TITLE
Stop Hidden by Map Drawer After Stop Search

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-iphone#1469]
### Expected behavior
After I search successfully for an existing stop, the map should zoom out and show my location and the location of the stop, or least the location of the stop I searched for.

### Actual behavior
The map zooms out but the map drawer is blocking the stop.  When I pan the map to see the stop, the search is cleared and the stop I searched for is no longer shown.

### Steps to reproduce the behavior
1) Search for a stop by ID (i.e. 10094 in San Diego)
2) Notice that the stop is hidden under the map drawer.
3) Pan the map to try and view the stop that is hidden.
4) The stop will disappear from the map (the search result is lost).

### Screenshot of the issue (if applicable)
![stop_search_issue](https://user-images.githubusercontent.com/5028299/75119763-b6038f80-563a-11ea-8a55-91627b499f23.PNG)

### App Version/Hardware
iOS 13.3.1
iPhone 10
OBA v. 20.1.0

**Comment by devinbraun** [comment]
Not sure if it's part of the same issue,  but after panning the map, the map drawer is blank and still blocking the map.

![map_drawer_blank](https://user-images.githubusercontent.com/5028299/75119832-6376a300-563b-11ea-95bf-c64fe0a7c877.PNG)

**Comment by aaronbrethorst** [comment]
Fixed in https://github.com/OneBusAway/OBAKit
