### ISSUE TITLE
Search by Vehicle ID Missing Vehicle Location

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-iphone#1470]
### Expected behavior
Search for a vehicle ID that is currently in service.  The vehicle is shown on the map on the route it is currently operating.

### Actual behavior
After searching by vehicle ID, the correct route shows on the map after searching for a vehicle by ID, but the vehicle icon is not shown on either the map or in the stop list.

### Steps to reproduce the behavior
1) Search for a vehicle by ID (in San Diego you could search for 601, 701, 1001, 1101, 1201)
2) The map zooms out to show the route the vehicle is on, but there is no indication on the map or in the stop list where the vehicle is located.

### Screenshot of the issue (if applicable)
![missing_vehicle](https://user-images.githubusercontent.com/5028299/75119885-d5e78300-563b-11ea-8656-d3f83719a900.PNG)

### App Version/Hardware
iOS 13.3.1
iPhone 10
OBA 20.1.0

**Comment by aaronbrethorst** [comment]
This should be fixed in the upcoming release (currently in TestFlight). Please reopen on https://github.com/OneBusAway/OBAKit if this is not correct.
