### ISSUE TITLE
iOS 14 crash

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-iphone#1479]
About 160 reported crashes, all running iOS 14.

Reproduction: Drag around the map and app will eventually crash.

itunes connect crash stack:
![Screen Shot 2020-08-31 at 11 14 12 AM](https://user-images.githubusercontent.com/22162410/91752462-43401780-eb7b-11ea-8153-d5955cb37ce5.png)
![Screen Shot 2020-08-31 at 11 18 45 AM](https://user-images.githubusercontent.com/22162410/91752800-be093280-eb7b-11ea-95e5-dd87ea76188f.png)

Haven't had the chance to debug on my device, so full stack trace is unavailable atm.

**Comment by ualch9** [comment]
will tackle this asap, 14 launches tmrw apparently.

**Comment by aaronbrethorst** [comment]
Thanks Alan. I'll publish a new release as soon as this lands.

**Comment by ualch9** [comment]
![Screen Shot 2020-09-15 at 8 18 06 PM](https://user-images.githubusercontent.com/22162410/93288414-9e375880-f790-11ea-9857-f148a8bf1a82.png)

The crash always happens during a move (but not necessarily every move)

```lldb
alan <IGListIndexSetResult 0x600001cf2740; 0 inserts; 0 deletes; 0 updates; 0 moves>
alan deletes: 0 indexes
alan moves: []
alan inserts: 0 indexes
alan end

alan <IGListIndexSetResult 0x600001c90fc0; 11 inserts; 0 deletes; 0 updates; 0 moves>
alan deletes: 0 indexes
alan moves: []
alan inserts: 11 indexes
alan end

alan <IGListIndexSetResult 0x600001362bc0; 2 inserts; 3 deletes; 0 updates; 8 moves>
alan deletes: 3 indexes
alan moves: [<IGListMoveIndex 0x600000f8fbc0; from: 3; to: 0;>, <IGListMoveIndex 0x600000f8fc00; from: 2; to: 1;>, <IGListMoveIndex 0x600000f8fc40; from: 6; to: 2;>, <IGListMoveIndex 0x600000f8fca0; from: 5; to: 3;>, <IGListMoveIndex 0x600000f8fce0; from: 8; to: 4;>, <IGListMoveIndex 0x600000f8fd00; from: 7; to: 5;>, <IGListMoveIndex 0x600000f8fd40; from: 0; to: 6;>, <IGListMoveIndex 0x600000f8fdc0; from: 1; to: 9;>]
alan inserts: 2 indexes
alan end

(lldb) ← EXC_BAD_ACCESS
```

Solution is to never give a Stop the opportunity to "move", so we diff identifier using memory instead of stop ID.
