### ISSUE TITLE
zoom in on current location forces zoom out sometimes

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#148]
On app start up if you try zooming in the app will force you back to a higher zoom level. This is extremely annoying when you are trying to zoom in on an area with lots of stops. [This video](https://www.dropbox.com/s/4tug0g22wcp8i3p/2013-09-05%2007%3A06%3A19%20%2B0000-mod.mp4) demonstrates me opening the app and then double taping to zoom in where you can then see the app automatically zooms me out and the process repeats.

**Comment by aaronbrethorst** [comment]
i haven't seen this in forever. please reactivate if this is still occurring.
