### ISSUE TITLE
Unable to send email feedback

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-iphone#1482]
From itc:

![image](https://user-images.githubusercontent.com/22162410/94302143-9b6efd00-ff20-11ea-9438-fccb3b40b4d9.png)

app works flawlessly when you don't receive any feedback amrite

**Comment by aaronbrethorst** [comment]
![image](https://user-images.githubusercontent.com/2254/94302298-dbce7b00-ff20-11ea-8e96-85be8e9b0148.png)
