### ISSUE TITLE
OneBusAway iPhone feature request tracker

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#156]
What free or for-pay feature request tracker (with voting features) do we want to use for the OneBusAway iPhone app?

There is an [IdeaScale page](http://onebusaway.ideascale.com/a/ideafactory.do?id=8715&mode=top&discussionFilter=byids&discussionID=46166) but it is very outdated and it doesn't seem anyone knows who owns the account. The various campaigns also seem to confuse it a bit as many ideas listed under all are iPhone specific and having them listed under all doesn't really help us prioritize what iPhone users are looking for.

Other options include [UserVoice](https://www.uservoice.com/plans/?ref=top_pricing) (free, [example](http://feedback.gitlab.com)), [Get Satisfaction](https://getsatisfaction.com/corp/pricing/) (pay, [example](https://getsatisfaction.com/getsatisfaction/)), [UserEcho](https://userecho.com/pricing/) (free, [example](http://feedback.inst.ag/))

**Comment by aaronbrethorst** [comment]
Closing. I think GitHub is working ok for the moment, especially in conjunction with Apptentive.
