### ISSUE TITLE
adjust stop icon size based on zoom level

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#157]
From IdeaScale [a user](http://onebusaway.ideascale.com/a/dtd/Bus-Stop-Markers/91292-8715) requested that we make the stop icons smaller. I think we should make the app icons adjust based on zoom level. This could also help address some concerns mentioned in https://github.com/OneBusAway/onebusaway-iphone/issues/62 in regards to showing stops at higher zoom levels.

**Comment by aaronbrethorst** [comment]
It looks like the issue that the user wanted addressed has more to do with being able to figure out which icon is the correct one, and be able to tap on the correct stop. Smaller stop icons might help in some respects, but would also decrease overall usability of the map. 

I think a more broadly successful strategy would be to incorporate the 'nearby stops' UI into the map, basically the same thing you propose at https://github.com/OneBusAway/onebusaway-android/issues/352. I'm closing this in favor of #318, which will be updated to reflect my notes here.
