### ISSUE TITLE
Bookmark routes

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#158]
From IdeaScale [a user](http://onebusaway.ideascale.com/a/dtd/This-is-a-great-app!/93810-8715) requested bookmarking routes. This is an interesting idea. Perhaps the bookmarks page could be updated to include a button to view your bookmarked stops or bookmarked routes. When in the routes view it could give you a link to the route details page as well as show you the nearest stops for that route.

**Comment by aaronbrethorst** [comment]
dupe #457
