### ISSUE TITLE
Update service alerts facility

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#182]
Redesign/improvement to the current service alerts facility.

**Comment by bbodenmiller** [comment]
For future reference here is what service alerts look like right now:

![image](https://cloud.githubusercontent.com/assets/1192780/10049888/79f4bbbe-61ce-11e5-9466-6158696a14ac.jpg)
![image](https://cloud.githubusercontent.com/assets/1192780/10049889/79fcc78c-61ce-11e5-91ce-79d50b2e44ad.jpg)
![image](https://cloud.githubusercontent.com/assets/1192780/10049890/7a04ad44-61ce-11e5-9ee0-a522f6b6ede4.jpg)
![image](https://cloud.githubusercontent.com/assets/1192780/10049891/7a15c584-61ce-11e5-9fa5-f21d585d90cd.jpg)

Also it appears alerts are working from the web app, for now.

**Comment by aaronbrethorst** [comment]
Service alerts work. They just need more data piped in. I'm going to do more in #881 too.
