### ISSUE TITLE
add help/app tour

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#193]
An IdeaScale [user](http://onebusaway.ideascale.com/a/dtd/Add-Online-Help/92643-8715) and some [TestFlight feedback](https://testflightapp.com/dashboard/builds/feedback/6631652/) have requested a help section and/or app tour feature. I think a first run app tour would be sufficient with an option for the user to access that app tour again from the Info tab.

**Comment by aaronbrethorst** [comment]
I've started adding callouts for features that need explanations and will do more in the future as need and opportunity dictate.
