### ISSUE TITLE
Arrivals for transfer stop should take into account ETA of selected trip

### ISSUE THREAD

**Issue by nalbion** [OneBusAway/onebusaway-iphone#2]
From the Trip Schedule list, it's possible to select a stop further along the selected trip (and the ETA at that stop is shown in the list).

If I'm on a bus that takes an hour to reach the stop I get off at, and I want to transfer to another service once I get there, the arrivals screen for that stop should show arrivals expected to arrive at my ETA, not now.

The arrivals-and-departures-for-stop service has an optional "time=n" parameter, this should be provided by the Trip Schedule list when a stop is selected.

**Comment by aaronbrethorst** [comment]
you're better off with an app that supports trip planning, which—unfortunately and for reasons totally outside of my control—is not OneBusAway. Try Google Maps, perhaps.
