### ISSUE TITLE
Add nearby stops to stop view

### ISSUE THREAD

**Issue by caitbonnar** [OneBusAway/onebusaway-iphone#225]
Received a suggestion from an OBA iPhone user today who pointed out that there used to be a 'nearby stops' button on individual stop views. (I'm guessing around where 'Add to Bookmarks' button is located.) Does anyone know the reason for its removal? 

I think it would be a useful feature to have put back; it would be quicker than jumping over to the map view, and if you accidentally choose the stop facing the other direction, it'd be easier to find the correct one.  Any other thoughts?

Also, this may be a separate issue, but I recall @bbodenmiller saying that it might also be handy to show nearby routes.  This may be helpful for the map view as an additional option, not sure about the stop view.  I'd like feedback on this idea as well.

**Comment by aaronbrethorst** [comment]
I fixed this in the latest builds.
