### ISSUE TITLE
Improve/validate Google Analytics checkpoints

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#255]
We should upgrade [TestFlight SDK](https://www.testflightapp.com/sdk/ios/download/) to the latest version so the TestFlight dashboard stops complaining. Additionally ideally the various Checkpoint's should be reviewed as some are passed multiple times when they shouldn't be and others are passed before the TestFlight session is started and thus not logged in the metrics (may also be partially addressed in the TestFlight SDK update).

**Comment by aaronbrethorst** [comment]
@bbodenmiller - is this issue still relevant?

**Comment by bbodenmiller** [comment]
I believe some of the ga logging events may still be reporting inaccurately so it is worth a detailed look.
