### ISSUE TITLE
change search box to unified search box

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#302]
Would be great to see the search box be more like the Android implementation where route, stop, and address searches are all performed without having to select which you'd like to search for.

**Comment by bbodenmiller** [comment]
Worth noting a user has reported some issues with the address search as follows (reported at http://seattletransitblog.com/2014/12/31/onebusaway-fixes-coming/#comments).

>  in the search put an address such as 3rd Avenue & Pike St. Where you should get skads and skads or result the result you get is “no routes found.”

I tried a search for "3rd Avenue & Pike St., seattle, wa", I get errors sometimes and nothing happens other times. Seems to be something wrong with address lookup.

/cc @caitbonnar @barbeau

**Comment by aaronbrethorst** [comment]
Fixed with #997
