### ISSUE TITLE
Region selection issues after most recent update

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#304]
It seems that some users are having issues being connected to the correct OBA server, which I believe started after the most recent app update was pushed out.

We're seeing messages from users that are getting directed to the OBA Tampa "Contact Us" email address, while the user's location in the email is in Puget Sound.  This shouldn't be happening, since if the below location was used to choose the region, then the email should have been directed to OBA Puget Sound's "Contact Us" email address.  I'm guessing the app is setting the region based on a bad first location fix, and then populating the email with a location that it grabs later.

Example feedback:
>When I try to look up a stop that I use frequently, the app is saying that the stop isn't found. And when I look up stops by number, the app says that they are out of the service area.
>App Version: 2.2.1
Device: iPhone5,3
iOS Version: 7.0.4
Current Location: 47.732867, -122.292577

------------

>My app keeps reporting out of service area even though it's been updated. Suggestions? 
>App Version: 2.2.1
Device: iPhone6,1
iOS Version: 7.1.1
Current Location: 47.633476, -122.341165

cc'ing @haneys @sheldonabrown

**Comment by aaronbrethorst** [comment]
calling this fixed for now after 2.4.1.
