### ISSUE TITLE
Custom API URLs aren't working

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#305]
After seeing https://github.com/OneBusAway/onebusaway-android/issues/126 I thoughts I'd see if the iOS OBA also had issues with port numbers in custom api URLs. I tried `aalborg.cs.washington.edu:80` which seems to crash/lock up upon entering the `:`.

**Comment by barbeau** [comment]
In v2.4.2 (20151215.15), I'm seeing some issues with entering custom API URLs again.  I'm not sure if these are new, or just haven't been reported until recently.

Our test server is `app.staging.obahart.org`, so requests are formatted like this:
http://app.staging.obahart.org/api/where/arrivals-and-departures-for-stop/Hillsborough%20Area%20Regional%20Transit_1688.json?key=TEST

In OBA Android, we can just enter the server name into the custom API URL text box.  However, entering either of the following into OBA iOS:

* `app.staging.obahart.org`
* `http://app.staging.obahart.org`

...results in the message "Server Address Invalid - Please check the URL and try again."  Both of these URLs should work.

The only URL that *does* work is:

* `http://app.staging.obahart.org/api/`

I encountered this on two different iPhones - the version info from one of them is below:

~~~
App Version: 2.4.2
Device: iPhone5,1
iOS Version: 9.2.1
~~~

We should also change the hint for the custom API URL text box on iOS to drop the `/api` following the server name (assuming we get resolve the above issue).  I originally advocated for adding this when I was first working with the OBA server stack, but in a correct server configuration it really shouldn't exist.  We've removed it on OBA Android.  This could be the source of the above URL formatting issues as well - we should assume a single `/api` exists in the URL path, not more than one.  So if the user enters `app.staging.obahart.org`, the assumed REST API request should be:

http://app.staging.obahart.org/api/where/arrivals-and-departures-for-stop/Hillsborough%20Area%20Regional%20Transit_1688.json?key=TEST

If they type in `app.staging.obahart.org/onebusaway-api-webapp`, the assumed REST API request should be:
http://app.staging.obahart.org/onebusaway-api-webapp/api/where/arrivals-and-departures-for-stop/Hillsborough%20Area%20Regional%20Transit_1688.json?key=TEST

One final related item - there is a quirk if you go to edit the server name, and hit "Done" in the keyboard without changing anything, it pops up a message that's something like "Server Address Invalid - It's not really invalid, you just didn't change it".  I'd prefer to not warn the user of this and just persist the new URL.  It's really confusing - it took me 3 tries of entering a valid URL before I read the small print and realized that it wasn't really rejecting it.

@aaronbrethorst Would you be able to prioritize a fix for this in the next release too?  It's complicating our testing at PSTA, as users need to type in one address on Android and another on iOS.

**Comment by aaronbrethorst** [comment]
@barbeau for sure.

**Comment by barbeau** [comment]
Awesome, thanks!
