### ISSUE TITLE
Change "Nearby Stops" functionality & UI on map view

### ISSUE THREAD

**Issue by caitbonnar** [OneBusAway/onebusaway-iphone#318]
Aaron says: I think the most obvious path forward on this, both from the perspective of enabling visually impaired users to better navigate nearby stops, and to help sighted users more quickly find their stop—especially in areas with many stops—is to place the 'nearby stops' UI onto the map, similar to what's mentioned in https://github.com/OneBusAway/onebusaway-android/issues/352.

---

Hi all,

As a current part of the evaluation of the StopInfo project, we have been interviewing blind and low vision transit riders, and have been hearing some feedback from them on accessibility issues with the iOS app (fortunately there aren't too many as of right now). One recurring request we've been receiving is that the 'Nearby Stops' list view on the maps tab is difficult to navigate via VoiceOver, since the tab bar controller disappears (which is a really useful navigation tool for visually impaired users), and there is no clear 'Back' button.  I think this is a general problem with consistency of layout as well. 

I wanted to see if you all had any feedback on a UI design that might be a suitable replacement. The quickest thing of course is just to add a back button, or to force the tab bar controller to remain on the page (which may require using a view other than a list view). It might also be a good time to evaluate the current layout of the list: another idea we've heard is to include an estimate of your current distance from the stop (something that would be useful for StopInfo as well). 

Anyway, I might have to wait until after this current project wraps up next month to get something in (it's been taking up most of my time at the moment), but I thought I'd introduce the issue now in case someone else wants to take it on or has any feedback.

**Comment by aaronbrethorst** [comment]
out of scope for 2.5.
