### ISSUE TITLE
Add iOS 8 TODAY screen to show a few favorite stop+route intersections

### ISSUE THREAD

**Issue by chadsy** [OneBusAway/onebusaway-iphone#322]
Pull down the today screen, see the next 1-3 buses of a specific route due at a specific stop. Killer feature for commuters who are always on one route at a small set of stops.

**Comment by aaronbrethorst** [comment]
Moving out of 2.4.

**Comment by beliyd** [comment]
This will be unblocked by #417

**Comment by beliyd** [comment]
@Wizecoder @aaronbrethorst I was thinking of messing around with this over next weekend, didn't want to interfere if work is already in progress though.   Thoughts?

**Comment by aaronbrethorst** [comment]
That sounds great, but I'd love to talk about design first.

**Comment by beliyd** [comment]
Something typical, shared user defaults + a simple Storyboard UI that uses same art assets as existing app, perhaps even re-use existing controllers through container controllers.

**Comment by aaronbrethorst** [comment]
Sorry, I should have been more specific: that sound great, but I'd love to talk about the user experience, and what data is exposed to the user in the Today screen.

**Comment by beliyd** [comment]
What would ya all like to be shown?

**Comment by bbodenmiller** [comment]
Personally I'd like the today screen to show the arrival times for the nearby routes that I've favorited. Unfortunately right now however we only track favorites at a stop level & not a route level.

**Comment by aaronbrethorst** [comment]
To second that, I'm in complete agreement with Ben that this is what we should be displaying. So for now, I guess, we can show the next 3(?) buses at the closest stops you've favorited perhaps.

**Comment by beliyd** [comment]
Cool.  I'll see if I can spike it over the weekend, will report back if anything un-expected comes along.

**Comment by aaronbrethorst** [comment]
Thanks!

**Comment by beliyd** [comment]
Started working on this.  

May need to do multiple smaller PRs out first laying the groundwork.

**Comment by aaronbrethorst** [comment]
Awesome :+1:

**Comment by beliyd** [comment]
@aaronbrethorst @bbodenmiller fyi.  The "develop" branch is not building.

error:  ld: library not found for -lPods-MarqueeLabel

I have cocoapods installed.

Any thoughts?

**Comment by bbodenmiller** [comment]
@beliyd assume build issue is fixed as your comment has been deleted? I just did a refresh clone and build from `develop` with no problems.

**Comment by beliyd** [comment]
Got pulled off into more work stuff :(   Unfortunately not looking good for me finishing this :(

**Comment by aaronbrethorst** [comment]
@beliyd no sweat, thanks for the heads up, and all of the help!

**Comment by aaronbrethorst** [comment]
Similar features in other apps:

![img_1154](https://cloud.githubusercontent.com/assets/2254/18613019/01e6acd2-7d24-11e6-9436-2b9267f2457f.PNG)

![img_1155](https://cloud.githubusercontent.com/assets/2254/18613020/01e77cb6-7d24-11e6-984c-6d6af56b4048.PNG)
