### ISSUE TITLE
Possible issue with "report a problem" feedback

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#324]
We've been seeing a number of empty feedback emails (i.e., just the template, no additional info) in Tampa from iOS users, and today someone reported that the app is crashing when trying to send email feedback via app:

>Tried to submit this through you app, but it crashed....
...
>App Version: 2.2.1
Device: iPhone3,3
iOS Version: 7.1.2

I don't know if the two (crashing and empty emails) are related.  Here are the version numbers of the other iOS devices that have sent blank emails:

>App Version: 2.2.1
Device: iPhone5,3
iOS Version: 7.1.2

>App Version: 2.2.1
Device: iPhone5,1
iOS Version: 7.1.1

>App Version: 2.2.1
Device: iPhone5,1
iOS Version: 7.1.2

Its possible that the empty emails are user error.

cc @cagryInside

**Comment by yogipatel** [comment]
@aaronbrethorst I'd be happy to look at this. Is there a test server I can point my test problem reports at?

**Comment by aaronbrethorst** [comment]
@barbeau would be the better person to ask

**Comment by barbeau** [comment]
@yogipatel We have a staging server set up in Tampa, so feel free to use this one to test if the server accepts problem reports - http://app.staging.obahart.org.  Although I'm not entirely sure that matches the production configurations being used in Puget Sound and Tampa. 

FYI - there were some server-side issues with problem reports failing in Puget Sound that I (and others) noticed on Android- see https://github.com/OneBusAway/onebusaway-application-modules/issues/126#issuecomment-112933871.  I don't know if this ticket is related, or a separate problem.  

In fact, I'm not entirely sure at the moment that OBA and iOS are using the exact same format to submit problem reports.  I have https://github.com/OneBusAway/onebusaway-android/issues/264 open on Android to check out problem reporting format for that platform, to see if it can be improved.  However, see also https://github.com/OneBusAway/onebusaway-application-modules/issues/69, I'm not sure if the OBA problem reporting API that is officially documented is working, although I know @sheldonabrown has been working on this.

@sheldonabrown are Puget Sound and Tampa running the same code for problem reporting APIs?  If so, do you happen to have a staging server that has the same code running (sorry, I know we co-opted your other test server)?  Also, were you able to confirm that the stop/trip problem reporting APIs work as documented at http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/report-problem-with-trip.html and http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/report-problem-with-stop.html?

**Comment by yogipatel** [comment]
@barbeau Thanks. On initial look, the app seems to be submitting the report properly (ignoring the fact that we're using GET instead of POST). I've found a related crash, but it doesn't affect the actual report submission.

@caitbonnar Which server were you running against when you were able to replicate this issue? Also, was there a specific sequence involved, or any time you added a lot of comment text, it failed? And how much text are we talking about, 1k characters, 8k? Most Apache servers will reject GET requests around 8k. Thanks.

**Comment by yogipatel** [comment]
Are we ignoring the possibility that the app does not auto-save the entered comment, ie the user has to hit the save button before navigating back to the report submission screen? It's a common behavior to fill something in and then go right back. I actually didn't catch explicit saving step my first time around either.
