### ISSUE TITLE
iOS app should allow Family Sharing

### ISSUE THREAD

**Issue by jessegoodnoe** [OneBusAway/onebusaway-iphone#339]
With iOS 8 and the new Family Sharing feature, users that are not the primary account owner can't download/buy/update OneBusAway.

Scenario:
Me - primary itunes account holder
My wife - a family share member on my itunes account

I can download OneBusAway from the iTunes app store.  She cannot.

Given that it's a free app, I see no reason to prevent Family Sharing.

**Comment by aaronbrethorst** [comment]
Doesn't look like there'll be an easy solution for this, and it's an external issue to boot. Closing.
