### ISSUE TITLE
"Continues as..." on stop list missing

### ISSUE THREAD

**Issue by caitbonnar** [OneBusAway/onebusaway-iphone#341]
I'm not sure when this started occurring, but today a user brought to my attention today that the option to see what route a certain bus changes into from the "Show as list" view has gone missing. AFAIK, we didn't touch anything that might have caused this in the iOS app in the last update. My guess right off the bat is that it has to do with a change with trips, specifically the tripID, from the API, since [here is the code that handles it](https://github.com/OneBusAway/onebusaway-iphone/blob/5b9c55fd18b3da223d1cd85f68679fd7340c4f7f/view_controllers/TripDetails/OBATripScheduleListViewController.m#L365-L391).

@barbeau or @sheldonabrown  Do you know what might be going on? 

Would be great to have this option working again in the iOS app, it's a feature that a lot of people really like.

**Comment by aaronbrethorst** [comment]
@barbeau any update on this?

**Comment by bbodenmiller** [comment]
A number of issues have been reported recently on the SoundTransit GitHub so perhaps worth posting there.

The issues raised recently are:
* https://github.com/SoundTransit/soundtransit-rds/issues/17
* https://github.com/SoundTransit/soundtransit-rds/issues/16
* https://github.com/SoundTransit/soundtransit-rds/issues/15

**Comment by barbeau** [comment]
@aaronbrethorst I don't know of any specific issue with trip_ids at the moment in Puget Sound.  But, as @bbodenmiller references, there do seem to be other issues surrounding GTFS in general.  Are you still finding missing values for previousTripId and nextTripId as referenced above by @caitbonnar?

**Comment by caitbonnar** [comment]
They seem to be showing up again. We can close this issue.
