### ISSUE TITLE
Bus arrival in-advance reminder on iOS app

### ISSUE THREAD

**Issue by timtianmingzheng** [OneBusAway/onebusaway-iphone#343]
I am a heavy user of the OneBusAway app. I use it twice a day to get to office and come back home. Usually, what time to leave office and go home is flexible. For me, I would leave around 6pm to 7pm. So I would prefer stay at office and work something not that serious until the bus is coming in 10 mins.

To achieve this, now I just frequently open the app, and keep refreshing the bus-stop schedule table. What I would prefer is that:
1. I will tell the app which bus-stop, how long for me to walk down there, at what range of time, which bus will I want to take.
2. When close to the time range, the app wakes up, starts keeping track of the target bus at the target bus-stop on behalf of me, and pops up an alert to kick me off the office in-advance.
3. I will check to the alert, walk down street, and meet the bus right away!
4. If I am in the middle of something, not checking the alert, no worries, the app will start tracking the next upcoming bus and repeat the same procedure until the pre-set time range is gone.

I believe this feature meets the intention creating this app: to help passenger better schedule their travel plan and save the idling time. Also I think this feature is technically feasible.

If you guys like the idea and give me a chance to contribute to the app, that would be fantastic, because this will be the first time for me to really join in a develop community and work on open source project.

I am open to any discussion on the feature details or the technical problems.

Sincerely,

Tim

**Comment by barbeau** [comment]
Note that there is a duplicate issue for this - https://github.com/OneBusAway/onebusaway-iphone/issues/242.

**Comment by aaronbrethorst** [comment]
this would be a cool feature for the eventual watchOS companion app.

**Comment by ualch9** [comment]
Began working on this [here](https://github.com/ualch9/onebusaway-iphone/tree/alarm) for iOS.

**Comment by aaronbrethorst** [comment]
@ualch9 please hang back on this. I lost track of this particular task but have about a week of time invested in solving this.
