### ISSUE TITLE
Warn about invalid custom APIs

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#347]
As mentioned at https://github.com/OneBusAway/onebusaway-android/issues/105#issuecomment-71123903 many people are using the custom API field as a freetext field for things like `seattle wa`. Perhaps validating the API and warning them if it is invalid would be useful.

**Comment by caitbonnar** [comment]
Sure, that seems like a good idea.

**Comment by barbeau** [comment]
+1 - This could cut down on some "my stops aren't showing up" feedback too, if users are messing with this setting and don't understand the consequences.  I would go as far as rejecting input that's not a working OBA server.

**Comment by aaronbrethorst** [comment]
@barbeau take a peek at my pull request, #477. I'm doing exactly that against the current-time endpoint. It seems like a safe, easy endpoint to test against. Thanks for the suggestion, btw.
