### ISSUE TITLE
Create a "Donate" link in the mobile app

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#349]
This would be for donations to the overall OBA project (not regions), and would direct to this link:
http://onebusaway.org/donate/

Currently the donation account is managed via UW, and used for overall project expenses.

Also ticketed for Android in https://github.com/OneBusAway/onebusaway-android/issues/201.

**Comment by caitbonnar** [comment]
Cool! Will add to the Ready list. :)

**Comment by barbeau** [comment]
Thanks @caitbonnar!  I haven't determined exactly how this would be shown in OBA Android (I assume in Help or Preferences lists), so please keep me posted for how it ends up being shown in OBA iOS.

**Comment by alanborning** [comment]
For the iPhone, how about if we put it at the top level under "Info".

**Comment by caitbonnar** [comment]
@alanborning That sounds like a good place to me, too. 

@barbeau Whoever works this in should post a screenshot so you guys can see what it looks like in iOS.

**Comment by aaronbrethorst** [comment]
fixed with #429
