### ISSUE TITLE
TestFlight changes required before 2/26/2015

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#350]
> Recently, the All-New TestFlight Beta Testing service was launched inside of iTunes Connect.  

> Here's What's New:
> * Invite up to 1,000 external testers using just their email address
> * Easy to use TestFlight iOS app available on the App Store
> * No need to keep track of UDIDs or provisioning profiles
> * Beta testing directly inside of iTunes Connect without the need of the TestFlight SDK

> [Learn more »](https://developer.apple.com/testflight/)

> With the new version of the TestFlight service available inside of iTunes Connect, we are also informing you that TestFlightapp.com will no longer be available as of 2/26/2015. 

> To prepare for the TestFlightapp.com closure, we recommend that you export all of your current testers so you can import them directly into the new TestFlight Beta Testing service.

> How to export testers from TestFlightapp.com
> 1. Sign in to the TestFlight Dashboard at testflightapp.com
> 2. Navigate to the "People" tab
> 3. Check mark the teammates you would like to export
> 4. Open the "Actions" menu on the right side of the teammates list
> 5. Select "Export Contact Info" to download the exported CSV file

> How to import testers into the new TestFlight Beta Testing
> 1. Sign in to iTunes Connect at itunesconnect.apple.com
> 2. Click "My Apps"
> 3. Select the app you want to enable for beta testing
> 4. Enter the "Prerelease" tab and select "External Testers"
> 5. Click the plus sign to add new external testers
> 6. Use the "Import File" from the "Add New External Testers" page to upload the exported CSV file

> For additional questions, please refer to our [FAQ](http://help.testflightapp.com/customer/portal/articles/1768754). 

> Thanks, 

> The TestFlight Team and Apple

**Comment by bbodenmiller** [comment]
Per the FAQ current apps will function just fine but we should remove the TestFlight SDK from future releases.

Additionally we'll need to update the readme to tell people how to join the beta program.

Lastly it looks like we may now be limited to 1000 testers as opposed to the previous unlimited with the enterprise license.

**Comment by caitbonnar** [comment]
Thanks for the update! I'll put this on the to do list. If you're able to remove the SDK from the app, that'd be awesome -- unfortunately I have a lot on my plate right now. I can do the overall account management stuff.

**Comment by caitbonnar** [comment]
Just exported all TestFlight testers over.

**Comment by bbodenmiller** [comment]
Also worth noting using the new platform we can only distribute to testers running iOS 8.

Any thoughts on a new signup process? Does iTunes Connect have any options?

**Comment by aaronbrethorst** [comment]
What percentage of testers running iOS 6 or 7 do we actually have today?

**Comment by bbodenmiller** [comment]
README still needs updating.

**Comment by aaronbrethorst** [comment]
@caitbonnar do you know what the process is for inviting new beta testers to the app with the new iTunes Connect-integrated TestFlight?

**Comment by caitbonnar** [comment]
@aaronbrethorst Yes, there is a spot to invite external testers under "Prelease" in iTunes Connect. Until you get that account set up, feel free to send me addresses of people you wish to invite, and I can get them sent out. Unfortunately it doesn't look like there is a link we can share where testers can sign up on their own and we can approve them, at least from what I can see. :(

**Comment by aaronbrethorst** [comment]
README updated. Thanks for the info, @caitbonnar!

**Comment by caitbonnar** [comment]
No prob!
