### ISSUE TITLE
Add another tracker for Google Analytics unique to OBA iOS

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#352]
While working on [OBA Android Google Analytics](https://github.com/OneBusAway/onebusaway-android/issues/105#issuecomment-71897488), we realized that Google's [Best Practices](https://support.google.com/analytics/answer/2587087) for tracking the same app on multiple platforms has changed.  Originally, they suggested using the same tracking ID on the various platforms.  Now, they are recommending using different tracking IDs per platform.  However, the catch is that to compare two apps using different tracking IDs (i.e., "rolled up reporting"), you need a subscription to Google Analytics Premium, which costs money.

To make OBA GA future proof, we should add another tracking ID to OBA iOS that tracks only iOS devices.  Here's our general strategy:

| IOS | Android |
| --- | :-: |
| tracker1 (existing property - actually "OBA SmartPhone" with iOS view) | tracker1 (existing property - actually "OBA SmartPhone" with Android view) |
| tracker2  (for rolled up reporting) | tracker3 (for rolled up reporting) |

So, OBA iOS would continue reporting analytics via the current tracker1 ID, but we would add tracker2 ID as well, via multiple trackers feature:
https://developers.google.com/analytics/devguides/collection/ios/v3/advanced#multiple-trackers

I grabbed a new tracker ID for tracker2:
- tracker 2 - iOS (unrolled) - **UA-2423527-18**

**Comment by aaronbrethorst** [comment]
I am not inclined to do this under a time crunch; instead I'd like to spend some time rethinking how analytics works across OBA for iOS. I'm going to push this into the next release when we're not under a time crunch.

**Comment by barbeau** [comment]
Agreed - we need to figure this out collectively as a project too (or at least between iOS and Android).  We're way over the free tier usage limit in GA, and as I understand it we're losing analytics data because of this.  Assuming no one can come up with the $150k/year fee for GA Enterprise, it looks like we're going to need to switch to GA sampling to get under the free tier threshold.
