### ISSUE TITLE
Seattle Hackathon (March 20-22, 2015) - Feature Ideas

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#353]
There's a transit hackathon coming up next month in Seattle, and I thought it'd be great to put together a list of cool features participants could build on top of OBA as part of it. Here's more info on the hackathon itself: http://hackthecommute.seattle.gov/2015/01/13/hackthecommute/

No dependencies that I can think of:

* Estimated or real bus position on the details page
* Saving bookmarks (i.e., starred stops) across platforms / devices - I think this could be done via Gogole Cloud Save, which includes support for Android, iOS, and web - see OneBusAway/onebusaway-android#32.
* Add ability to easily white-label project without forking code base - for Android, see OneBusAway/onebusaway-android#172.

Requires data loading changes: (may be obviated by #311, but tbd)

* Local notification alerts (i.e. a popup that tells you something like "the next #10 bus departs in 8 minutes")
* Today screen widget
* Apple Watch app

Depends on having a functioning OTP installation:

* Improved trip planner

From Reddit and Seattle Transit Blog

* display transit alerts (scrape from metro, st, etc)
   * display events affecting route (brige opening, protest, parade, etc)
   * map of reroute
   * reverse engineer KCM app?
* crowd source transit data (alerts, bus stop closures, full buses, reroutes, events causing delays, etc.) 
   * arrival data for routes with no realtime feed
   * particularly useful for link and sounder at this time
* better crowd sourcing of bus stop info (location, features, incorrect data, etc)
   * does it have realtime display?
* crowd sourced parking availability at transit centers
   * include historical data?
* crowdsource chronic incorrect data by stop and route
   * e.g. 21 at stop xyz always shows as late between 5-10 p.m. but then arrives ontime (see seattletransitblog comment)
* reminder for bus arrival
* reminder for stop being soon 
* bus location visualized on map (with ability to know if it is scheduled vs realtime)
* better predict arrival times based on historical ontime performance, traffic data, crowdsourced data, etc.
* better handle ghost buses (crowd source?)
* multiple ways to view bus data
   * ability to view arrival data for multiple routes at different stops on same screen (for when you are deciding between two buses or more buses)
   * ability to view arrival times for all nearby routes (like transit app)
* Everett Transit realtime data (https://github.com/SoundTransit/soundtransit-rds/issues/21)
* Seattle Streetcar realtime data
* Washington state ferry routes, realtime data, & alerts 
* trip planning (and multimodal trip planning)
   * possibility to deeplink google maps?
   * use api KCM app uses?
   * based on current realtime bus data
* orca balance & reload integration
* price per ride based on orca data
   * e.g. Would pass holder save money with pass, would non-pass holder save with pass
* wsdot and sdot traffic camera integration
* wsdot and sdot travel time integration
   * e.g. Now vs historical for this day/time
* Uber, lyft, zipcar, car2go, bike share, etc. integration
* cheap & easily deployable arrival screen (android tv, Apple TV, iPad, etc)
* map of realtime displays by type
* feature parity with KCM app and/or the transit app
* public dashboard to view OBA Google Analytics data
* ability to change base map & poi location provider
   * iOS maps, Google Maps, Foursquare, OpenStreetMaps, etc.

If you have additional suggestions, please add them to this list or to the comments below.

**Comment by barbeau** [comment]
**Cross-platform ideas:**

* Saving bookmarks (i.e., starred stops) across platforms / devices - I think this could be done via Gogole Cloud Save, which includes support for Android, iOS, and web - see https://github.com/OneBusAway/onebusaway-android/issues/32.
* Add ability to easily white-label project without forking code base - for Android, see https://github.com/OneBusAway/onebusaway-android/issues/172.

**Ideas for Android:**

* Trip planner - Could implement this client-side via integration (loose or tight) with our existing [OpenTripPlanner Android app](https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/wiki) - see https://github.com/OneBusAway/onebusaway-android/issues/25 and https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/21#issuecomment-25921169
* Automatically notify me when I'm approaching my destination - I think this would require trip planner integration to be efficient - see https://github.com/OneBusAway/onebusaway-android/issues/17 and https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/415
* Android Wear (i.e., watch) support - Some work has been started on this, but its been quiet for a while - see https://github.com/OneBusAway/onebusaway-android/issues/181
* Automatically notify me with arrival info when I approach my favorite stops - see https://github.com/OneBusAway/onebusaway-android/issues/184
* Add support for Uber / other ridesharing-ish services - see https://github.com/OneBusAway/onebusaway-android/issues/200
* Show bus position on map - I'll likely tackle this as part of the current UI work I'm doing, but other implementations/ideas for how to show vehicle positions is welcome.  See https://github.com/OneBusAway/onebusaway-android/issues/176 and https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/447

All Android development should be based on the current OBA `develop` branch, since we're in the middle of a UI overhaul - https://github.com/OneBusAway/onebusaway-android/tree/develop.

There are many other [issues marked with "Enhancement" tags](https://github.com/OneBusAway/onebusaway-android/labels/enhancement), but the above is the top list of items I think match best with a hack-a-thon.

**Comment by caitbonnar** [comment]
These all look good to me! The kickoff event is tonight --  hopefully there will be a good turnout!

**Comment by candacefaber** [comment]
Yes! Thank you! We had great turnout at the kickoff and would love to see OBA devs at the event. Registration is live at <a href="hackthecommute.brownpapertickets.com">hackthecommute.brownpapertickets.com</a>.

**Comment by jakebromberg** [comment]
Hi there!

I'm an iOS dev by day and wouldn't mind helping out with OBA. This hackathon would be a good chance to join in, if it's not too late. Need an extra pair of programming hands?

**Comment by candacefaber** [comment]
Definitely! Please register! We'll have a table dedicated to discussing OBA on Friday 3/20 prior to team formation. Let me know if you have any questions.

**Comment by aaronbrethorst** [comment]
@jakebromberg You don't have to wait for the hackathon to start working on OBA. Clone the project and go to town!

**Comment by jakebromberg** [comment]
I've registered for the event. See you guys there. Also, digging through the issues tickets to see what I can work on. Glad to join you folks!

**Comment by aaronbrethorst** [comment]
Thanks, @jakebromberg! Please see if anything in the 2.4 milestone catches your eye, but—if something from a later one sounds more appealing—I won't say no to any good PR :bowtie:

**Comment by bbodenmiller** [comment]
I'm reading through ideas on reddit and Seattle Transit Blog - here they are for others to consider:

* better handle ghost buses (crowd source?)
* display transit alerts (scrap from metro, st, etc)
   * display events affecting route (brige opening, protest, parade, etc)
* crowd source transit data (alerts, bus stop closures, full buses, reroutes, events causing delays, etc.) 
   * arrival data for routes with no realtime feed
* better crowd sourcing of bus stop info (location, features, incorrect data, etc)
* reminder for bus arrival
* reminder for stop being soon 
* bus location visualized on map (with ability to know if it is scheduled vs realtime)
* better predict arrival times based on historical ontime performance, traffic data, crowdsourced data, etc.
* ability to view arrival data for multiple routes at different stops on same screen (for when you are deciding between two buses or more buses)
* pull in Everett Transit realtime data
* trip planning (and multimodal trip planning)
   * possibility to deeplink google maps?
   * based on current realtime bus data
* orca balance & reload integration
* price per ride based on orca data
   * e.g. Would pass holder save money with pass, would non-pass holder save with pass
* crowd sourced parking availability at transit centers
   * include historical data?
* wsdot and sdot traffic camera integration
* wsdot and sdot travel time integration
   * e.g. Now vs historical for this day/time

**Comment by barbeau** [comment]
@aaronbrethorst Just curious if anything for OBA ended up coming out of the hackathon?

**Comment by aaronbrethorst** [comment]
Yes but it was @bbodenmiller's project, so I'd rather be spoke to it :)

**Comment by bbodenmiller** [comment]
I'm currently fascinated by crowdsourcing of information so I pitched an idea around crowdsourcing transit data and a number of other individuals jumped onboard. Think Waze for transit riders. Initially we focused it on tracking when buses are full with the option to later expand it to include ghost buses, accidents, breakdowns, reroutes, alerts, etc. Essentially the idea is the try and collect information the agencies are not yet providing, on events that may result in a passenger not being able to get on their bus. We made some progress but obviously a lot of work would be required to actually roll this into OBA. Specifically this would require backend changes or another backend and as you know getting Sound Transit to update their backend software is unlikely in the near future. It likely would be easier to setup another backend for this feature (at least initially - similar to StopInfo) and it sounds like there may be some Microsoft resources to help support that. You can see our work at https://github.com/OneBusAwaze/OneBusAwaze. Would love to hear your thoughts on getting this rolled in to OBA. We didn't place in the top 5 but had there been a crowd favorite seems we would have had a good chance - many people voiced their support for such a feature.

Team: @aaronbrethorst @veeseattle @phodiep @kpham13 @shiraissy @tonysip @cjtezak @YasharF @bbodenmiller

Worth noting many other projects tried to utilize data from OBA in one way or another. In particular one that looked very closely related to OBA was revamping the digital signs that show when the next bus is coming. http://hackthecommute.seattle.gov/2015/03/25/hack-the-commute-recap has a list of all the projects and repos.

**Comment by candacefaber** [comment]
Candace here, from Hack the Commute – would love to help keep this moving
forward in any way I can. I can put you in touch with the civic tech folks
from Microsoft and I'd encourage you to take advantage of the quick pitch
from non-finalists at the Championship Round on April 29, making whatever
specific asks from ST or the community on that platform. Let me know.

On Sat, Apr 4, 2015 at 1:54 AM, Ben Bodenmiller <notifications@github.com>
wrote:

> I'm currently fascinated by crowdsourcing of information so I pitched an
> idea around crowdsourcing transit data and a number of other individuals
> jumped onboard. Think Waze for transit riders. Initially we focused it on
> tracking when buses are full with the option to later expand it to include
> ghost buses, accidents, breakdowns, reroutes, alerts, etc. Essentially the
> idea is the try and collect information the agencies are not yet providing,
> on events that may result in a passenger not being able to get on their
> bus. We made some progress but obviously a lot of work would be required to
> actually roll this into OBA. Specifically this would require backend
> changes or another backend and as you know getting Sound Transit to update
> their backend software is unlikely in the near future. It likely would be
> easier to setup another backend for this feature (at least initially -
> similar to StopInfo) and it sounds like there may be some Microsoft
> resources to help support that. You can see our work at
> https://github.com/OneBusAwaze/OneBusAwaze. Would love to hear your
> thoughts on getting this rolled in to OBA. We didn't place in the top 5 but
> had there been a crowd favorite seems we would have had a good chance -
> many people voiced their support for such a feature.
>
> Team: @aaronbrethorst <https://github.com/aaronbrethorst> @veeseattle
> <https://github.com/veeseattle> @phodiep <https://github.com/phodiep>
> @kpham13 <https://github.com/kpham13> @shiraissy
> <https://github.com/shiraissy> @tonysip <https://github.com/tonysip>
> @cjtezak <https://github.com/cjtezak> @YasharF
> <https://github.com/YasharF> @bbodenmiller
> <https://github.com/bbodenmiller>
>
> Worth noting many other projects tried to utilize data from OBA in one way
> or another. In particular one that looked very closely related to OBA was
> revamping the digital signs that show when the next bus is coming.
> http://hackthecommute.seattle.gov/2015/03/25/hack-the-commute-recap has a
> list of all the projects and repos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OneBusAway/onebusaway-iphone/issues/353#issuecomment-89530797>
> .
>



-- 

Candace Faber

Seattle, WA

twt: @candacefaber

candacefaber.com
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2zGrQCVRYFSW5v0JBsW8rByXx56dwNGf80x9TM02?t=http%3A%2F%2Fwww.candacefaber.com%2F&si=6224883169099776&pi=c45d4e18-6c39-490f-bfff-6b8c7b0c0af0>

whoastrategies.com
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2zGrQCVRYFSW5v0JBsW8rByXx56dwNGf80x9TM02?t=http%3A%2F%2Fwww.whoastrategies.com%2F&si=6224883169099776&pi=c45d4e18-6c39-490f-bfff-6b8c7b0c0af0>

**Comment by barbeau** [comment]
Cool!  Yeah, crowd-sourced elements would be great in OBA.  For reference as this further evolves, you might want to check out [Moovit](http://www.moovitapp.com/) and [Tiramisu Transit](http://www.tiramisutransit.com/) - those are the two existing transit apps that I'm aware of that have major crowd-sourcing component.

I'd suggest posting info about the project to the OBA developers group (https://groups.google.com/forum/#!forum/onebusaway-developers) so its more visible in the context of the community.  I agree that setting it up so the backend is separate from the core onebusaway-app-modules is good to get started.

**Comment by aaronbrethorst** [comment]
Thanks, Sean. I'd seen moovit but not tiramisu
