### ISSUE TITLE
New project lead for OBA iOS

### ISSUE THREAD

**Issue by caitbonnar** [OneBusAway/onebusaway-iphone#354]
Hey everyone,

As I posted on the [Google OneBusAway dev forums] (https://groups.google.com/forum/#!topic/onebusaway-developers/WkoIO54dgcI) last week, I'll be passing off the OneBusAway iOS coordination to @aaronbrethorst from here on out! Just wanted to make an announcement here too since he will be in charge of handling PRs here now. 

I had fun working with all of you and will hopefully be able to keep contributing in the future. Feel free to keep on tagging me if you ever want my feedback on anything (particularly accessibility)! 

p.s. We can close this issue in a week or so - just wanted to make sure the announcement got out. Too bad there's not a "meta" label. ;)

**Comment by aaronbrethorst** [comment]
thanks again, @caitbonnar! :+1:
