### ISSUE TITLE
Alert for StopInfo survey

### ISSUE THREAD

**Issue by caitbonnar** [OneBusAway/onebusaway-iphone#366]
Hi all,

We're trying to deploy a survey that understands why people contribute information to StopInfo (or why they might want to) for an upcoming research conference. We also want to be able to improve the feature in any way we can in order to increase and maintain contributions. We were thinking it would be really useful to get participants by having an alert pop up to alert OBA users of the survey when they tap the info button to get into StopInfo. 

I wanted to see if this was feasible, as we have a relatively short time-frame to work with. Ideally we'd have to launch a new version sometime next week. @aaronbrethorst did you have a specific timeframe in mind for the next release? If it won't work out, that's okay -- just thought I'd check to see if it coincides with a launch. 

As to functionality, the alert would contain a link to the survey to open in Safari (we've played around with just having the link in StopInfo itself within the web view -- but it displays poorly in app, there's bad routing, and unfortunately there is no way to break out of the web view to open Safari (it doesn't have a URL scheme like other apps). Once they tap on the info button next to the stop name, or "About this Stop" under the arrival info, a pop-up would appear that asks them if they're interested in taking the survey... and they can tap "Yes," "No," or "Don't show this again." I'm open to other suggestions. We would take it out with the next update.

I'm generally wary of having pop-ups in apps asking to rate the app or visit other sites -- they're pretty annoying -- but if we could get even 20-30 more people because of this, it'd be worth it to us. 

I'll also be posting a more in-depth list of StopInfo improvements or fixes within the next couple of days. Analytics show it's accessed on average 1000 or so times a day (on weekdays), and it's been reported as being really useful by our blind and low vision participants, so it's a feature we want to stick around.

**Comment by bbodenmiller** [comment]
Seems like it would be easier to do this in the web UI using something like [Bootstrap modals](http://getbootstrap.com/javascript/#modals).

**Comment by caitbonnar** [comment]
@bbodenmiller I've tried a similar approach -- problem is that it still gets stuck in the web view controller because it thinks it's the native browser. I need the link to open in mobile Safari.

**Comment by aaronbrethorst** [comment]
@caitbonnar I don't have a good suggestion for you, offhand, unfortunately. Loading this in-app would definitely be the easiest way to go, and it's a bummer that won't work. 

I wasn't planning on releasing anything in the next week, but maybe you can just make that change off master, and resubmit to Apple as 2.3.2?

**Comment by bbodenmiller** [comment]
@caitbonnar any particular reason why it needs to be in native safari? I believe you can load iframes in the bootstrap modal.

**Comment by caitbonnar** [comment]
@bbodenmiller Basically just the usability is really bad. If they tap the app's 'Back' button at all (which is more salient than the survey's back button), the results get messed up. We don't really want to run that risk. If 'back' is pressed in Safari, it for some reason behaves better (I've been testing out a lot of different ways). The iframe may help with routing but I think is subject to the same problem. 

I'll talk to my team today and see what they say. It may be more trouble than it's worth, and there are still issues with it displaying correctly in the mobile browser (since we have to use certain survey forms for IRB, and they are not the best on mobile). 

Thanks to both of you for the input!

**Comment by bbodenmiller** [comment]
Have you thought about asking users to enter their email to be emailed the survey?

**Comment by caitbonnar** [comment]
@bbodenmiller We have a list of e-mails from people who have previously signed in to contribute, and are contacting them with the survey that way. However we'd like to reach a broader base, and especially allow people to be anonymous if they so choose (in accordance with our IRB), so we'd like the alert in addition. 

I talked with my team and they are pushing for us to include the alert, even if it requires an update with only that in place. @aaronbrethorst If this is still okay, I will work on getting that submitted today as 2.3.2. If you'd like me to include any other minor updates, let me know!

**Comment by aaronbrethorst** [comment]
@caitbonnar that sounds fine with me. I'd rather not include anything else, as it increases risk of destabilization. Thanks, though :)

**Comment by caitbonnar** [comment]
Sounds good, will let you know when this is submitted. Thanks!

**Comment by caitbonnar** [comment]
@aaronbrethorst @bbodenmiller @barbeau For future ref, the alert has so far worked really well for us -- it's been out for less than a day in the App Store and we've already gained over 100 new responses and some pretty valuable feedback. :-)

**Comment by aaronbrethorst** [comment]
:+1: :+1: :+1:

**Comment by barbeau** [comment]
Very nice!!  BTW - we were looking at the Google Analytics data today in context of testing OBA Android analytics, and we stumbled on some iOS StopInfo events being reported for regions outside of Puget Sound.  I believe @caitbonnar that you're using this analytics data for a paper, so just a heads up that you should filter by region before using the StopInfo numbers to make sure they reflect users actually accessing the StopInfo pages for Puget Sound.  I'll open an issue shortly for what we believe is a bug allowing StopInfo events to be reported in GA from outside of Puget Sound.

**Comment by caitbonnar** [comment]
@barbeau Yeah, I noticed that too -- will definitely make sure to do that. :-) The reason people can get to StopInfo outside of Puget Sound is because we always display the "About this Stop" button below the arrival times. A quick fix would be to take that out completely for regions outside of Puget Sound. 

However, that was done intentionally at first, to see if other regions were interested. We have an info page that it brings them to if they're outside of Puget Sound. (At least we used to - I'll have to check with Meg that it's still in there.) It gives details about the project and mentions it is currently only in Puget Sound. Maybe it would be easy to have a quick button or something that allows someone to request StopInfo for their region.

**Comment by barbeau** [comment]
@caitbonnar Ok, thanks, good to know.  Yes, the info page for outside Puget Sound does still work.  

We were confused because the info button is only displayed next to the stop name if there is a regional StopInfo server (i.e., you're in Puget Sound), but the "About this Stop" button is always shown, even if you're outside Puget Sound.  So, both buttons have the same resulting action, but they are displayed under different conditions.  I would suggest normalizing it so both buttons are shown/hidden together.  I do agree that it would be good to capture interest in the feature from regions that don't use it, but in the app analytics I'd like to be able to distinguish between interest in the feature, and actual use of the feature.  Right now from the app analytics it appears as if Tampa users are using StopInfo, even though it doesn't exist yet in Tampa.  I suppose you could cross-reference with StopInfo analytics logs, but that seems to be a complicated solution.

Does that make sense?  If so I can open an issue for these items so we can discuss the exact solution further.

**Comment by caitbonnar** [comment]
@barbeau Yeah, I think that was the product of trying to hurriedly code it in before our study... I agree that it should definitely be normalized. After this study finishes, I plan on opening an issue about better StopInfo integration too.

That makes sense about the analytics. We could also fire the analytics only if the region is currently Puget Sound. However because StopInfo is a web view, its analytics would go through the web site, which would be separate from the mobile analytics. We could send a parameter that would identify whether StopInfo was loaded from iOS, Android, or the Web, though. But you're right, it is more complicated. 

Feel free to open the issue now if you'd like -- I can tack on more StopInfo integration changes, or just reference the issue later from a separate issue. Whatever would be best for keeping things organized.

**Comment by barbeau** [comment]
@caitbonnar Ok, thanks!  I'll go ahead an open an issue just so this doesn't get lost.  Feel free to tack on or open a new one if the other things aren't exactly related.
