### ISSUE TITLE
New bookmarks button mockups and user study results

### ISSUE THREAD

**Issue by Wizecoder** [OneBusAway/onebusaway-iphone#368]
A few weeks ago Caitlin and I ran a couple of ~30 minute user study sessions with volunteers on campus. I built a couple of mockups and new feature ideas, and we got good feedback on them. The most positive feedback was probably for a new Bookmarks star that would make it more immediately visible that stops could be saved, and also give a nice visual treatment to the app.

All of the volunteers noticed the star and found it to be more intuitive then the current button, and one of the volunteers who had been using OBA for a while hadn't even used the current Add to Bookmarks button because it isn't visible without scrolling down if there are more than 6 or so upcoming arrivals, so it seems the star would definitely be an improvement.

Below I included the mockups for the updated stop screen, as well as an updated info popover (ignore the walking distance stuff). Due to a busy school schedule the last few weeks I haven't been able to build this yet, but it shouldn't take me more than a few hours work this weekend if we would like to try and get this into the next release. 

Thoughts?

![screen shot 2015-02-27 at 1 30 49 pm](https://cloud.githubusercontent.com/assets/354123/6421557/f4d7d296-be84-11e4-8512-75e555e36979.png)
![screen shot 2015-02-27 at 1 30 54 pm](https://cloud.githubusercontent.com/assets/354123/6421556/f4d79fec-be84-11e4-8597-d1d555fd137c.png)
![screen shot 2015-02-27 at 1 30 59 pm](https://cloud.githubusercontent.com/assets/354123/6421555/f4d7805c-be84-11e4-83c6-916adbb28d3f.png)

**Comment by barbeau** [comment]
I like the star to indicate the favorite - matches what we have on OBA Android.

**Comment by bbodenmiller** [comment]
I definitely think this is an improvement over the current bookmark process.

**Comment by caitbonnar** [comment]
:+1:

**Comment by aaronbrethorst** [comment]
looks good, but please remove the textual "add to bookmarks" item

**Comment by caitbonnar** [comment]
@aaronbrethorst Or maybe it should read "Edit Bookmark" or "Set Bookmark Group" or something if they've 'starred' the stop?

**Comment by caitbonnar** [comment]
Also, I think it would also be good to have a star on the popup bubble on the map view. I believe Android does it this way -- @barbeau is that correct?

**Comment by barbeau** [comment]
@caitbonnar In current production, no, but in the new UI design, yes (well, technically in the sliding panel header, not a map popup bubble, but same concept).  Something like this:

![oba-circlestopmarkerwithdirection-50](https://cloud.githubusercontent.com/assets/928045/5671393/8d98747e-9755-11e4-9568-e4ca54e9fd48.png)

**Comment by barbeau** [comment]
Final design for the sliding header TBD, but I do want to keep the favorite star there.

Just curious - did you do any testing for usability and size of star in the map popup bubble?  This is something I've been debating in the sliding panel header design.  The above star is approx. the smallest size Google style guidelines allow for a "tappable" button, but I've seen other apps (including Gmail) that use smaller stars.

**Comment by caitbonnar** [comment]
@barbeau Cool, thanks!

And no, unfortunately only had time to go over the basics (whether or not the star was intuitive as a bookmark indicator). That'd be interesting to look at, though. I'm not sure if iOS has similar guidelines, but I'd imagine so since they like things pretty standardized.

**Comment by Wizecoder** [comment]
It already changes to Edit Bookmark when one exists, so I think I will keep that button the way it is. It will also be different behavior, clicking that button creates the bookmark and take the user to a view to edit it to give it a name and group, whereas the star will just create it and leave the user on the stop screen.

**Comment by aaronbrethorst** [comment]
Different behavior that's part of the same feature. Here's what I'd like to see happen:

1. The refresh button is removed and replaced with a `UIRefreshControl`.
2. The star moves into the right side of the navigation bar.
3. By default, the star is unselected.
4. Tapping the star opens an action sheet with two options:
  * Add Bookmark
  * Cancel
5. Tapping Add Bookmark does what it sounds like, and the star is filled in.
6. Tapping the filled-in Add Bookmark button opens an action sheet with three options:
  * Edit Bookmark
  * Delete Bookmark (red, destructive style)
  * Cancel
7. Edit Bookmark is removed from the table view.

**Comment by Wizecoder** [comment]
Should I update other views to use a UIRefreshControl as well while I'm at it do you think, or just update this view?

**Comment by aaronbrethorst** [comment]
If you have time, yeah that'd be awesome!

**Comment by yogipatel** [comment]
@Wizecoder I'm down to knock this out if you're cool with it. Wizecoder/onebusaway-iphone@3314c76, right?

**Comment by aaronbrethorst** [comment]
mooted by new bookmark design
