### ISSUE TITLE
Tweak "contact us" section when custom API set

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#383]
When a custom API is set certain items in the contact us section should likely be tweaked. Currently it appears the email link results in a crash (it is also crashing now that I switched back to PS so unsure what is wrong). The Twitter links to the generic Twitter which seems fine. Facebook doesn't appear, so perhaps we should link to the generic Facebook.

Related to the similar Android issue: https://github.com/OneBusAway/onebusaway-android/issues/180

**Comment by bbodenmiller** [comment]
Just uninstalled and reinstalled OBA 2.4 beta and the contact us by email button causes a crash even without the custom API.

/cc @aaronbrethorst

**Comment by yogipatel** [comment]
@bbodenmiller I'll take a look at this if you can provide replication steps as I can't get the currect dev branch to crash by launching --> Info --> Contact Us --> Email.

**Comment by bbodenmiller** [comment]
You might give the master branch a try. I'm current running OBA 2.4 on iOS 8.1 and it's crashing when I try to use the contact via email feature when I use the steps you listed above.

**Comment by barbeau** [comment]
@yogipatel try setting the custom API as well (e.g., http://api.pugetsound.onebusaway.org) - seems like that may have triggered it initially?

**Comment by yogipatel** [comment]
@bbodenmiller Is it crashing for you on device or just the sim? Seems to be a known issue in the simulator, see: http://stackoverflow.com/a/25864182  It crashed on me in the simulator on 8.1 and 8.2, but it did **not** crash in 8.4. Might be a non-issue.

**Comment by bbodenmiller** [comment]
Crashing for me on the iPhone 5 device.

**Comment by yogipatel** [comment]
Unfortunately I don't have an 8.1 device handy. It works for me on 8.3 / iPhone 5. Do you have some crash reports that I could look at?

**Comment by yogipatel** [comment]
Unfortunately I don't have an 8.1 device handy. It works for me on 8.3 / iPhone 5. Do you have some crash reports that I could look at?

**Comment by bbodenmiller** [comment]
@yogipatel you have somewhere I can email them? Seems to have some unique data so don't want to post on here.

**Comment by yogipatel** [comment]
yogi.patel@gmail.com

**Comment by bbodenmiller** [comment]
Email button is working for me now that I'm on 8.4. Maybe it was an 8.1 issue.

**Comment by aaronbrethorst** [comment]
Closing. I haven't seen any further indications that this is still a problem.
