### ISSUE TITLE
Revise behavior of StopInfo icon/button and analytics

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#384]
Based on discussion started in https://github.com/OneBusAway/onebusaway-iphone/issues/366#issuecomment-77629301.

We were looking at the Google Analytics data today in context of testing OBA Android analytics, and we stumbled on some iOS StopInfo events being reported for regions outside of Puget Sound.  We initially thought this shouldn't be possible, since only Puget Sound has a StopInfo server set up (see https://github.com/OneBusAway/onebusaway-iphone/issues/213 for more about StopInfo in general).

It turns out that this is because the info button is only displayed next to the stop name on the arrivals screen if there is a regional StopInfo server (i.e., you're in Puget Sound), but the "About this Stop" button is always shown, even if you're outside Puget Sound.  So, both buttons have the same resulting action, but they are displayed under different conditions.  See below for behavior in Puget Sound vs. Tampa:

![stopinfoissue-combined](https://cloud.githubusercontent.com/assets/928045/6538065/114bdeee-c42b-11e4-9c37-e076ab850c2e.png)

I would suggest normalizing it so both buttons are shown/hidden together.

Additionally, currently the same analytics event "Loaded StopInfo from %@" is reported anytime a user taps on either the icon or button (see [code here](https://github.com/OneBusAway/onebusaway-iphone/blob/develop/view_controllers/StopDetails/OBAGenericStopViewController.m#L292)), and the "About this Stop" button is what is resulting in the StopInfo analytics events for regions outside Puget Sound that we observed.

I think that it would be good to capture interest in the feature from regions that don't use it, but in the app analytics I'd like to be able to distinguish between interest in the feature, and actual use of the feature.  Right now from the app analytics it appears as if Tampa users are using StopInfo, even though it doesn't exist yet in Tampa.  I suppose you could cross-reference with web StopInfo analytics logs, but that seems to be a complicated solution.

cc @cagryInside

**Comment by bbodenmiller** [comment]
I also think we should have two seperate analytic events so we can tell which button access method is used most.

**Comment by aaronbrethorst** [comment]
Mooted, stop info is dead.
