### ISSUE TITLE
Switch to CocoaPods for libraries

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#402]
Seems like it would be easier to manage additionally frameworks/libraries using CocoaPods. So far I've found the following already in use in the app that have CocoaPods:

* [TWSReleaseNotesView](http://cocoapods.org/pods/TWSReleaseNotesView)
* [libextobjc](http://cocoapods.org/pods/libextobjc)
* [MarqueeLabel](http://cocoapods.org/pods/MarqueeLabel)
* [GoogleAnalytics-iOS-SDK](http://cocoapods.org/pods/GoogleAnalytics-iOS-SDK)

**Comment by aaronbrethorst** [comment]
I'm cool with that.

**Comment by bbodenmiller** [comment]
Awesome. I'll work on this.

**Comment by beliyd** [comment]
CocoaPods ftw

**Comment by bbodenmiller** [comment]
Made good progress on this task. Currently stuck on #408 so @aaronbrethorst if you have a chance to look at that, that'd be great.
