### ISSUE TITLE
Does not properly prompt for region using simulator

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#408]
Update: It appears using the simulator the app does not properly prompt you for your region which then results in errors.

Original text:

It appears the simulator is not properly loading the agencies list using the latest code on the dev branch.

```
Apr  5 04:50:06 server.local OneBusAway[54410]: +[OBALogger(Internal) logError:prefix:] [Line 79] {
	    NSErrorFailingURLKey = "http://(null)/api/where/agencies-with-coverage.json?key=org.onebusaway.iphone&app_uid=E2BC7A9E-6999-4B73-B99E-D0067A17F7AC&app_ver=GIT_COMMIT_SHA&version=2";
	    NSErrorFailingURLStringKey = "http://(null)/api/where/agencies-with-coverage.json?key=org.onebusaway.iphone&app_uid=E2BC7A9E-6999-4B73-B99E-D0067A17F7AC&app_ver=GIT_COMMIT_SHA&version=2";
	    NSLocalizedDescription = "A server with the specified hostname could not be found.";
	    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1003 \"A server with the specified hostname could not be found.\" UserInfo=0x7fc19b09ab60 {NSErrorFailingURLStringKey=http://(null)/api/where/agencies-with-coverage.json?key=org.onebusaway.iphone&app_uid=E2BC7A9E-6999-4B73-B99E-D0067A17F7AC&app_ver=GIT_COMMIT_SHA&version=2, NSErrorFailingURLKey=http://(null)/api/where/agencies-with-coverage.json?key=org.onebusaway.iphone&app_uid=E2BC7A9E-6999-4B73-B99E-D0067A17F7AC&app_ver=GIT_COMMIT_SHA&version=2, _kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12, NSLocalizedDescription=A server with the specified hostname could not be found.}";
	    "_kCFStreamErrorCodeKey" = 8;
	    "_kCFStreamErrorDomainKey" = 12;
	}  userInfo:
```

**Comment by aaronbrethorst** [comment]
I occasionally run into this. It appears to be a bug with location simulation in the ios 8 simulator. Make sure to click the little location icon in the toolbar under the editor after you click Run. Choose the GPX file I added or add your own if you'd like. Let me know if you need any clarification.

**Comment by bbodenmiller** [comment]
Isn't this just for the multiregion api list? Seems it shouldn't have anything to do with the users current location.

**Comment by aaronbrethorst** [comment]
Hmm, you raise a good point. A workaround exists, but it is a frustrating one.

**Comment by bbodenmiller** [comment]
Looks like I misspoke and confused region & agency. However it does appear using the simulator that the app is not properly prompt for the users region.

**Comment by rajasagashe** [comment]
I'm getting the error loading regions when i run it on a iOS device. Here is the message, do you have any idea why it is happening, I haven't made any changes?

NSLocalizedDescription = "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.";
    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1022 \"The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.\" UserInfo=0x19f7e860

**Comment by aaronbrethorst** [comment]
New behavior in iOS 9.

**Comment by aaronbrethorst** [comment]
I've corrected the most egregious issues present here, and recommend using the two included GPX files for picking your region in the simulator.
