### ISSUE TITLE
StopInfo incorporation improvements

### ISSUE THREAD

**Issue by caitbonnar** [OneBusAway/onebusaway-iphone#411]
Hi all,

I've been meaning to get to this for awhile, but unfortunately with starting a new internship and moving to the Bay Area I got a bit distracted. Anyway, I wanted to make sure I documented some of the feedback I've gotten about StopInfo's incorporation into the iOS app before I forget. Unfortunately I don't think I'll have time (at least for awhile) to work on these myself, but I'm glad to provide high-level assistance where I can. 

Here are some ways I think we can improve integration with OneBusAway:

1. **A better button icon and/or placement of button in app.** This has been the most common request from general users as well as users with disabilities. The current icon (without high contrast mode enabled) is _difficult to see_ due to its thin weighting and contrast with the map behind it. It is also _difficult to tap_ for persons with motor impairments or people with smaller screens. The feedback about it being an info button has been mixed - some say that having it be the standard Apple info button was straightforward enough -- others said it was confusing because they thought they were already on the bus info page (bus arrivals). As it is currently, it does not have any indication that it leads to information about the _physical_ bus stop. Perhaps an icon showing a bus sign and shelter could be more intuitive? Open to suggestions here. 
We've also discussed taking out the redundant "About this Stop" table cell (#386), but I only recommend this if we improve the button design first (see [this comment](https://github.com/OneBusAway/onebusaway-iphone/issues/386#issuecomment-90747094)).
As noted in #384, the logic for displaying the info and 'About this Stop' button should be matched so that neither are displayed for regions that don't (yet) support StopInfo.

2. **Better navigation/routing within the web view controller.** Currently we only have a single 'Back' button in the StopInfo web view, which worked decently well when StopInfo was small, but has become more complicated now that StopInfo has grown to include more pages. (This was discussed initially in #280.) It gets messy when a user logs in or goes to edit a form and then has to go through several pages (I think sometimes including a form resubmission or an error after they've already signed in) to get back to the bus arrival times view. I am not sure if it would be useful to separate the Web back button and app back button again or to do some fiddling with the routing (probably web-side). Anyway, listing this here for reference/opinions.

3. **Pull applicable fields into ```OBAGenericStopViewController```.** This will probably have to come in to play if/when StopInfo produces an API, but wanted to throw it out there in case anyone is especially interested in taking this on. We've had requests for displaying reported stop closures on the arrival times page, as well as other fields from StopInfo that perhaps people could specify, or possibly notifications for information needs or requests (a feature currently being built into StopInfo where people can request information for particular stops) for that particular stop. From the survey, people indicated they would be more likely to contribute if they saw a request for information on the arrival times page while they were waiting for their bus.

Those are the main things I can think of for now. If anyone can think of things to add, let me know and I'll update the list accordingly. I would probably open a new issue (if one is not open already -- I tried to link relevant issues to each point) if you'd like to work on one of these items in particular.

**Comment by bbodenmiller** [comment]
I had a nice reply typed up that Chrome/GitHub decided to lose so the short version:

* I'd like to see an API for native integration. Web view could still be used for editing (FourSquare does this).
* I'd like to see suPport for crowdsourcing dats for not yet supported regions.
* Before an API is added https://github.com/TransitApp/SVWebViewController or something like the Facebook link popup may work better than the current web view.

**Comment by aaronbrethorst** [comment]
re @bbodenmiller's comments: :+1:

**Comment by caitbonnar** [comment]
Thanks @bbodenmiller. Copying @alanborning and @meganca here to see if they have anything to add.

**Comment by aaronbrethorst** [comment]
ping @alanborning and @meganca — is there a native API for StopInfo?

**Comment by alanborning** [comment]
No native API for StopInfo.  It would be a good thing to have, but no
immediate plans to add it.  (Currently nobody is working on StopInfo -
Caitlin and Meg have both graduated.)

**Comment by aaronbrethorst** [comment]
StopInfo is dead, sadly.
