### ISSUE TITLE
Notify user of new releases

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#415]
Despite automatic app updates 20% of our users in the last month were still using an old version of the app. We might consider adding a prompt to notify users that a new version of the app is available.

**Comment by chadsy** [comment]
Love this idea. Seems there are a few things to do/decide:

* App can automatically detect the current published version from itunes API (see below)
* Should *not* nag users who are using an older OS, given the move to iOS 8 with 2.4.0 this will be an issue
* Alternatively, could alter the message and suggest they update to supported a OS level
  * It's well beyond scope to determine whether the current device can run a later OS, so could mean that the message is inappropriate for some users
* Can asynchronously check for new version some time after app cold start
* Can handle with the usual Yes (go to storekit), Not now (try again next cold start), or Never (store the new version in NSUD to not nag again until there's a newer version)
* Is it interesting to present a specific update message? The release notes may not always reflect the most succinct or compelling reason.
* Has OBA ever encountered a scenario where an upgrade was required ASAP, e.g. major bug, API breaking change?

Fetch the [app store](https://itunes.apple.com/lookup?id=329380089) record, and use a few specific fields:

* version: "2.3.2"
* releaseNotes: "..."
* minimumOsVersion: "6.0"

@aaronbrethorst if this comes around on the backlog, I can flesh some of this out.

**Comment by aaronbrethorst** [comment]
I think that a simple solution to this would be great.

> Is it interesting to present a specific update message? The release notes may not always reflect the most succinct or compelling reason.

No. HOWEVER. I think there is a different user story worth considering that I keep meaning to log, and keep forgetting to do. We regularly see major data issues from Sound Transit. Users get frustrated, miss buses, and blame it on OBA. A potential solution would be to allow polling an URL for an optional message that would have an expiration time. Or, even easier, just poll a twitter account and display the message of its latest tweet if that tweet is less than 24 hours old, or whatever. So there's that.

> Has OBA ever encountered a scenario where an upgrade was required ASAP, e.g. major bug, API breaking change?

Not that I'm aware of. Sound Transit doesn't regularly update their OBA instance, either, so we'd probably have plenty of advance warning. 

@chadsy - if you're inclined to implement this, I'd say:

1. Go for it! As much as I'd love to have a PR for something that's at the top of my list (which admittedly only exists in my head at the moment), I'd much rather have you tackle something that you feel strongly about tackling.
2. Solve the simple case. No need for custom messages, or even checking OS compatibility.
