### ISSUE TITLE
Enhancement:  Project modularity

### ISSUE THREAD

**Issue by beliyd** [OneBusAway/onebusaway-iphone#417]
The project should be split into an SDK project and a separate application layer project. 

The SDK should contain the existing service layer + model abstractions, the app layer will contain UI and UIViewControllers.

I'll give it a go over the weekend :)

**Comment by beliyd** [comment]
Started working on this.  For the most part it is going pretty smooth.

Will require some refactoring as certain model/service entities depend on APIs that are not available to extensions and on view layer logic, but I don't expect it to be much work.

**Comment by aaronbrethorst** [comment]
We've already been down that path with onebusaway-iphone-common. I'd love to know what your use cases are for this work that will prevent it from being another iteration of that.

**Comment by beliyd** [comment]
I do remember seeing references to that in the past, but don't recall what it tried to achieve?

The idea behind this change is to split View + Controller logic from service/model layer and expose the service / model layer as a re-usable static library.

The app and the extensions would then link against this static library.

Sure, the code could technically be re-used through target inclusion, but that does not really scale tbh.

**Comment by aaronbrethorst** [comment]
Ok sounds good and thanks. I think the idea behind OBA common was roughly along the same lines as this, but it sort of withered due to a number of factors.
