### ISSUE TITLE
Don't animate the map zoom on application launch

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#42]
When you first open the app it starts at a very high zoom level and zooms in to your current location. I think we should take Google and Apple Maps lead and just start at the current users location.

**Comment by aaronbrethorst** [comment]
Resolution for this issue should be that when the app launches, the initial map 'zoom' is not animated.

**Comment by aaronbrethorst** [comment]
@yogipatel another good one for you
