### ISSUE TITLE
ui refresh

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#43]
What should the initial UI refresh look like? Here is the starting point:

![d53bc03a-ea3e-11e2-85d9-15faaac806ce](https://f.cloud.github.com/assets/1192780/796835/8eda60e2-ed31-11e2-8932-56a1f32b52c4.png)
![photo 1](https://f.cloud.github.com/assets/1192780/796850/058ea7a2-ed32-11e2-88e2-5208abcc8cb8.PNG)
![photo 2](https://f.cloud.github.com/assets/1192780/796851/05a3a3fa-ed32-11e2-8fdd-929aa09812b8.PNG)
![photo 3](https://f.cloud.github.com/assets/1192780/796852/060a41fa-ed32-11e2-8a0f-0509c7aaa2af.PNG)
![photo 4](https://f.cloud.github.com/assets/1192780/796853/06078082-ed32-11e2-8233-dcd2a89c50df.PNG)
![photo 5](https://f.cloud.github.com/assets/1192780/796854/0623bc84-ed32-11e2-9598-d799d243676e.PNG)

**Comment by aaronbrethorst** [comment]
A UI refresh is definitely in the cards, but I think it's more of a milestone than a single issue. Closing.
