### ISSUE TITLE
Privacy Policy URL 404s

### ISSUE THREAD

**Issue by yogipatel** [OneBusAway/onebusaway-iphone#431]
The privacy policy link in the info screen (http://onebusaway.org/privacy/) returns a 404. Either get that URL working, or update the app to the correct URL by modifying `kPrivacyURLString` in `OBAInfoViewController.m`.

**Comment by barbeau** [comment]
I'll work on fixing this on OBA.org.

**Comment by barbeau** [comment]
Related to this - I'm re-creating the privacy page, and we have a reference to OBA iOS using TestFilght for beta version distribution.  Is this still correct?  Or did we abandon TestFlight for OBA iOS?

**Comment by barbeau** [comment]
Ok, this is fixed - privacy page no longer returns a 404 - http://onebusaway.org/privacy/.  Just let me know about TestFlight, and I'll update the page as to whether its still used on iOS or not.

**Comment by bbodenmiller** [comment]
TestFlight is still used on iOS but TestFlight is now owned by Apple so the privacy policy has changed.

Some other comments on the privacy policy page:
* "Github" and other variants should be changed to "GitHub"
* Double spaces are unnecessary
