### ISSUE TITLE
Location button stays solid even when not tracking

### ISSUE THREAD

**Issue by yogipatel** [OneBusAway/onebusaway-iphone#432]
This was mentioned by @bbodenmiller in #430. The desired functionality is for the button to go "hollow" when the map is no longer tracking the user's location (similar to the location services icon in the status bar of iOS).

3x: ![](https://cloud.githubusercontent.com/assets/144539/8495105/bc069210-211f-11e5-829b-d94fc7b14757.png)

2x: ![](https://cloud.githubusercontent.com/assets/144539/8495159/2dcb24ec-2120-11e5-929d-fe1b6cf0fb12.png)

1x: ![](https://cloud.githubusercontent.com/assets/144539/8495200/6d01c5d0-2120-11e5-85e3-ee97d71e5451.png)

**Comment by yogipatel** [comment]
Well, I thought this would be easy to implement, but `OBASearchResultsViewController` seems a bit…complicated.

We can't use `MKUserTrackingModeFollow` because that forces its own zoom level (unless the user specifically zooms it to some other level). That usually results in a "Zoom in to look for stops" message. The user can still zoom in manually while tracking, but it's confusing. I tried to kludge a forced zoom after the tracking mode starts, but it's inconsistent and sometimes forces a zoom back out.

We can't use the built-in `refreshLocation` code either, since it also forces a zoom level (which the user might want to change, but still track). Additionally, we need to detect when the user pans the map so we can disable tracking. That would require a `UIGestureRecognizer` or similar. At the same time, it would need to support zooming *while* tracking, which won't work since our code forces a zoom level.

I'm not sure how to proceed as neither of those options is user friendly. The second option is at least possible to do. I'd rather just simplify `OBASearchResultsViewController`/`OBAMapRegionManager` and go from there.

@aaronbrethorst Thoughts?

**Comment by aaronbrethorst** [comment]
Is there a callback, notification, or KVO hook we can listen to that will tell us whether or not we're currently trying to find the user's location? If so, hook that and use it to drive the bar button item's selection state. If not, we'll find another option.

**Comment by yogipatel** [comment]
As long as the map controller's view is on screen, it will receive location updates. This is for tracking (following is probably a better term to use) the user as they move around. I may have misinterpreted what @bbodenmiller wanted from the button. My understanding was that it would turn on/off the map following the user as they move, like the Maps app does.

Do you know how the min zoom level (`kMaxLatDeltaToShowStops`) parameter was decided on? If we bump it up, we can probably use the built-in `MKUserTrackingModeFollow`. It's easy and smooth, but forces a level of zoom where we don't display stops.

**Comment by aaronbrethorst** [comment]
Brian's commit doesn't say why he chose that value. I assume it had something to do with performance characteristics of EDGE and 3G data connections. If it's easy to try out, I'd be interested in seeing what happens when you bump it up, but I can't guarantee that we'd be able to merge the changes.

**Comment by yogipatel** [comment]
It'd need to be bumped from `0.008` to `0.022`. I just checked that value, and there *are* areas where this results in exceeding the limit of stops returned by the API (even if we crank the maximum count up to 250), so that won't work.

OTOH, I was considering prototyping a change in how stops are loaded from the API and handed to the mapping system. Currently, they're loaded (and re-loaded) in what seems like a very inefficient manner. If you're open to that, I'll take a stab at it.

While I have your attention: what's supposed to be the minimum supported version of iOS?

**Comment by aaronbrethorst** [comment]
> OTOH, I was considering prototyping a change in how stops are loaded from the API and handed to the mapping system. Currently, they're loaded (and re-loaded) in what seems like a very inefficient manner. If you're open to that, I'll take a stab at it.

Sure, sounds great :)

> While I have your attention: what's supposed to be the minimum supported version of iOS?

iOS 8

**Comment by barbeau** [comment]
>It'd need to be bumped from 0.008 to 0.022. I just checked that value, and there are areas where this results in exceeding the limit of stops returned by the API (even if we crank the maximum count up to 250), so that won't work.

FWIW, there has never been a zoom limiter on displaying stops on OBA Android (back from before I started maintaining the app).  So even at a city zoom level, the app grabs the max. number of stops that the API returns and shows them on the map.  This does result in some non-deterministic-ish behavior where you move the map and different stops pop in and out, and we've talked about being less aggressive in loading.  However, we've never heard any complaints from users about this behavior, so we haven't touched it (IMHO, it does let you see where general transit coverage exists, so you can target your zooming in a bit better).  Alternately, we've heard complaints from OBA iOS users about not being able to see stops at all at higher zoom levels.  So, do with that what you will :).

>OTOH, I was considering prototyping a change in how stops are loaded from the API and handed to the mapping system. Currently, they're loaded (and re-loaded) in what seems like a very inefficient manner. If you're open to that, I'll take a stab at it.

I actually just implemented something similar on OBA Android - previously, if you moved the map a tiny bit, all the markers were cleared and the app hit the API endpoint again with the new bounds, and displayed the result on the map.  With the modern Android Maps API v2 this resulted in some flickering and strange behavior.  And, even with the old Maps API it result in stops disappearing that were just in view if you scrolled away and back again.  I changed to caching the stops, and only clearing the map and reloading from scratch when the number of stops on the map exceeded a threshold.  Result is much better experience for the user, IMHO.  Not sure if its useful given that it's on Android and in Java, but the main data structures for the implementation are [here](https://github.com/OneBusAway/onebusaway-android/blob/develop/onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/StopOverlay.java#L641).

**Comment by aaronbrethorst** [comment]
@barbeau awesome, thanks for the info and context!

@yogipatel go for it :)

**Comment by yogipatel** [comment]
@barbeau Thanks for the info, that's helpful to know. The existing iOS app does what the previous Android app would do, namely hitting the API again for stops it already has. I don't like the idea of the non-deterministic-ish stops, but agree that it probably is fine from a user's perspective.

So I threw one idea together a prototype into a separate repo (yogipatel/oba-playground@586f481). It's by no means compete, I'm just trying to see if this approach might work.

What it's doing is treating stops just like map tiles. That is, the world is split into chunks Xº tall/wide and the loader then makes API calls in increments of that size. There's a setting for what that size is (`kChunkSize`) in https://github.com/yogipatel/oba-playground/blob/master/Test/TileLoader.m I'm not doing anything fancy, the lat _and_ long are set to the same value even though it's not technically the same distance. There's also a setting (`kNeighborhoodSize`) for how many chunks to load at a time. Here's some ASCII art:

```
    0   1   2   3   4   5  
  +---+---+---+---+---+---+
  |   |   |   |   |   |   |
0 |   |   |   |   |   |   |
  |   |   |   |   |   |   |
  +-----------------------+
  |   |   |   |   |   |   |
1 |   | L | L | L |   |   |
  |   |   |   |   |   |   |
  +-----------------------+
  |   |   |  X|   |   |   |
2 |   | L | L | L |   |   |
  |   |   |   |   |   |   |
  +-----------------------+
  |   |   |   |   |   |   |
3 |   | L | L | L |   |   |
  |   |   |   |   |   |   |
  +---+---+---+---+---+----
```
The above is a representation of a map split up into some `kChunkSize` with a `kNeighborhoodSize` of 3. The `X` in the `2,2` chunk is the center of the map, as the user sees it. API calls are made for each chunk marked `L`. So 9 total requests are made for `1,1`, `1,2`, `1,3`, `2,1`, etc.
```
    0   1   2   3   4   5  
  +---+---+---+---+---+---+
  |   |   |   |   |   |   |
0 |   |   | L | L | L |   |
  |   |   |   |   |   |   |
  +-----------------------+
  |   |   |   |   |   |   |
1 |   | C | C | C | L |   |
  |   |   |   |X  |   |   |
  +-----------------------+
  |   |   |   |   |   |   |
2 |   | C | C | C | L |   |
  |   |   |   |   |   |   |
  +-----------------------+
  |   |   |   |   |   |   |
3 |   | C | C | C |   |   |
  |   |   |   |   |   |   |
  +---+---+---+---+---+----
```
The user now pans the map so that `3,1` is the center. The new "neighborhood" (the 3×3 area centered on the map center) is a combination of some of the old chunks and some new. Here only 5 requests are made. Chunks marked `C` are "cached" (sortof) from the previous load(s).

And we basically just keep doing that as the user pans. When the user zooms, the area that is loaded doesn't change, so they just see a smaller area's stops loaded.

The idea is to avoid annotation-thrashing and reloading stops we're already aware of. Performance doesn't really feel all that much different until you zoom out and have all of Seattle's stops staring at you. Even then, it's still reasonable given what it has to deal with. We can always set a max zoom out and hide the annotations or maybe do some clustering.

Of course we'll still need some way of expiring loaded stops, and I have a few ideas for that, but wanted to see what you guys thought of this approach. I think if we refine/tune it right, we can have a better user experience as well as greatly reduced server load.

The settings in the repo right now come out to ~a chunk size of 1.1km × 0.75km and a 5×5 neighborhood, which is about 20km².

Comments please :)

**Comment by yogipatel** [comment]
[Preview](http://i.imgur.com/zucalp9.gifv)

**Comment by bbodenmiller** [comment]
Sounds like an interesting concept but we probably don't want to hit the API 9 times for a query of nearby stops given the encouragement these days to reduce individual requests. How about 1 API request every map move and just not redrawing pins that are already loaded?

Better option would probably be just cache all stops in a region and then figure out a mechasm for when to expire them. This would also allow some offline usage the app doesn't support today.

**Comment by aaronbrethorst** [comment]
@yogipatel sounds like a great idea in general. It'd be interesting to map out what real-world API usage looks like today versus with your model. In addition to @bbodenmiller's concerns, I'm also sensitive to racking up a significant amount of cellular data usage on our users' phones, and the higher latency connections we'll see in the wild.

So, all told: I'd be interested in seeing what this would look like with a reload on map move. I love the idea of having already-cached pins available for the user as soon as they move the map, but I'm concerned about the issues mentioned above.

Still, all that said, I think this is looking awesome, and I'm excited to incorporate more of your work into the project. thanks again!

**Comment by bbodenmiller** [comment]
I echo @aaronbrethorst, this work and the other work you've done for the app is awesome!

What about loading more aggressively when the user is on WiFi and less so when on cellular?

As for the user tracking what I was hoping for is similar functionality as exists in most map apps. I imagine the most out of the box solution would be best for maintainability purposes.

**Comment by yogipatel** [comment]
Thanks for the feedback guys. Would you mind giving me one or two typical usage scenarios that we'd want to optimize for? I'd be happy to run some of the numbers. I don't really care if we use this approach or not, it was just a shock to me at how inefficient the current app is in terms of redundant data transfer.

So this is setup so that when a user pans, the stops are already there (within reason), so we never ask the server for the same stops twice, and so that the user can zoom out and still see stops in context. Admittedly I approached this from how _I_ was most recently using the app — by just panning around a bunch and figuring out where it's inefficient. How do real people use the app though? :smile:

As far as only loading one section at a time, I can't immediately think of a straightforward approach to that without doing things in chunks w/multiple requests like I am here. There needs to be a reference partitioning of space to prevent reloading of preexisting data. That's why every mapping application does things in tiles (that and being able to zoom easily).

For example, if I load a screen full of data, then pan diagonally 1/3 of the way to the corner, what would my API call(s) look like? To prevent a redundant request, I'd need to split the newly revealed part of the map into 2–3 requests, since I can only request stuff in rectangular shapes (radius based requests won't help). That's basically what I'm doing anyway, sans that initial load of the surrounding areas. The other option is to make one call for the whole screen, but that would return a lot of stops already loaded.

In any case, I'm happy to go with whatever approach you guys want.

**Comment by yogipatel** [comment]
@bbodenmiller I think we could be less aggressive on slower connections, but I'd need to think about that. And yea, adding location tracking is usually really simple, but this time it's not.

**Comment by aaronbrethorst** [comment]
@yogipatel for some reason, I cannot assign this issue to you, but I think this would be cool to implement. I want to make sure we're not saturating the user's data cap, but I love the concept and think this is absolutely the direction in which we should move. :+1:

**Comment by aaronbrethorst** [comment]
https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKUserTrackingBarButtonItemClassRef/index.html#//apple_ref/occ/cl/MKUserTrackingBarButtonItem
