### ISSUE TITLE
Project does not build with Xcode 7 GM. can't find the .xcodeproj to disable Bitcode.

### ISSUE THREAD

**Issue by tomtclai** [OneBusAway/onebusaway-iphone#440]
>ld: '/Users/tomlai/onebusaway-iphone/Pods/GoogleAnalytics-iOS-SDK/libGoogleAnalyticsServices.a(TAGDataProvider.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
>clang: error: linker command failed with exit code 1 (use -v to see invocation)

I know i can [disable Bitcode](http://stackoverflow.com/a/30856364/3614291) if I can find the .xcodeproj for GoogleAnalytics, but looks like it doesn't exist. I tried disabling Bitcode in all the .xcodeproj files I could find (there are 3, right?), but no luck.

Thoughts?

**Comment by aaronbrethorst** [comment]
@tomtclai any reason you closed this? We'll need to grab a new Google Analytics lib at the very least. You can also set `ENABLE_BITCODE=NO` in the OBA xcodeproj.

**Comment by tomtclai** [comment]
Yes. I closed it after I did what you said with the OBA Xcodeproj. And
then I made a pull request about this, which probably didn't show up here.
Oops
