### ISSUE TITLE
Contact via Facebook/Twitter not opening using native app

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#453]
Previously clicking Twitter under the Contact Us menu would open the native app if installed. On iOS 9.0.2 using the 8.4 beta it's only ever opening Facebook & Twitter via web.

Clearly this is a very low priority.

**Comment by aaronbrethorst** [comment]
Probably a result of the changes in iOS 9 to the `-canOpenURL:` API.
