### ISSUE TITLE
Rationalize and sort out failure cases in the map controller

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#463]
This was a user-reported issue on OBA 2.4.0. I've seen this a reasonable number of times before, but it's disconcerting that two different people connecting to the same OBA instance are seeing the issue.

![img_5641](https://cloud.githubusercontent.com/assets/2254/11387407/00314db4-92df-11e5-93ef-85cfe2ddd2ee.PNG)

**Comment by barbeau** [comment]
FWIW, someone forwarded me this link in context of this issue:
http://iosdevtips.co/post/121756573323/ios-9-xcode-7-http-connect-server-error

If its not relevant, please feel free to ignore :).

**Comment by barbeau** [comment]
Also, apparently this is consistently reproducible with RVTD (Rogue Valley, Oregon) region:
https://groups.google.com/forum/#!topic/onebusaway-users/8JCn3k4diQo

**Comment by barbeau** [comment]
The one thing that seems different about RVTD when compared to other production regions is that it has a port number in the URL:
http://oba.rvtd.org:8080/onebusaway-api-webapp/

The only other region that has a port number in the URL is Lappeenranta, Finland (beta):
http://194.89.230.196:8080/

You may want to see if this is consistently reproducible with the Lappeenranta region too.

See the Regions API results for all the `obaBaseUrls`:
http://regions.onebusaway.org/regions-v3.json

**Comment by barbeau** [comment]
@aaronbrethorst Re-opening - sounds like this is still an open issue based on https://groups.google.com/forum/#!topic/onebusaway-users/e5en7uiQx-A and https://groups.google.com/d/msg/onebusaway-developers/aXv5ojoLrEA/QqyTgp0nCgAJ?  If not please close.

**Comment by aaronbrethorst** [comment]
Closing since this (thankfully) hasn't popped up since I made the ATS fix some months ago. Please reopen if it occurs again.
