### ISSUE TITLE
Stop #263 E bound is in the wrong location

### ISSUE THREAD

**Issue by revoltpuppy** [OneBusAway/onebusaway-iphone#464]
Harrison at Plymouth is currently in the wrong location on the map. What's marked is the old location, across the street from the W bound stop.

In reality, this stop moved a block west, to be between Perry and Plymouth streets.

**Comment by bbodenmiller** [comment]
The OneBusAway iPhone app just pulls the data from the Sound Transit OneBusAway server so you'll need to file this with them at https://github.com/SoundTransit/soundtransit-rds.

**Comment by revoltpuppy** [comment]
Thanks, I've reported it there.
