### ISSUE TITLE
Add "Rogue Valley, Oregon" to supported agencies in App Store listing

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#472]
We added RVTD in "Rogue Valley, Oregon" as an official production region in Sept (see https://groups.google.com/forum/#!topic/onebusaway-developers/-BC9aI4XYo8), but it's currently not listed in the App Store listing under "Supported agencies".

@aaronbrethorst Could you please add it?  Thanks!

**Comment by aaronbrethorst** [comment]
Will do.

**Comment by aaronbrethorst** [comment]
Done! Not sure exactly when it'll show up, but it should be soon.

    Supported agencies:
    * Atlanta, GA: Cobb Community Transit (CCT), Georgia Tech Trolley and Stinger Shuttles, Metropolitan Atlanta Rapid Transit Authority
    * Seattle, WA: King County Metro, Sound Transit, Pierce Transit, Intercity Transit, Community Transit, and Washington State Ferries 
    * Tampa, FL: Hillsborough Area Regional Transit (HART)
    * Rogue Valley, OR: Rogue Valley Transportation District (RVTD)
    * York, Canada: York Regional Transit (YRT), Viva

**Comment by barbeau** [comment]
Thanks!
