### ISSUE TITLE
Append the current regionName to the map's search box placeholder text

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#507]
When I'm working on OBA in the iPhone Simulator, it can be hard to tell if OBA is refusing to show me my current location because there's a bug with region selection or because locations in the Simulator only work through GPX files (and you have to manually select one—boo).

So, let's solve this problem and add a little bit of contextual information that our users may enjoy. When the app starts up or when the selected region changes, let's put the current region's name (`regionName`) into the search box. Here's what it should look like for Puget Sound:

![screen shot 2015-12-16 at 6 12 43 pm](https://cloud.githubusercontent.com/assets/2254/11859581/1cc06638-a421-11e5-9f5c-90a8bc95278a.png)

**Comment by barbeau** [comment]
+1 - did it just say "Search" previously?

**Comment by aaronbrethorst** [comment]
@barbeau It just says "Search", yeah. There's nothing wrong with that, but it feels more...personal this way, and it's useful as a debugging aid.

**Comment by barbeau** [comment]
Agreed!  Is there still an indication somewhere that you can search by address, stop ID, or route ID?  I thought I remembered seeing that at some point, but it could have been an old version.

**Comment by aaronbrethorst** [comment]
@barbeau Yep, tap on the search box and it shows you the 'scopes' by which you can search: address, stop #, or route #.

**Comment by barbeau** [comment]
:+1:

**Comment by aaronbrethorst** [comment]
fixed
