### ISSUE TITLE
Some stops disable the "Tap to load more arrivals" button after one load

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#514]
From a user:

> I did see one strange anomaly with the ‘Tap to load more arrivals’ function. It works as expected at most stops, but at stops #1120 - W bound, #590 - NW bound and other stops located on 3rd Avenue, the app will only allow for one use of the ‘Tap to load more arrivals.’ After that, the link is ghosted. This is not the case at other stops I use.

I've been able to reproduce the issue at stop 1120. The logic in `OBAGenericStopViewController` for figuring out what's enabled and disabled, and what goes where is a bit crazy. It would be awesome to overhaul this and rebuild the logic for figuring out which cells go where on top of my static table code.

**Comment by yogipatel** [comment]
On it.

**Comment by aaronbrethorst** [comment]
fixed w/ the MVVM rearchitecture.
