### ISSUE TITLE
Use local Regions API response bundled with app in case of centralized Regions API failures

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#517]
The OA Regions API (http://regions.onebusaway.org/regions-v3.json) is a centrally hosted API at UW that provides all the OBA apps with a directory of OBA servers/regions, as well as their geographic locations, so the apps know which local server they should send API requests to, based on the location of the mobile device.  The Regions API is queried upon initial app installation to fetch the regions list, and occasionally in the background to update this information.

Over the last few months, we've been seeing more frequent failures of the Regions API at UW, where requests eventually timeout.  This is a significant problem, as it affects users of all OBA regions (unlike a local OBA server failure, which would affect only users in that region), and without region information the app is unusable, even if the local OBA server is up and running.  We're working to try and increase the reliability of the Regions API, as well as the watchdog systems that tell us when things go down.

To reduce the potential for centralized OBA failures affecting end users, on OBA Android we bundle a JSON response from the Regions API with the app to use in the case that the centralized Regions API fails.  This bundled response is obviously older than the actual Regions API response (updated when the last app update was pushed), but the contents of the Regions API typically don't change frequently, and old region info is better than an unusable app.

@aaronbrethorst Could we implement this bundled Regions API response in OBA iOS as well, so the app is still usable when the Regions API fails?  I don't believe this is currently implemented on OBA iOS, but correct me if I'm wrong.

**Comment by aaronbrethorst** [comment]
@barbeau Yeah, we can take care of this. Do you know what's up with the regions API and what's being done to rectify this issue?

**Comment by bbodenmiller** [comment]
Related comment that I left at https://github.com/OneBusAway/onebusaway-android/issues/408#issuecomment-168756114:

> Why not move the json file to be served directly by GitHub or GitHub Pages? Another option would be hosting it with a CDN (e.g. MaxCDN is $0.06 per GB). Something like the free plan on CloudFlare might even help.

**Comment by aaronbrethorst** [comment]
Or, say, S3+CloudFront. I'm not comfortable with hosting critical parts of the OBA infrastructure on GitHub.

**Comment by barbeau** [comment]
@aaronbrethorst Awesome, thanks!  I currently don't know the technical details of why the UW server keeps failing to respond, but I'm trying to get them.  We will be discussing the Regions API server issues further in the OBA annual meeting - see https://groups.google.com/forum/#!topic/onebusaway-developers/pi4fedxTlM4, and there should be another announcement shortly with call-in info.  S3 + CloudFront is probably a good option.

**Comment by barbeau** [comment]
@aaronbrethorst How often does OBA iOS refresh the Regions API info?

Also, I don't have much experience with S3 + CloudFront - do you know the advantages of using CloudFront, vs. just serving a file off S3?

For load reference, we're seeing around 1 request/sec with the current Regions API (including all clients).
