### ISSUE TITLE
Stop UI for Ferries is Hard To Read

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#523]
I'm not entirely sure what should happen, here, but it needs to be more legible no matter what we do.

![img_0776](https://cloud.githubusercontent.com/assets/2254/12535053/a04a993e-c22a-11e5-8422-269aafaed696.PNG)

**Comment by tomtclai** [comment]
Are these routes all non-stop? They only have an origin and a destination?

since the destination is redundant, why don't we display the origin instead of the route name in the small space on the left

**Comment by aaronbrethorst** [comment]
This is more of a reminder for myself with regard to stop UI redesigns than it is a specific task that can be solved on its own.

**Comment by barbeau** [comment]
We have the same issue on Android - https://github.com/OneBusAway/onebusaway-android/issues/409.

There are two issues here which make the ferry data a little more complicated to display than normal transit route data - see the above Android issue and https://github.com/SoundTransit/soundtransit-rds/issues/51#issuecomment-170429678 for details, but here's the summary:

1. No `route_short_names` are provided in the ferry GTFS data - A normal transit route has GTFS data with a `route_short_name` (e.g., `5`).  In OBA we typically display routes as a combination of the `route_short_name` and the headsign, so it looks like `5 - Downtown`.  The ferry data is missing the `route_short_name` in their GTFS data, so we don't have a concise way to refer to the route name.  Apparently WSDOT is looking into this but no promises - https://github.com/SoundTransit/soundtransit-rds/issues/51#issuecomment-170061935.
2. The headsign is truncated - I think there is some pre-processing happening in the process of feeding the ferry data into OBA - the raw GTFS data for the ferry has headsigns that look like `To Seattle`, but in the `arrivalsAndDepartures` element in the API response it shows up as `Seattle`.  This makes it a little more difficult to determine the direction just from the headsign.  See https://github.com/SoundTransit/soundtransit-rds/issues/51#issuecomment-170429678 for details.

**Comment by aaronbrethorst** [comment]
This is now fixed with the new stop UI.
