### ISSUE TITLE
Add 3D Touch App Shortcuts for Map, Recents, and Bookmarks

### ISSUE THREAD

**Issue by jgriffin** [OneBusAway/onebusaway-iphone#524]
As a user, multiple times a day I lauch the app, go into bookmarks, and select a different stop. With 3D touch on iPhone 6 this could be made faster/simpler.

The easiest first part is to add static shortcuts to the existing Map, Recent, and Bookmarks tabs. A more advanced scenario would dynamically surface recent bus stops.

**Comment by aaronbrethorst** [comment]
Totally agree. Any interest in working on it?

**Comment by jgriffin** [comment]
Yes. I implemented the static shortcuts before opening this issue :). After playing with it a bit, adding the dynamic recent stops also feel needed. After I add those, I'll create a pull reqeust.

**Comment by aaronbrethorst** [comment]
:+1:

**Comment by aaronbrethorst** [comment]
fixed!
