### ISSUE TITLE
Stop rendering is inconsistent when zooming in and out

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#565]
### bug report from a user

Aaron,

I found a bug with zooming in and out of the map, specifically as it relates to the feature you describe where more stops are visible when you zoom out. If I am zoomed in on the way, I see all of the stops in my neighborhood. But if I zoom out, several stops disappear. It appears that it is perhaps the desired UI behavior for clarity, otherwise the entire map would just be a sea of stops overlaid on the map. But when I zoom back into the neighborhood and street level, most of my local stops do not return to the UI. I only see the select few stops that were there when I was zoomed out. Does this make sense?

### App Version/Hardware

March 14 TestFlight build.

**Comment by aaronbrethorst** [comment]
@cagryInside - any chance I can get you to take a peek at this?

**Comment by barbeau** [comment]
@cagryInside Could you please give this a quick look, and see if there is a simple solution?

So I know the [stops-for-location REST API endpoint](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/stops-for-location.html), used to grab stops based on geographic bounds, returns 100 markers per call by default (see https://github.com/OneBusAway/onebusaway-application-modules/blob/master/onebusaway-api-webapp/src/main/java/org/onebusaway/api/actions/api/where/StopsForLocationAction.java).  It could be that the larger zoom level is exposing a previously undiscovered bug in the map overlay related to multiple calls to the API as the map is panned/zoomed, and exceeding a certain threshold of markers.  I overhauled the marker overlay for OBA Android as part of the v2.0 UI redesign and dealt with some similar issues.

FWIW - On OBA Android, we now have a fuzzy threshold of 200 markers on the map.  We use a HashMap internally to keep track of what has already been added - this allows us to pan to an area and back without clearing the existing markers (unless we exceed the threshold) (in v1.x, the map was always cleared on each new call to stops-for-location, which resulted in markers appearing/disappearing on each pan of the map).  When the next call to stops-for-location API is made after exceeding the threshold, we wipe the map clean of markers and start over with the response from the API.  At more zoomed out levels, this can result in some non-deterministic-ish behavior where different stops appear on the map, based on the response from the server.  But as long as there aren't more than 200 stops in your geographic view portal, the view of stops should be consistent.

**Comment by cagryInside** [comment]
So, I noticed that the IOS app was checking the region when the zoom level changed. When we zoom out and zoom in it wasn't refreshing the stops since zoomed in region still inside the previous region. 

This was the previous code:

```
BOOL containedRegion = [OBASphericalGeometryLibrary isRegion:region containedBy:self.mostRecentRegion];
     if (!moreAccurateRegion && containedRegion) {
          NSString *label = [self computeLabelForCurrentResults];
          [self applyMapLabelWithText:label];
          return; // Do NOT update stops
      }
``` 

So, I added a zoom level control that updates stops when the zoom level changes:

```
if (!moreAccurateRegion && containedRegion && !zoomLevelChanged) {
          NSString *label = [self computeLabelForCurrentResults];
          [self applyMapLabelWithText:label];
          return;  // Do NOT update stops
}
```

The commit is here: https://github.com/cagryInside/onebusaway-iphone/commit/fd8270dff5d850ba28488b28d80fae6ba4decc24

@aaronbrethorst  and @barbeau if you are ok with this solution, I will open a PR.

**Comment by aaronbrethorst** [comment]
Please go ahead and open a PR and we can discuss further then. PRs are cheap and easy to open.
