### ISSUE TITLE
Layout issues with long destination description

### ISSUE THREAD

**Issue by LIL717** [OneBusAway/onebusaway-iphone#577]
### Expected behavior

List view of scheduled busses should show route number, destination and minutes in portrait orientation

### Actual behavior

List view of scheduled busses is missing either Route or Minutes when Destination has a long description

### Steps to reproduce the behavior

In Settings>Display & Brightness > Text Size move slider to one tick right of center.  In OneBusAway app, navigate to Destination S Sammamish P & R - Bay 1.  Destination "Downtown Seattle Eastgate" forces either Route or Minutes off the screen (rotate to landscape and back to see both occurrences.)

### Screenshot of the issue (if applicable)

![img_8963](https://cloud.githubusercontent.com/assets/5344311/13896669/01b9e4fc-ed52-11e5-8f78-42121238ec2d.PNG)

![img_8961](https://cloud.githubusercontent.com/assets/5344311/13896670/0c20e404-ed52-11e5-83c1-d0a8cb61dbb5.PNG)

### App Version/Hardware

iPhone 6 iOS 9..2.2

**Comment by aaronbrethorst** [comment]
@LIL717 - can you clone this project, and install on your phone and see if the change I just pushed fixes this for you? If yes, great, lmk. If not, boo, lmk and reopen.
