### ISSUE TITLE
Add new production agencies to ITunes store description

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#581]
### Expected behavior

[iTunes Store listing](https://itunes.apple.com/us/app/onebusaway/id329380089) should include all the current production regions for OBA:

* Atlanta, Georgia
* Rogue Valley, Oregon
* San Diego, California
* Seattle/Tacoma/Puget Sound, Washington
* Tampa Bay, Florida
* Washington, D.C.

### Actual behavior

These are the current productions regions listed in the iTunes Store listing:

* Atlanta, GA: Cobb Community Transit (CCT), Georgia Tech Trolley and Stinger Shuttles, Metropolitan Atlanta Rapid Transit Authority
* Seattle, WA: King County Metro, Sound Transit, Pierce Transit, Intercity Transit, Community Transit, and Washington State Ferries 
* Rogue Valley, OR: Rogue Valley Transportation District 
* Tampa, FL: Hillsborough Area Regional Transit (HART)
* York, Canada: York Regional Transit (YRT), Viva

The following are missing:

* San Diego, California
* Washington, D.C.

**Comment by aaronbrethorst** [comment]
Can you give me the exact text you'd like to see in the App Store listing? I'll make sure it's included when I submit OBA 2.5 later this week.

**Comment by barbeau** [comment]
@aaronbrethorst That's a good question - I was just debating changing things as well on Android.

Here's what we currently have on Android:

>**Real-time transit information for the Puget Sound region and beyond.**

>Never miss the bus again!

>OneBusAway serves up fresh, real-time transit information in the following cities:

>* Atlanta, Georgia
* Rogue Valley, Oregon
* San Diego, California
* Seattle/Tacoma/Puget Sound, Washington
* Tampa Bay, Florida
* Washington, D.C.
>* More coming soon!

>Find nearby stops on a map, choose from a list of favorite stops, add shortcuts to your phone's home screen, and set reminders for frequently used trips.

>Problems with arrival times?  Real-time arrival information comes from your local transit agency.  Please tap on the arrival time and select "Report problem with trip" to tell them what went wrong.  Or, reach them via email by tapping "Menu->Help->Contact Us".

>Problems with the app itself (e.g., crashes)?  Please submit a crash report if prompted, or email us via android-app@onebusaway.org.

>Want a sneak-peak at new versions?  Sign up to be a beta tester at https://play.google.com/apps/testing/com.joulespersecond.seattlebusbot.

>Like hacking things?  OneBusAway is open-source!  Find out how you can help at http://onebusaway.org.

What are your thoughts on the above?

The bold first sentence is the "Short description" that shows up before diving into the detailed description (the rest of the text) on Google Play.  I was debating changing this to be less specific to Puget Sound, and something more general.  We could do the same for iOS and remove the cities from the top line.

The major difference between this and current iTunes listing is that we don't explicitly call out which transit agencies are supported, but focus more on the cities/regions.  As more regions are added, and more agencies added to each region, my feeling is that it would be better to get away to managing the list of agencies here.  There is functionality in the app to pull back the supported agencies for a region (in OBA Android, via "Help->Supported agencies").

We could run this by the OBA Board as well if we think it needs further review.

**Comment by aaronbrethorst** [comment]
@barbeau - i think this looks great. thanks for the help; I'll get it added to the iTunes Connect record right now.

**Comment by barbeau** [comment]
Thanks!  One fix:

>OneBusAway serves up fresh, real-time transit information in the following **cities**:

should probably be:

>OneBusAway serves up fresh, real-time transit information in the following **regions**:

**Comment by aaronbrethorst** [comment]
Good catch, will do!
