### ISSUE TITLE
Route trace colors referenced by route_color field

### ISSUE THREAD

**Issue by kencon** [OneBusAway/onebusaway-iphone#589]
Submitting feature enhancement request regarding using route_color hex values (if present) to represent route traces on route map as is already present in the Android beta app.

**Comment by aaronbrethorst** [comment]
@kencon can you include any additional information about the feature as it's used in Android, today? Screenshots, links to .java files, etc?

**Comment by kencon** [comment]
Android reference (RouteMapController.java): onebusaway-android/onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java

Currently in the Android beta app, route overlays are drawn with the route color as referenced in the RouteMapController source file (as shown below).
![screenshot_2016-03-29-18-58-59](https://cloud.githubusercontent.com/assets/5865563/14126784/75c8dd7a-f5e1-11e5-97f3-6c798360f236.png)

This would be a great feature to add into the iOS app. One concern would be colors that are too bright and provide little contrast especially for those with visual difficulties.

**Comment by kencon** [comment]
The vehicle's color is derived by the schedule deviation and the pin itself from the vehicle location. The route trace is derived from the `route_color` field from the input GTFS data. Unfortunately, WMATA doesn't publish the actual GTFS data feed they use in their OBA instance as of yet. Certain details seem to be stripped from their latest GTFS data feed.

**Comment by aaronbrethorst** [comment]
Ahh, I see. Thanks for the clarification. I'll take a peek and see what we can do!

**Comment by kencon** [comment]
Thanks Aaron.

**Comment by barbeau** [comment]
IIRC color comes from route element in [stops-for-route](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/stops-for-route.html) API method for drawing colored line on the map.

**Comment by barbeau** [comment]
The other place we expose GTFS route color in OBA Android is trip details, from [trip-details](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/trip-details.html) API method:

![image](https://cloud.githubusercontent.com/assets/928045/14128723/7648cc00-f5f1-11e5-9604-d1076f406295.png)

The line is colored based on route color, as is the landmark icon (which appears if the user came to the trip details screen from a screen where that stop was selected).

If route color isn't defined in GTFS, the API should return an empty string for route color.

If its useful, here's [the commit](https://github.com/OneBusAway/onebusaway-android/commit/50ad2d5fda96070d3e80020e566cf8e7650887b1) that added GTFS route color support in OBA Android, which includes some unit tests and sample JSON responses.

**Comment by aaronbrethorst** [comment]
👍

**Comment by aaronbrethorst** [comment]
Implemented in OBAKit
