### ISSUE TITLE
Can no longer reorder bookmarks in v2.5.0

### ISSUE THREAD

**Issue by jwhitley** [OneBusAway/onebusaway-iphone#593]
notes from @aaronbrethorst:

In the interest of supporting the adoption of CloudKit, any solution for this problem will need to move away from an explicit order enforced through the array that the bookmark is included in, and towards encoding the sort order in the bookmark itself.

In other words: to fix this, add this to OBABookmarkV2, set it appropriately, and use it to sort bookmarks:

    @property(nonatomic,assign) NSUInteger sortOrder;

Tasks:

- [x] Abstract out the user preferences persistence layer into a protocol
- [ ] Write tests to validate bookmark and bookmark groups behavior
- [ ] Add a UUID to bookmark groups, and replumb bookmarks to be associated with their groups based upon the UUID instead of their inclusion in an array.
- [ ] Add sort order to bookmarks
- [ ] Make bookmarks rearrangeable with the `sortOrder` property mentioned above. 

----

### Steps to reproduce the behavior
1. Navigate to the bookmarks tab in iOS OBA app, v2.5.0. 
2. Tap 'Edit'

### Expected behavior
Reorder/drag handles appear on the right side of each item in the bookmarks list view. 

### Actual behavior
No handles appear, nor is any other affordance for reordering evident. 

### App Version/Hardware
2.5.0, iPhone 6s Plus

**Comment by aaronbrethorst** [comment]
Thanks for the report! We'll get it fixed, or feel free to tackle it yourself if you'd like.

**Comment by jwhitley** [comment]
@aaronbrethorst I'll have a look, but no guarantees on timeliness; I'm stretched a bit thin at the moment.  I see where moving rows has been explicitly disabled in `OBABookmarksViewController`, and will go from there.

**Comment by aaronbrethorst** [comment]
I'll tackle it in due course if you don't get to it. I have a number of tasks related to bookmarks to include in the next feature release. On a related note, I've updated the bug to include information on how this should be fixed.

**Comment by jwhitley** [comment]
❤️ thanks!
