### ISSUE TITLE
Title of stop view has issues with long strings 

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#600]
![image](https://cloud.githubusercontent.com/assets/2254/14272160/36787dfa-fab5-11e5-9c6d-ed01769fc33f.png)

**Comment by seemar** [comment]
Here is the repro for long error strings:
1. Open station 
2. Move away from the page
3. Go offline

Expected: The Internet connection appears to be offline.
Actual: See string one cannot fully see. "The Internet connection appears to..."

issue #2: expected: "internet" not "Internet", separate ticket?
Issue #3: Why isn't the data read? It was a standard usage that caused the error. I will file a separate ticket once I find repro.

**Comment by aaronbrethorst** [comment]
> issue 600.2: expected: "internet" not "Internet", separate ticket?

zing.

**Comment by aaronbrethorst** [comment]
It looks like the error message is coming from `NSJSONSerialization`. The offline behavior is covered by #137. Not much that we can do about that, as that message is being vended by an Apple framework class. That said, the way in which error messages are surfaced and displayed here can definitely be improved.

Specifically, what needs to be fixed to call this issue complete is to provide a better user experience around the display of error messages.
