### ISSUE TITLE
Route disambiguation UI doesn't always appear when it should

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#601]
### Expected behavior

The route disambiguation UI always appears when there are multiple routes whose names contain the same search string.

### Actual behavior

This is not always the case.

### Steps to reproduce the behavior

1. Zoom in reasonably close to street level
2. Search for "105"

Expected:

The disambiguation UI appears and asks if you meant Metro Transit or Community Transit

Actual: 

It only shows one or the other.

It *will* work if you zoom out far enough to show a map span from Marysville to Lacey.

### App Version/Hardware

2.5.0

**Comment by barbeau** [comment]
We had (have) the same issue on Android - https://github.com/OneBusAway/onebusaway-android/issues/42.  Issue stems from the fact that the [stops-for-location](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/stops-for-location.html) and [routes-for location](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/routes-for-location.html) APIs are driven by location, and are the primary means to search for stops and routes.

From that issue:

>Looks like [the server-side routes-for-location API default is 10,000m](https://github.com/OneBusAway/onebusaway-application-modules/blob/master/onebusaway-api-webapp/src/main/java/org/onebusaway/api/actions/api/where/RoutesForLocationAction.java) when a `radius` query parameter isn't provided.

Same for stops-for-location API.

Our fix on Android was to submit the `radius` parameter with the API requests and set it to `40000` meters.  This seems to cover most of the Puget Sound and Tampa Bay areas, which I believe are currently the largest geographic areas that OBA is deployed to.  Even with this radius, if you're on the perimeter of the region it still may not return routes/stops close to the opposite side of the region.

Long term fix is to implement search server-side that doesn't rely on geolocation and radius.

**Comment by aaronbrethorst** [comment]
Thanks Sean!
