### ISSUE TITLE
Remove privacy policy caveat in feedback emails

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#602]
### Expected behavior

The project-wide [OBA privacy policy](https://onebusaway.org/privacy/) should reflect the data sent via the feedback emails, and the feedback email contents should reflect that.

### Actual behavior

When a user submits feedback via email, this is tacked onto the bottom:

>The following information is provided for troubleshooting purposes and does not comply with the privacy policy. If you are uncomfortable sharing any of the following information you may remove it, however it may affect our ability to assist you.
App Version: 2.5.0
Device: iPhone7,2
iOS Version: 9.3.1
Set Region Automatically: NO
Region: Puget Sound
Custom API: 
Current Location: (X,Y)

I updated the [OBA privacy policy](http://onebusaway.org/privacy/) to reflect what data is submitted in these feedback emails (Under "OneBusAway Apps"), so we should remove the "and does not comply with the privacy policy" section of the feedback text.

### Steps to reproduce the behavior

Tap on Help->Send feedback.

**Comment by aaronbrethorst** [comment]
fixed in #604

**Comment by barbeau** [comment]
Thanks!
