### ISSUE TITLE
OBA crashes when iPhone is unlocked while displaying a particular trip's departure time.

### ISSUE THREAD

**Issue by sam-roth** [OneBusAway/onebusaway-iphone#607]
### Expected behavior
The app should not crash when the device is unlocked.

### Actual behavior
The app crashes when unlocking the device while a departure is selected.

### Steps to reproduce the behavior
* Set the device to require passcode immediately after locking. (May not be necessary.)
* Open OBA.
* Tap "Search Puget Sound". 
* Enter "550".
* Tap the hamburger menu button. 
* Select "University St Station - Bay D".
* Select any "550E Bellevue" departure. (A view should be displayed with items reading "Show as Map" and "Show as List".)
* Press the lock button.
* Press the home button.
* Enter passcode or use Touch ID
* Observe that the device will hang for several seconds, then display a black screen. The home screen is displayed instead of the bus departure time. Upon reopening OBA, the app displays the map and not the departure time.

### App Version/Hardware

* Hardware: iPhone 6S (MKQE2LL/A)
* iOS Version: 9.3.1
* OBA Version: 2.5.1 (20160401.18)

**Comment by aaronbrethorst** [comment]
Thanks for the report.
