### ISSUE TITLE
Fail to code sign when trying to run on device

### ISSUE THREAD

**Issue by tomtclai** [OneBusAway/onebusaway-iphone#612]
I’m trying to run the project on my device -- I have an active dev membership; but I'm getting a code sign error that i've been unable to fix.
### Expected behavior

I'm able to install and run the project on my device. 
### Actual behavior

I encountered a code sign error.

![screenshot 2016-04-09 23 08 18](https://cloud.githubusercontent.com/assets/6173427/14408417/3c3df74a-fea9-11e5-8691-48e5ffb3094c.png)
Here, Xcode crashed when I click `Fix Issue`...  

Under Target->OneBusAway->Capabilities->App Groups, `group.org.onebusaway.iphone` is red (again the `Fix Issue` button here crashes Xcode)
![screenshot 2016-04-09 23 15 46](https://cloud.githubusercontent.com/assets/6173427/14408421/59b55c00-fea9-11e5-89d0-4ef3daf96ccc.png)

Is there a way to fix this manually?
### Steps to reproduce the behavior
- Pull from the Onebusaway repo. 
- I changed the bundle identifier to `org.onebusaway.tom` so it won't say `An App ID with Identifier 'org.onebusaway.iphone' is not available`

![screenshot 2016-04-09 23 22 00](https://cloud.githubusercontent.com/assets/6173427/14408445/fafc8c00-fea9-11e5-9a7a-ec5af9fcdeb4.png)
### App Version/Hardware

| OneBusAway | 2.5.2 (20160407.17) |
| --- | --- |
| OS X | 10.11.4 |
| Xcode | 7.3 (7D175) |

**Comment by aaronbrethorst** [comment]
I recommend creating a brand-new Xcode project using one of Apple's templates, and—following the instructions here http://stackoverflow.com/a/30734940—get it to build and run on your phone. After that, use the exact same bundle ID that this other application had with OneBusAway. I don't think you'll be able to get OBA to run with the `org.onebusaway.iphone` bundle identifier, unfortunately.
