### ISSUE TITLE
Placeholder task for incorporating trip planning via Apple's transit offerings into OBA

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#618]
http://www.macrumors.com/2016/04/18/apple-maps-transit-directions-seattle/

There is a bunch of work that needs to be done in order to get trip planning working and integrated sensibly into the app, but trip planning needs to happen.

**Comment by barbeau** [comment]
@aaronbrethorst heads up that York is working on adding trip planning to their fork of OBA iOS now, using Google Directions API.  Not sure on current timeline - I'll check in with them.

**Comment by aaronbrethorst** [comment]
Google Directions API? Interesting. Please let me know what they have to
say!

On Mon, Apr 18, 2016 at 9:09 PM, Sean Barbeau <notifications@github.com>
wrote:

> @aaronbrethorst <https://github.com/aaronbrethorst> heads up that York is
> working on adding trip planning to their fork of OBA iOS now, using Google
> Directions API. Not sure on current timeline - I'll check in with them.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/OneBusAway/onebusaway-iphone/issues/618#issuecomment-211721454>
>



-- 
Aaron Brethorst

talk 425.241.4008
read http://www.brethorsting.com
see http://www.flickr.com/photos/aaronbrethorst

**Comment by barbeau** [comment]
...and HART's current plan is to adapt that to OpenTripPlanner and deploy at least in Tampa - it should support any region that deploys an OTP server (that's the current work going on with OBA Android, issue [here](https://github.com/OneBusAway/onebusaway-android/issues/25)).  OBA iOS is planned after that, dependent on York's timeframe to flesh out the initial implementation.  You should hear from @sheldonabrown when that time grows near.

**Comment by barbeau** [comment]
From a discussion today:

>Google Places autocomplete widget for iOS has unlimited use (i.e., no quota), although it's rate limited to 1k requests in 24 hrs by default, but you can remove this by asking Google nicely - https://developers.google.com/places/ios-api/usage.

>Docs on service - https://developers.google.com/places/ios-api/autocomplete

This is what we're using for geocoding/POI search in OBA Android.  Sound Transit raised the question of consistency of search results between app platforms, which prompted me to look this up.

**Comment by barbeau** [comment]
Just to update this issue - we have live OpenTripPlanner servers being used for OneBusAway Android trip planning in Puget Sound, Atlanta, and Tampa.  Regions with OTP servers are in the Regions API (http://regions.onebusaway.org/regions-v3.json) and have a `otpBaseUrl` field, as well as a `otpContactEmail` field for when things go wrong with trip planning.
