### ISSUE TITLE
Show stop icons at a higher (i.e., more zoomed out) zoom level

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#62]
Originally referenced in #42.

The apps cuts off the view of icons at too low a zoom level.  Right now I'm several blocks from transit service that I wanted to look at, which requires me to zoom out, pan elsewhere, and then zoom back in to get stop icons to appear on the map.  And if I zoom out by a step or so, the icons disappear and again prompt me to "Zoom in to look for stops".  

In contrast, in the Android app I can zoom out to almost the city level and still get icons for all the stops on the map.

We should allow stop icons to be shown at least a few zoom levels higher than the current cutoff that triggers the "Zoom in to look for stops" prompt.

**Comment by aaronbrethorst** [comment]
@yogipatel related to work you've explored in the past.

**Comment by barbeau** [comment]
@aaronbrethorst We'd like to revisit this issue and make it a priority to get out in the next release.  

We're currently working on bringing the other major transit agency in the Tampa Bay area, PSTA, onboard in OneBusAway Tampa.  Not being able to see stops at higher (i.e., more zoomed out) zoom levels in OBA iOS is one of the major issues they want to see resolved before launch.  Soft launch is scheduled for April 1st, hard launch is scheduled for July 1st.

This is an issue for them because their stop density is lower than the City of Tampa in many places.  As a result, you can only see one or two stops on the screen at a time.  And when you zoom out, you can't see any stops.  This results in users having to constantly zoom in, pan, zoom out, pan, etc., and it makes it very difficult to get a larger picture of what the transit coverage/routes are located.

Test server with PSTA data, if you want to check out their system, is at `app.staging.obahart.org` - here's the middle of Pinellas County - https://goo.gl/maps/cYNbnMWUZmr.

Would you be able to prioritize this?

cc @cagryInside

**Comment by aaronbrethorst** [comment]
yep, sure thing. I'm certainly happy to.

**Comment by barbeau** [comment]
Thanks @aaronbrethorst!

**Comment by aaronbrethorst** [comment]
@barbeau i have hopefully fixed this issue to Tampa's satisfaction in the pull request I just opened (#542). Please let me know if they—or you—would like to see stops show up even further up. I'm happy to keep tweaking it as needed.

**Comment by barbeau** [comment]
Awesome!  Thanks @aaronbrethorst, we will take a look.
