### ISSUE TITLE
Long route name causes UI readability issues

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-iphone#622]
Stops with long route names cause UI readability issues.  

Open arrivals for stop 75090 for San Diego MTS

![oba_screenshot_longroutedestination](https://cloud.githubusercontent.com/assets/5028299/14856986/556be318-0c4f-11e6-9386-f0448f86e631.jpg)

iPhone 6
iOS 9.3.1
OBA App v. 2.5.2

**Comment by aaronbrethorst** [comment]
Thank you for the bug report. For the moment, you can work around this by tapping "filter and sort routes" and sorting by route.
