### ISSUE TITLE
Deep linking possible via web URL?

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-iphone#634]
I'm interested to know if it's possible to deep-link from a web URL w/ parameters to a specific screen within a native iOS app.

For example, with OBA the steps would look something like:

1. Tap on a web link in Safari for an OBA stop, like http://pugetsound.onebusaway.org/where/standard/stop.action?id=1_480
1. Somehow the onebusaway.org domain would be registered with OBA iOS, and would trigger a deep link to launch the OBA iOS app
2. The OBA iOS app would parse the parameters and/or URL, and pull up the arrival info screen for Puget Sound stop_id `1_480`

I believe this is possible on iOS using custom schemes like `facebook://` (and IIRC this was done within OBA iOS for StopInfo to have a tie back to native app from browser?), but my question is specific to using web URLs that start with `http://`.  The idea is that you could have a single URL in a web page that could be consumed by either web browser or native iOS app or native Android app, if those are installed on the respectively platforms.  This is possible on Android using URL, but I don't know about iOS.

@aaronbrethorst issue now open as requested :).

**Comment by barbeau** [comment]
Found [this article](http://www.programmableweb.com/news/how-to-implement-deep-linking-ios/how-to/2015/07/14), which seems to suggest this is possible via a few different methods.

**Comment by aaronbrethorst** [comment]
Cool thanks. I'll check it out!

**Comment by RPangrle** [comment]
This sounds a lot like what Universal Links is meant to support: (https://developer.apple.com/library/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html)

**Comment by aaronbrethorst** [comment]
@RPangrle thanks for the link 👍

**Comment by barbeau** [comment]
Excellent, thanks @RPangrle!  Sounds like this is now available on iOS 9, which, from some Googling, looks like around 87% of devices. I'll close this out then.

**Comment by RPangrle** [comment]
Well there still is work to implement this client side as Universal Links use  the UIApplicationDelegate handoff method (```- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler```). I don't know if trhat's covered in another issue or not.

**Comment by aaronbrethorst** [comment]
It's not at present, no. This was the only task associated. I don't know offhand if this needs to be implemented or if this was more of a request for information for the time being. Sean can clarify.

**Comment by barbeau** [comment]
This was basically an RFI - @aaronbrethorst asked me to ticket it here as a reminder.  So I'm fine with this issue being closed, and @RPangrle or @aaronbrethorst feel free to open a new issue if you want to implement something specific in OBA iOS.  AFAIK we don't currently have any issues on OBA Android or iOS re: deep linking, but whatever we decide on we should be consistent so the same URLs open on both iOS and Android.
