### ISSUE TITLE
Apply title casing to trip headsigns based on heuristics

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#635]
### Expected behavior

Our trip headsigns should not include either SCREAMING CAPS or incorrectly downcased acronyms. We should apply a heuristic to determine whether or not trip headsigns are properly capitalized.

### Actual behavior

Issue report from San Diego:

> Hello OBA experts,
> Is it possible to turn off the auto capitalization features in OBA?
> We have lots of stops and head signs which use acronyms such as "SDSU" and "Downtown SD" which get changed to "Sdsu" and "Downtown Sd" respectively. 
> Thanks for any help!
> Devin

**Comment by barbeau** [comment]
FYI - Android implementation at https://github.com/OneBusAway/onebusaway-android/pull/576.

If text is all caps (e.g., "THIS IS A HEADSIGN"), then convert to title case (e.g., "This Is A Headsign"), otherwise don't change it.

**Comment by barbeau** [comment]
Sorry, previous post should have read "title case" - I just corrected it.
