### ISSUE TITLE
setup developer chat room

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#66]
would like to find a free chatroom for us to use like campfirenow.

**Comment by barbeau** [comment]
Last year apparently Google started supporting permanent URLs for Hangouts, so I grabbed a permanent URL (well, currently expires 2020) for OneBusAway-related Hangouts:
https://plus.google.com/hangouts/_/event/ce7dbh4vagk8b9si2nf64t8v544

I also set up Bitly link that will take you to the same Hangout:
http://bit.ly/OBAHangout

We'll use this for screen sharing for the upcoming OBA Annual Meeting - an email will go out about this shortly on the oba-developers list.

**Comment by bbodenmiller** [comment]
I submitted a PR with links to the IRC channels. That being said IRC isn't able to integrate with the GitHub development process nearly as well as [HipChat](http://hipchat.com) and [Gitter](https://gitter.im), both now free.

**Comment by barbeau** [comment]
Has anyone here tried [Gitter](https://gitter.im)?  I was looking at this today - looks promising, with tight integration with Github.

**Comment by bbodenmiller** [comment]
I've only tried it enough to post in my last comment that it looks promising. Since I subscribed to a few projects to test it, I get daily summary emails (I imagine configurable) that look handy. Like you mentioned it has tight GitHub integration. In addition to the web app they also have OS X, Windows, iPhone, & Android apps with Linux on the way. I vote we give it a try for the iPhone & Android repos atleast through the end of the Seattle Hack the Commute Hackathon.

**Comment by barbeau** [comment]
From a quick look I think admins need to add users to the [OBA Gitter](https://gitter.im/OneBusAway?utm_source=share-link&utm_medium=link&utm_campaign=share-link)?  I can't seem to find a way to request to join from a non-admin account.

So, if you'd like to be added to test it out let me know and I'll add you (cc @cagryInside).

**Comment by barbeau** [comment]
Also looks like you can do per-repo chatrooms - just fired one up for [onebusaway-android](https://gitter.im/OneBusAway/onebusaway-android?utm_source=share-link&utm_medium=link&utm_campaign=share-link), to see how it works.

**Comment by aaronbrethorst** [comment]
I just created http://onebusaway.slack.com. I have invited everyone for whom I have email addresses, and I'm following up with Slack on best practices for managing a Slack channel for OSS projects.

**Comment by barbeau** [comment]
Cool!
