### ISSUE TITLE
Bus Departing ~1,440 minutes early

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#661]
### Expected behavior

Buses should not ever report themselves as being a day early.

### Actual behavior

Sometimes you'll see a bus reporting itself as departing approximately 1,440 minutes early, which happens to be roughly the number of minutes in one day (24 * 60).

### Steps to reproduce the behavior

Unclear, but I have finally managed to grab JSON from the server for a circumstance when this happened, so that I can at least nail down whether it's a client or server issue.

This happened at 9:12AM Pacific Time on August 24, 2016. JSON data is attached.

[Archive.zip](https://github.com/OneBusAway/onebusaway-iphone/files/435150/Archive.zip)

**Comment by barbeau** [comment]
Interesting, users have reported this a few times on Android as well.  I've
chalked it up to device clock issues in the past as I've never seen it
myself, but seems like it might be a server issue if we're seeing it on
both platforms?

**Comment by aaronbrethorst** [comment]
Which regions have you seen reports of this occurring in? Only Puget Sound?

**Comment by barbeau** [comment]
I think so - only Puget Sound.  It might be a GTFS scheduled arrival time issue.  I'll see if I can dig into the JSON.

**Comment by barbeau** [comment]
Alright, after looking at `1_11190.json` in the zip file that @aaronbrethorst attached to this issue in the initial post (captured at `1472055140749` - Wednesday August 24, 2016 09:12:21 am - PDT), it looks like it's a real-time prediction error in Puget Sound - the scheduled times in the response look correct.

Here's a snippet of JSON:

~~~
"arrivalsAndDepartures":[  
            {  
               "arrivalEnabled":true,
               "blockTripSequence":4,
               "departureEnabled":true,
               "distanceFromStop":1072.7762336411688,
               "frequency":null,
               "lastUpdateTime":1472054957000,
               "numberOfStopsAway":2,
               "predicted":true,
               "predictedArrivalInterval":null,
               "predictedArrivalTime":1471968867000, // Tuesday August 23, 2016 09:14:27 (am - PDT) (Incorrect)
               "predictedDepartureInterval":null,
               "predictedDepartureTime":1471968867000, // Tuesday August 23, 2016 09:14:27 (am - PDT) (Incorrect)
               "routeId":"1_100447",
               "routeLongName":"",
               "routeShortName":"49",
               "scheduledArrivalInterval":null,
               "scheduledArrivalTime":1472055211000,  // Wednesday August 24, 2016 09:13:31 (am - PDT) (Correct)
               "scheduledDepartureInterval":null,
               "scheduledDepartureTime":1472055211000,  // Wednesday August 24, 2016 09:13:31 (am - PDT) (Correct)
               "serviceDate":1472022000000,
               "situationIds":[  ],
               "status":"default",
               "stopId":"1_11190",
               "stopSequence":6,
               "totalStopsInTrip":20,
               "tripHeadsign":"University District Broadway",
               "tripId":"1_30937119",
~~~

timestamp to human-readable time conversions done with http://www.epochconverter.com/, using "America/Los Angeles" (PDT) time zone.

@sheldonabrown Could you please take a look at this in the Puget Sound source real-time feeds?

Link to the offending stop:
http://api.pugetsound.onebusaway.org/api/where/arrivals-and-departures-for-stop/1_11190.json?key=TEST

**Comment by sheldonabrown** [comment]
Certainly -- this has been seen across all interfaces, so I'm happy to have
an example

**Comment by aaronbrethorst** [comment]
@sheldonabrown is there an issue that can or should be opened up against the server project? Is there any other action that I can take at this time?

**Comment by sheldonabrown** [comment]
@aaronbrethorst we are already tracking this issue in a non-public bug tracking system.  You are certainly welcome to open a bug up on the public wiki as well.

So far we've found KCM is providing an invalid timestamp in the trip updates which may be causing OBA to infer the wrong stop time update to apply the delay to.  We should have a code fix shortly but the deploy to production may take a while.  I will concurrently work with KCM to see if they can fix the timestamp issue.

**Comment by aaronbrethorst** [comment]
@sheldonabrown I'll go ahead and close this for now. Thanks for the info and I'm happy to hear it's being tracked :)

**Comment by barbeau** [comment]
@sheldonabrown Has the fix for this been deployed in Puget Sound?

**Comment by sheldonabrown** [comment]
Not yet. It's in QA now though so soon.
