### ISSUE TITLE
"zoom in to look for stops" incorrectly displayed on app startup

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#69]
I live in an area with no stops in the default zoom radius so when I open the app I incorrectly get the message "zoom in to look for stops" when it should either say something like no stops here or have no message at all.

/cc @ksslng

**Comment by aaronbrethorst** [comment]
Core issue is fixed. Secondary issue remains, and will hopefully be fixed in 2.5.
