### ISSUE TITLE
Dead Code Removal

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#694]
- [ ] OBAArrivalEntryTableViewCellFactory

**Comment by aaronbrethorst** [comment]
Trying to figure out why I can't assign @chadsy to this per his request.

**Comment by barbeau** [comment]
Apparently on Github you can only assign users to issues if they are part
of a team assigned to the repo.  Read-only teams work - I just actually
tested this last week.

Aaron - Feel free to set up read only teams on oba-ios if that helps.

**Comment by aaronbrethorst** [comment]
@barbeau hmm, i'm not sure i have sufficient permissions on this repo to do that.

**Comment by barbeau** [comment]
Ok - just set it up for @chadsy.

@chadsy If you accept the invitation, then I believe @aaronbrethorst can assign issues to you.  If you have problems finding the invitation, try vising https://github.com/OneBusAway/, and I believe you should see a link with a pending invitation.

**Comment by chadsy** [comment]
Thank you @barbeau & @aaronbrethorst...
