### ISSUE TITLE
Bookmarks should be validated as having non-zero length titles before being created

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#711]
### Expected behavior

A bookmark without a name cannot be created.

### Actual behavior

It can be created, which causes other problems later on.

### Steps to reproduce the behavior

Create a bookmark, leave the name blank.

### App Version/Hardware

2.6.0

**Comment by chadsy** [comment]
Same thing applies to Group names.

**Comment by aaronbrethorst** [comment]
thanks, @chadsy - logged that as #717
