### ISSUE TITLE
Attempting to view vehicle info on a scheduled route shows "Error connecting"

### ISSUE THREAD

**Issue by chadsy** [OneBusAway/onebusaway-iphone#735]
### Expected behavior
Either no ability to look at Vehicle info if it's not available, or a clearer message that vehicle info isn't available with scheduled rather than actual data.

### Actual behavior
Vehicle Info screen appears, showing a title of either "Error connecting" or "Unknown error" and "Updating..." in the view.

### Steps to reproduce the behavior
1. Open a stop with several route arrivals
1. Choose an arrival showing "scheduled arrival" instead of an actual live time
1. Tap Vehicle Info at the bottom of the route list screen
1. Notice the Vehicle Info screen...

### Screenshot of the issue (if applicable)
![image](https://cloud.githubusercontent.com/assets/421655/18609114/efcfc5f8-7cae-11e6-8eff-cc7faf0fa24d.png)

**Comment by chadsy** [comment]
I recall seeing it for quite a while, so if there are no substantive complaints it can totally wait.

**Comment by aaronbrethorst** [comment]
cool, 2.6.1 it is
