### ISSUE TITLE
OBA API URLs in the Regions API are inconsistent, need special casing

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#755]
### Expected behavior

For any region: you can append `/api/whatever-endpoint.json` to the end of the value contained in `obaBaseUrl` in the regions API and everything just works.

### Actual behavior

Some regions' `obaBaseUrl`s are already suffixed with `/api` and some are not.

### App Version/Hardware

OBA 2.6.0/regions-v3.json

### Discussion

The ideal fix would be to normalize the URLs in the regions API. However, for now, I think it will suffice to work around this by searching composed URLs for the substring `api/api` and collapsing this into `api`.

**Comment by barbeau** [comment]
You should be able to just append `api/where/...` to all the `obaBaseUrls` in the Regjons API and that should work.  Some of the regions have an extra `/api` in the full path, and those are the regions that have the `/api` in the Regions API (long story, attributed to me for one, setting up servers when I'm normally the mobile app guy).  I think Tampa is the only instance where both work.

**Comment by aaronbrethorst** [comment]
@barbeau that's fascinating. I see that does stop working if the URL has two slashes in that part of the path, though. e.g. http://api.tampa.onebusaway.org/api//api/where/current-time.json

Thanks for the head's up. This does greatly simplify my fix.

**Comment by barbeau** [comment]
Good point on the double slashes, although I think all the base URLs in Regions API should be normalized with trailing slash.  If not let me know.
