### ISSUE TITLE
Automatic Selection Region Option Switching Problem

### ISSUE THREAD

**Issue by kencon** [OneBusAway/onebusaway-iphone#764]
### Expected behavior
When switching Automatically Select region option off, should be able to select a region from active/beta regions list.

### Actual behavior
After selecting a new region, the Automatically Select Region option switches itself back on and goes to the nearest active region. Even after manually selecting a region and choosing to go to that region, the nearest active region still gets loaded and the option turns on.

### Steps to reproduce the behavior
1. Go to **Info > Region**.
2. Turn off **Automatically Select Region**.
3. Select an active region outside current area.
4. Go to map and select Yes to go to current selected region.
5. Try searching for a route or stop but will not be found. App automatically takes you back to nearest region and Automatically Select Region option gets enabled again.

### App Version/Hardware
App Version: 2.6.0
Hardware: iPhone 6S
OS: iOS 10.0.2

**Comment by aaronbrethorst** [comment]
@kencon thank you for the report! We'll follow up on this as part of the next release.
