### ISSUE TITLE
Map doesn't consistently show stops when it first loads

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#773]
### Expected behavior

The map shows stops within its bounds when it appears

### Actual behavior

This doesn't happen, but it only occurs inconsistently.

### Steps to reproduce the behavior

Launch app on Map tab

### App Version/Hardware

2.6.0/2.6.1

**Comment by heckj** [comment]
FYI - default view of several stops for me has exhibited this issue. Sometimes pinch-zooming "way out" and back in can trigger the view to appear, but without any interaction they don't appear to show up for me.

**Comment by aaronbrethorst** [comment]
Probably a race condition? The region is updated shortly after launch and this causes all active connections in the JSON data source object to be canceled. My guess is that, when this works properly, that either the region is updated fast enough that the map annotations request hasn't started yet and won't be canceled later, or that the map annotations request finishes before the regions request. Still investigating how to fix this problem.
