### ISSUE TITLE
dev environment setup instructions not quite working

### ISSUE THREAD

**Issue by heckj** [OneBusAway/onebusaway-iphone#774]
### Expected behavior

I could download all relevant files and open Xcode with this project to compile it and poke at it's soft underbelly

### Actual behavior

from-scratch the instructions didn't complete as expected `pod install` in particular just failed

### Steps to reproduce the behavior

- clean machine, installed xCode 8
- didn't have cocoapods installed previous
- made fork on github
- cloned from fork
- cd into enlistment
- ran `gem install cocoapods --pre`
- tried running `pod install`, which resulted in:
```
Could not find proper version of cocoapods (1.1.0.rc.1) in any of the sources
Run `bundle install` to install missing gems.
```
- ran `bundle install` - that installed some things, ending with `Your bundle is complete!`
- ran `pod install` again, which resulted in:
```
[!] No `Podfile' found in the project directory.
```

- `git status` shows that `Gemfile.lock` is modified

### terrible admission

believe it or not, i've never used cocoapods before, but since this project was using them, I thought I'd try this process out, but I don't really know the ruby setup process or much about hacking through it, so suggestions _very welcome_

- `ruby -v`
```
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
```

**Comment by aaronbrethorst** [comment]
doh, sorry, yeah. I gotta clean that up. Cocoapods has been eliminated in favor of Carthage. You shouldn't have to do anything other than open the xcodeproj file and run the app now.

**Comment by heckj** [comment]
^^ erp, not quite true - need to install carthage. I'm fiddling with that now - I'll put up a PR with the instruction changes for you

**Comment by aaronbrethorst** [comment]
OH RIGHT. Because of that `copy-frameworks` task. Argh. Sorry about that and thank you very much!

**Comment by aaronbrethorst** [comment]
(Also, since you volunteered, I'm assigning this to you 😄 — thank you very much!)

(And please fill out the ICLA when you have a moment, too. Much obliged 😄 https://docs.google.com/forms/d/12jV-ByyN186MuPotMvxJtNKtSaGGTnEHm8rXomM2bm4/viewform)

**Comment by heckj** [comment]
yep, iCLA signed right after I kicked up the PR - I actually read the contributor guidelines - thought there might be something like that lurking about. :-)
