### ISSUE TITLE
Launch screen UI regression

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#807]
Make it look the way it did before

**Comment by chadsy** [comment]
What's the issue? How long ago was "before"?

**Comment by aaronbrethorst** [comment]
Two days ago. It says "org.onebusaway.iphone" instead of showing a tab bar.

**Comment by chadsy** [comment]
Oh, you mean, now it's showing `Launch Screen.storyboard` instead of going directly into the last view?

**Comment by aaronbrethorst** [comment]
It's shown a launch screen for the last few years. The launch screen just happened to look identical to the app UI. Rearranging all of the files on disk the other had the unfortunate side effect of messing up Xcode's hardcoded paths to a few files, the launch screen included.

**Comment by aaronbrethorst** [comment]
(after the app launches and the launch screen is torn down, the app then shows the last view)
