### ISSUE TITLE
Map annotations need a couple more pixels of black under the word "Stop"

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#808]
### Expected behavior

Consistent padding on all four sides

### Actual behavior

Bottom looks a little truncated 

### Steps to reproduce the behavior

Go to the map

### Screenshot of the issue (if applicable)

![img_1273](https://cloud.githubusercontent.com/assets/2254/19430474/363823e8-9409-11e6-9024-be51f2f5b634.PNG)

### App Version/Hardware

2.6.2, latest beta

**Comment by chadsy** [comment]
Ah, yeah, needs some adjustment after the last-minute typeface change from Helv to System.

**Comment by chadsy** [comment]
If I double the icon size, it looks basically correct:
![image](https://cloud.githubusercontent.com/assets/421655/19448191/a1cf5f76-9455-11e6-9964-041a33ccae07.png)

So there's a rounding problem somewhere.
