### ISSUE TITLE
Arrivals and Departures for Stop API call is URL Encoded twice

### ISSUE THREAD

**Issue by sheldonabrown** [OneBusAway/onebusaway-iphone#817]
### Expected behavior

When user gets arrivals at a stop, we are expecting the query server side:
/api/where/arrivals-and-departures-for-stop/Hillsborough%20Area%20Regional%20Transit_6968.json?key=org.onebusaway.iphone&app_uid=663DDC7F-36E2-4EA6-B6B6-25241AF5E49A&app_ver=20161017.13.2&version=2&minutesAfter=35&minutesBefore=5
### Actual behavior
/api/where/arrivals-and-departures-for-stop/Hillsborough%2520Area%2520Regional%2520Transit_6968.json?key=org.onebusaway.iphone&app_uid=663DDC7F-36E2-4EA6-B6B6-25241AF5E49A&app_ver=20161017.13.2&version=2&minutesAfter=35&minutesBefore=5
### Steps to reproduce the behavior

Search for Stop 6968 for the Tampa Region.

### Screenshot of the issue (if applicable)

You get an error.

### App Version/Hardware

2.6.2

### Notes:
I've added some apache to undo the problem server side for now -- but obviously that is not a long term solution.  I can set you up with a staging server to reproduce the issue.  Just let me know.

**Comment by aaronbrethorst** [comment]
Thanks for the quick fix. I'll get this included in the next update.
