### ISSUE TITLE
Display the user's heading on the map

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#834]
### Expected behavior

I should always be able to see my heading on the map
### Actual behavior

I can only see it if I tap twice on the button in the top left corner of the map 
### Screenshot

Here's what Google Maps looks like. We should basically do this.

![img_1336](https://cloud.githubusercontent.com/assets/2254/19790167/e8cc3fda-9c6a-11e6-869c-fb1054bf50cc.PNG)

Here's my (lame) mockup of it:

![design](https://cloud.githubusercontent.com/assets/2254/19790329/4678d3f4-9c6c-11e6-9eb2-0688aac69059.jpg)

**Comment by aaronbrethorst** [comment]
In the process of fixing #485, I added a third party component that resembles the user location annotation view. I modified this component to improve its support for displaying heading or orientation indicators, and even added a graphic to the app's xcassets catalog that looks like what Apple uses on their built-in component.

**Comment by sethfri** [comment]
Nice! Is this done then?

**Comment by aaronbrethorst** [comment]
@sethfri no, still needs doing. The second screenshot was just a mockup (which is now out of date).

**Comment by sethfri** [comment]
@aaronbrethorst oh ok I think I misunderstood when you said "I modified this component to improve its support for displaying heading or orientation indicators". So we have this component currently in the app, but it's not in use?

**Comment by aaronbrethorst** [comment]
@sethfri Right. I added `SVPulseAnnotationView` to display buses with their headings in the ArrivalAndDeparture controller, and I'd love to be able to use it to display the user's location with their heading on OBASearchResultsMapViewController, too.
