### ISSUE TITLE
I18N/L10N Audit

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#836]
### Expected behavior

All strings in the app should appear in the expected language.
### Actual behavior

I see a couple places, like on the launch screen, where English strings peek through instead.
### Resolution
- [x] Audit every piece of app UI and assemble a list of things that need to be localizable
- [x] Assemble a list of things that are localizable and need to be updated
- [x] Make follow-up tasks

**Comment by themonki** [comment]
It may be good to enable some options for verifying translations, like:

https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html#//apple_ref/doc/uid/10000171i-CH7-SW4
