### ISSUE TITLE
Investigate drop-off in analytics numbers 

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#849]
There's a recent sharp drop-off in iOS usage on Google Analytics. I'm guessing this must be the result of a misconfiguration somewhere in the iOS codebase.

**Comment by bbodenmiller** [comment]
Last version I'm seeing data on in Google Analytics is 2.5.2.

**Comment by aaronbrethorst** [comment]
good catch, @bbodenmiller. thanks for the info :)

**Comment by aaronbrethorst** [comment]
Not fixed.
