### ISSUE TITLE
Show the user what timeframe they're looking at after tapping "Load More"

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#850]
### Expected behavior

I know what timeframe I'm looking at on the stop view after tapping "Load More"

### Actual behavior

It's not possible to tell. This isn't a big deal during the day, but when you're looking at a route late at night, it can seem like tapping the button doesn't do anything. 

### Design

We will extend the existing `* scheduled` row. The `* scheduled` text will only be displayed if non-real time data is visible. The first line, with the rendered times, will always be visible.

![mockup](https://user-images.githubusercontent.com/2254/32480386-708751bc-c343-11e7-8bcf-02d9df725fa4.png)

### Tasks to complete this issue

- [x] Create design 
- [x] Design signoff
- [ ] Implementation

**Comment by barbeau** [comment]
FWIW, on Android if there aren't any upcoming arrivals in the time period we show that timeframe as an entry in the list:

![image](https://cloud.githubusercontent.com/assets/928045/19932394/6c53db22-a0e6-11e6-87c5-a13a3340198b.png)

Every tap of "Load more arrivals" increments by 1 hr.

When an arrival is shown, and tapping "Load more" doesn't yield any additional arrivals, we pop up a Toast saying "No additional arrivals in the next X hr/min":

![image](https://cloud.githubusercontent.com/assets/928045/19932475/ab5bc136-a0e6-11e6-83c2-cbd9f6e2964d.png)

This seems to work relatively well - at least no users have complained about it yet, and this went live prior to the v2 UI redesign a year or two ago.
