### ISSUE TITLE
Improve explanation of negative minutes

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#864]
- [ ] Design
- [ ] Implementation
-----

![img_1371](https://cloud.githubusercontent.com/assets/2254/20170829/c2d3a386-a6e2-11e6-943e-c05fa1e68cf2.PNG)

**Comment by aaronbrethorst** [comment]
![img_1371](https://cloud.githubusercontent.com/assets/2254/20170805/9ff2a9ca-a6e2-11e6-8d14-9529ef8fd10e.PNG)

**Comment by barbeau** [comment]
FYI - On OBA Android I got enough feedback on negative arrivals, including users that didn't want them displayed, that I implemented a setting to allow users to hide them (default is original behavior of them being displayed).  We're working on a similar setting for OBA Alexa now too.  Something you might want to consider.

**Comment by bbodenmiller** [comment]
Personally I think negarive times should be off by default. In most cases seeing the negative time just drives resentment towards the app and agency without providing any value. Only in rare cases of bad data does seeing the negative time help you know to hurry up.

**Comment by aaronbrethorst** [comment]
thanks for the input, guys. I'm just going to turn it off for now.
