### ISSUE TITLE
Make it easier to choose a custom range of bus departure times

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#880]
User feedback:

> Please allow access to previous departures for more than 3 minutes!! There is a very narrow window to report a late/no show bus and no sense of whether a particular bus is e.g. an early 9:15 arrival or an extremely late 8:55 arrival.

My response:

> Viewing late/no-shows goes back 5 minutes, but if you tap on "Report a Problem" you'll see buses that go back 30 minutes. 

> I agree that the latter problem is definitely an issue. I'm not sure how to best address it, though, without creating a significant amount of cognitive overhead for people whose buses are running on time, though, unfortunately. I've been thinking about supplementing "Load More" with a double-sided slider that would let you choose a wider range of default times.

- [ ] Design
- [ ] Implementation

**Comment by barbeau** [comment]
Interestingly, I'm getting the same request from users on OBA Android for the first time:
https://github.com/OneBusAway/onebusaway-android/issues/728

I'm guessing there is a new systematic data issue for a route in Puget Sound.
