### ISSUE TITLE
Add a stop-gap service alert solution to OBA for Puget Sound

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#881]
The Puget Sound OBA deployment currently does not include service alerts. Sound Transit does have an RSS feed that includes a more 'free-form' list of service alerts. Until ST is able to pipe this data into OBA, it would be nice to have a way to give riders a heads up about possible issues, even if we can't directly map those alerts to specific stops or routes.

Giving users the ability to learn whether their route has been canceled, redirected because of snow, or is on reduced service because of a Sounders parade is an extremely valuable service to offer. 

The XML document is almost 2MB in size, and we can't have people downloading that tens of thousands of times a day. To that end, the file will have to be downloaded by OBA.co at regular intervals, parsed there, and stored for (partial) re-transmission to OBA clients. Maybe as a JSON file on the other side, because I'd much rather write JSON parsing code on iOS than XML parsing code.

- [x] OBA.co RSS feed reader/model/persistence (http://www.soundtransit.org/schedules/alerts.xml)
- [x] OBA.co API for global service alerts corresponding to a region. (right now only region `1` will have them)
- [ ] Downloader, modeling, and persistence for global service alerts. (I'd love to reuse the existing service alert model.)
- [ ] Design for global alert UI
- [ ] Implement global alert UI

**Comment by bbodenmiller** [comment]
This would be awesome. I also still think some level of crowdsourcing this data would be beneficial as well because the alerts are only as good as the input data.

**Comment by barbeau** [comment]
+1 for JSON instead of XML

**Comment by sethfri** [comment]
What's the expected UX for these alerts? As written above, it seems like the proposal is for an alert to pop up on app start (if ST has posted an alert). That could be a bit spammy for users who are just trying to catch a KC Metro bus.

What do we think of just showing an alert if a user navigates to a stop containing an ST route? If we like that, I'm happy to take this on. Does the app/backend currently have any notion of which agencies belong to a certain stop, or will that need to be built in as well?

**Comment by aaronbrethorst** [comment]
> What's the expected UX for these alerts?

TBD

> it seems like the proposal is for an alert to pop up on app start (if ST has posted an alert). That could be a bit spammy for users who are just trying to catch a KC Metro bus.

I'll have to clarify the above, then, as I have no intention to spam users or pop up modals.

> if a user navigates to a stop containing an ST route

The rationale behind the stop-gap was that unfortunately there's no way to specifically associate a given route with a chunk of text from this RSS feed. And ST operates the OBA servers for ST, KC Metro, CommTrans, and a bunch of other providers, so it's not specific to ST routes.

**Comment by aaronbrethorst** [comment]
tbh, at this point the original issue is mostly a 'note to self.' I need to flesh out a number of things before this can be tackled. Assigning to myself to follow up.

**Comment by aaronbrethorst** [comment]
Also: https://public.govdelivery.com/topics/WAKCDOT_255/feed.rss
