### ISSUE TITLE
Show bus and user location on the arrivals/departures controller

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#892]
A 'timeline' style bar should run down the left side of the table, and there should be a bus icon at the stop where the bus is currently located. There also needs to be some indication of where the user is. Maybe just a slightly shaded-in cell? I dunno yet.

**Comment by barbeau** [comment]
Here's what we ended up with on Android for trip status - bus icon is bus, landmark icon is bus stop user asked for information about.

![image](https://cloud.githubusercontent.com/assets/928045/21227563/939ff510-c2a8-11e6-9188-25f45f5c62e5.png)

**Comment by aaronbrethorst** [comment]
@barbeau what do you do when the bus is at the landmark?

**Comment by themonki** [comment]
![image](https://cloud.githubusercontent.com/assets/1817333/21233292/a71dfea2-c2bc-11e6-8a64-b8975fe0636d.png)

**Comment by barbeau** [comment]
Yup, a thing of beauty ;).  We obviously don't have all the kinks worked out.  It's been on my TODO list to polish the bus icon more and figure out a way to gracefully handle the overlap.  

This screen will also be the focus point for the future feature (hopefully soon) "get off the bus now" alert, and we have another icon that is a destination flag to mark that stop (with the assumption being you're on the bus, so the bus icon represents your position).

**Comment by aaronbrethorst** [comment]
ah cool, thank you for the information. This is most helpful! :)

**Comment by themonki** [comment]
Here is like Google show:

![image](https://cloud.githubusercontent.com/assets/1817333/21233771/6b12b31a-c2be-11e6-9847-77b1f39ad786.png)

The circle represent the bus and the "current stop" is bold font

**Comment by aaronbrethorst** [comment]
Here's what I ended up with, in case you guys are curious:

![simulator screen shot dec 18 2016 1 05 16 pm](https://cloud.githubusercontent.com/assets/2254/21296514/a8fa6a04-c522-11e6-9b5d-86249eb2dc1b.png)

**Comment by barbeau** [comment]
Looks good - better use of screen real-estate than what we currently have on Android.
