### ISSUE TITLE
Zoom map without animation on launch

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#912]
It used to be that when the app launched the map would zoom in to street level on the user's current location without animation. Seems I broke this at some point. Would be nice to fix.

**Comment by barbeau** [comment]
FYI, I changed this behavior (default snap to location) on Android at one
point and got a lot of feedback about it, and switched it back.  Users were
definitely attached to it.

**Comment by aaronbrethorst** [comment]
Cool, thanks for the datum.
