### ISSUE TITLE
The map toggle position on arrivals and departures should be sticky

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#913]
Persist open and shut in preferences

**Comment by sethfri** [comment]
To make sure I know what screen we're talking about, is it when you open a Stop view and then tap on one of the arriving buses that you get to the arr/dep screen? And is the intention here if I open the map toggle in arr/dep, it should stay open on any subsequent arr/dep visits for any bus until I toggle it closed again?

**Comment by aaronbrethorst** [comment]
Exactly. The state of the button highlighted in magenta in the screenshot below should be stored in user defaults. If the button state 

Key: `OBAArrivalAndDepartureMapExpandedKey`
Default, registered value: NO (or should this be YES?)

If the value of that default is YES, the map is opened to its expanded size. If the value is NO, it is opened in its collapsed size. Tapping the button toggles the value persisted in user defaults.

![foo](https://cloud.githubusercontent.com/assets/2254/21692683/da7e1922-d332-11e6-84e0-18456a0bca49.jpg)

**Comment by victorray84** [comment]
@aaronbrethorst I want to work in this issue. Do you also need any toggle button in Settings to check map is expanded or collapsed?

**Comment by aaronbrethorst** [comment]
I was imagining this to be a stop gap measure while awaiting someone to work on #976. As that issue is being worked on, this should—for now—be left alone.

**Comment by ualch9** [comment]
FYI, I'm planning to remove this button and the size of the `MapController` will persist only if the header collapses/expands 100% (not in between). #976
