### ISSUE TITLE
User's selected stop on Arrivals and Departures should be shown in different color

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#914]
It should be ringed in blue or something.

**Comment by sethfri** [comment]
Can you elaborate on this? There's already the blue pedestrian icon next to the stop. Were you envisioning the whole cell ringed in blue?

**Comment by aaronbrethorst** [comment]
I'll finish up the design and then toss this back into the pool.

**Comment by victorray84** [comment]
@aaronbrethorst can you assign this issue to me??

**Comment by aaronbrethorst** [comment]
@victorray84 I need to finish the design first, and then I'd be delighted to have you work on it.
