### ISSUE TITLE
UIActivityVC needs sourcerect and sourceView on iPads

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-iphone#919]
I've traced this specific issue to line 583 in `OBAStopViewController.m`. A `controller.popoverPresentationController.sourceView` and `sourceRect` is needed.

### Expected behavior
UIActivityViewController should have a `sourceRect` & `sourceView ` set on iPads
### Actual behavior
Exception occurred, app crashes
### Steps to reproduce the behavior
see screenshot
### Screenshot of the issue (if applicable)
![simulator screen shot dec 30 2016 10 31 11 pm](https://cloud.githubusercontent.com/assets/22162410/21576342/e85cbadc-cedf-11e6-9582-82a5ce6d0674.png)
### App Version/Hardware
commit `53fbb53` - develop

**Comment by ualch9** [comment]
I've tried implementing a solution [here](https://github.com/ualch9/onebusaway-iphone/commit/2af4112c23c5caec62c93760eabfce1a85bcfa78) but it doesn't fully work.

**Comment by aaronbrethorst** [comment]
@ualch9 thanks for the bug report and the approach you suggested. I've followed a similar tack and have a PR here that resolves this issue: #920

I'd love it if you could take a peek at it.

**Comment by ualch9** [comment]
Thanks for overlooking my (probably) terrible ObjC.

**Comment by aaronbrethorst** [comment]
> Thanks for overlooking my (probably) terrible ObjC.

Don't say that! Given that you aren't familiar with the OBA codebase, I think you did a fine job. I hope you'd be willing to keep spending some time helping out in the future. Please feel free to join the Slack channel, too: http://onebusaway.herokuapp.com
