### ISSUE TITLE
Strange glitch on the VehicleMapController

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#932]
See screenshot. (the strange gray line to the right of the route line)

![attachment 1](https://cloud.githubusercontent.com/assets/2254/21752439/ab634368-d58c-11e6-8f1d-5a3b4ed3e7c4.jpg)

**Comment by ualch9** [comment]
It looks like a temporary fix is to redraw the view (press the expand button on the bottom right of the map view)
<img src="https://cloud.githubusercontent.com/assets/22162410/21753315/a2eaf07e-d59f-11e6-8120-07980c7541fe.jpg" height=400>
