### ISSUE TITLE
Sometimes cannot edit the name of a bookmark when creating it

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#933]
A user reports:

> when bookmarking a stop, if I edit the stop name and then set the group, I lose my edits to the name.

**Comment by islandowl** [comment]
Yes Aaron, this is the same problem I was running into in my OBA bug report on 1/17. Didn't see a way to link back to the email exchange /bug report.

**Comment by aaronbrethorst** [comment]
thanks, @islandowl. This'll be released in the next version of the app. If you'd like earlier access I'd be happy to add you to the beta program. Email me at aaron at brethorsting dot com if you'd like to be added.
