### ISSUE TITLE
Improve title casing for strings with acronyms

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#934]
Related to #635. I'm not sure how best to tackle this, but the issue reported by Devin Braun in San Diego does need to be fixed.

Here are some unit tests that this hypothetical title casing utility would have to pass:

    NSString *convertedText = [HypotheticalStringMunger properlyTitleCaseString:@"DOWNTOWN EXPRESS"];
    XCTAssertEqualObjects(convertedText, @"Downtown Express");

    NSString *convertedText = [HypotheticalStringMunger properlyTitleCaseString:@"Downtown Express"];
    XCTAssertEqualObjects(convertedText, @"Downtown Express");

    NSString *convertedText = [HypotheticalStringMunger properlyTitleCaseString:@"UTC/VA MED CTR EXPRESS"];
    XCTAssertEqualObjects(convertedText, @"UTC/VA Med Ctr Express");

    NSString *convertedText = [HypotheticalStringMunger properlyTitleCaseString:@"12TH & IMPERIAL"];
    XCTAssertEqualObjects(convertedText, @"12th & Imperial");

    NSString *convertedText = [HypotheticalStringMunger properlyTitleCaseString:@"UCSD / VA MEDICAL CTR"];
    XCTAssertEqualObjects(convertedText, @"UCSD / VA Medical Ctr");

    NSString *convertedText = [HypotheticalStringMunger properlyTitleCaseString:@"SDSU"];
    XCTAssertEqualObjects(convertedText, @"SDSU");

    NSString *convertedText = [HypotheticalStringMunger properlyTitleCaseString:@"GROSSMONT TROLLEY"];
    XCTAssertEqualObjects(convertedText, @"Grossmont Trolley");

![image-1](https://cloud.githubusercontent.com/assets/2254/21903959/ad16088a-d8b6-11e6-8eae-84dc7bac0d8b.png)
![image-2](https://cloud.githubusercontent.com/assets/2254/21903960/ad2eebc0-d8b6-11e6-886f-9892b8032769.png)
![image-3](https://cloud.githubusercontent.com/assets/2254/21903962/ad3e0c5e-d8b6-11e6-9612-4c6482551dbd.png)
![image](https://cloud.githubusercontent.com/assets/2254/21903961/ad3500e6-d8b6-11e6-9398-5ba2dcd5a2bf.png)

**Comment by barbeau** [comment]
"UCSD / VA MEDICAL CTR" is the hard one.  Same issue on Android.  I don't know how to fix that - let me know if you come up with any ideas.

**Comment by bbodenmiller** [comment]
Shouldn't this be fixed in the API rather than each app? Is there not some existing library we can use to do this?

**Comment by barbeau** [comment]
Technically, it should be fixed in the data itself from each agency.  IMHO, text shouldn't be in all caps.

**Comment by aaronbrethorst** [comment]
I AGREE COMPLETELY. AND I THINK THAT THAT IS UNLIKELY TO HAPPEN ANY TIME SOON. MUCH BETTER TO MAKE A GOOD EFFORT AT FIXING IT IN-APP WHILE SIMULTANEOUSLY APPROACHING AGENCIES ABOUT IMPROVING VENDED DATA.

;)

**Comment by artlung** [comment]
OneBusAway is actively promoted by San Diego MTS - they do so on social media - and there are also recorded announcements on "Rapid" bus lines. Is there a formal partnership? What's the best way to lobby them to improve the (API?) data?

**Comment by barbeau** [comment]
Aaron - where did this issue report come from? SDMTS or user?

**Comment by aaronbrethorst** [comment]
@barbeau from SDMTS

**Comment by barbeau** [comment]
Did they say why headsign was in all caps?  Is it something they are
able/willing to change?

**Comment by aaronbrethorst** [comment]
Good Q. Didn't ask, but I'll check.

Sean Barbeau wrote:

**Comment by devinbraun** [comment]
Our (San Diego's) headsigns are properly capitalized.  The API returns the correct headsign.  The ***apps*** re-capitalize the headsigns for us.  I know this recapitalization started because the original agencies used ALL CAPS for their headsigns, but we do not.  

Here's an example API call which includes the "UTC/VA Med Ctr" headsign.  
[http://realtime.sdmts.com/api/api/where/arrivals-and-departures-for-stop/MTS_10840.xml?key=org.onebusaway.iphone](http://realtime.sdmts.com/api/api/where/arrivals-and-departures-for-stop/MTS_10840.xml?key=org.onebusaway.iphone)

Here's another one with "UCSD / VA Medical Center" in the headsign:
[http://realtime.sdmts.com/api/api/where/arrivals-and-departures-for-stop/MTS_94038.xml?key=org.onebusaway.iphone](http://realtime.sdmts.com/api/api/where/arrivals-and-departures-for-stop/MTS_94038.xml?key=org.onebusaway.iphone)

**Comment by devinbraun** [comment]
Here's a previous discussion regarding capitalization:

[https://groups.google.com/d/topic/onebusaway-developers/ji4tXePwB10/discussion](url)

**Comment by aaronbrethorst** [comment]
Hmm, the app's behavior is doubly wrong, then. The re-capitalization isn't supposed to happen unless those strings are in all caps. Thanks for the further context, @devinbraun. I'll make sure this gets fixed for the next release.

**Comment by barbeau** [comment]
@devinbraun thanks for reporting this!  Does everything look OK on Android now?  I know I fixed a headsign issue a while back but want to make sure everything is correct now.

**Comment by devinbraun** [comment]
I remembered that we have one head sign that just says SDSU (one word, all caps).

**Comment by devinbraun** [comment]
@barbeau I still see a few issues in Android.  I'll open another issue.

**Comment by aaronbrethorst** [comment]
Mooted by #1317. We're just going to go with whatever the API gives us.
