### ISSUE TITLE
Handoff support

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-iphone#949]
Now that we have support for iPad, it would be helpful if we could handoff application state to another device. It looks like we already have partial support for this in `OBAApplicationDelegate` `- (BOOL)application:(UIApplication *)application continueUserActivity...`. OBA now needs to broadcast a `UserActivity`. By using `webpageURL`, macOS can also continue application state in Safari.

**Comment by ualch9** [comment]
@aaronbrethorst please assign this to me

**Comment by aaronbrethorst** [comment]
👍

**Comment by barbeau** [comment]
Interesting - I don't believe that a similar feature is natively supported
on Android,  closest would be retaining game state.

Would it be possible to implement this via deep links/URL schemes instead?
Not sure how much state you're talking about retaining for the handoff, but
if done in a way that doesn't depend on iOS specifically it would enable
better integration across platforms. That being said, I would imagine the
native support is simpler to implement.

**Comment by aaronbrethorst** [comment]
Handoff is built deeply into iOS and macOS. I don't think it would be possible to replicate its feature set without doing a lot of extra engineering work. https://support.apple.com/en-us/HT204681

**Comment by barbeau** [comment]
Yeah, that's what I figured.

**Comment by ualch9** [comment]
# Proposed changes
(at the request of @aaronbrethorst)
In terms of current code, all features will remain the same. `OBAHandoff` will handle most of the new features, with some added behaviors in views wanting to support Handoff. 

## `OBAStopViewController`
`OBAStopViewController` will pass on the current `OBAArrivalAndDepartureForStopV2` to `OBAHandoff` for processing. Only the stopID and current region will be sent because `OBAStopViewController` can be initialized with just the stopID. The region is just for matching. Here's the workflow:

![desktop hd](https://cloud.githubusercontent.com/assets/22162410/22170226/3983da02-df30-11e6-844a-f18842af3c92.png)

## `OBAApplicationDelegate`
Most changes in `OBAApplicationDelegate` will take place in the `- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity` method which requires it to check if `userActivity.userInfo` exists. If it does exist, create and `push` an `OBAStopViewController` with the stopID provided in `userInfo`. 
**The current workflow:**
![receiving current](https://cloud.githubusercontent.com/assets/22162410/22170295/e7eb81d0-df30-11e6-922e-5ea1581ca124.png)

**Updated workflow:**
![receiving updated](https://cloud.githubusercontent.com/assets/22162410/22170299/f2625972-df30-11e6-9d39-ed672a56703a.png)

If there are any other views that should support handoff, please let me know. For views that can provide a deep link URL and be handled by `OBADeepLinkRouter` will not require big changes. Otherwise, a solution such as the one outlined above may be needed.

**Comment by aaronbrethorst** [comment]
This looks fantastic. 👍 I look forward to seeing the PR!

**Comment by aaronbrethorst** [comment]
Fixed in #952
