### ISSUE TITLE
Error message that accompanies a server failure is misleading

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#954]
It looks like the app displays an "error connecting" dialog when the OBA server it's trying to connect to is down. This is misleading and should be fixed.

- [ ] Assessment of all circumstances in which this dialog can appear.
- [ ] Replacement of messages with more appropriate ones (ideally with something like `AlertPresenter` instead of a modal alert)

![attachment 1](https://cloud.githubusercontent.com/assets/2254/22198051/a5be4f9c-e109-11e6-9338-6a01ffe57b71.jpg)

**Comment by devinbraun** [comment]
BTW, we received 15 emails during the short time the app was down on Sunday.

**Comment by aaronbrethorst** [comment]
Fixed with #1044
