### ISSUE TITLE
Add a button to the bookmarks controller to show ALL bookmarks

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#955]
The user's bookmarks are scoped to the bookmarks' region. If you have 5 bookmarks in Puget Sound and travel to Boston your Puget Sound bookmarks are hidden. 

We should tell users why their bookmarks disappeared and give them the option of viewing all of their bookmarks by putting footer text and a button on the bookmarks tab.

- [x] Needs design
- [ ] Needs implementation

------

# Design

![show](https://cloud.githubusercontent.com/assets/2254/22658503/308088ac-ec4f-11e6-90b8-51c3a908928a.png)

![hide](https://cloud.githubusercontent.com/assets/2254/22658502/3068f3fe-ec4f-11e6-8759-a7c7cc644b75.png)

**Comment by dotTechnopath** [comment]
I think we should tackle both #942 and this at once so that we don't have conflicts with the design /  implementation

**Comment by dotTechnopath** [comment]
![redesign 1](https://cloud.githubusercontent.com/assets/9895341/22620255/8e67eae4-eabc-11e6-8f37-209a32eb4c99.png)

This interface should solve both #942 and #955 both at once (UX wise). This builds on the "sort button" that i have proposed on #942. The "sort" button replaces the current "groups" button on the bookmarks tab, and the "groups" button now only appears when you hit the edit button.

**Comment by aaronbrethorst** [comment]
@dotTechnopath - The key problem that needs solving is that, from a user's perspective, their bookmarks sometimes just 'disappear.' This happens because of bugs in the multi-region code that I'm planning on fixing soon. However, the toggle for displaying all bookmarks vs. this region's needs to be much more clearly presented to the user. Thank you for spending time thinking through this.

![show](https://cloud.githubusercontent.com/assets/2254/22658503/308088ac-ec4f-11e6-90b8-51c3a908928a.png)

![hide](https://cloud.githubusercontent.com/assets/2254/22658502/3068f3fe-ec4f-11e6-8759-a7c7cc644b75.png)

**Comment by dotTechnopath** [comment]
I think something to consider with your idea I think is that if the user has many bookmarks, then they would have to scroll all the way down every time they wanted to make the switch from all to current regions, which might be cumbersome.

**Comment by aaronbrethorst** [comment]
Punting to the next release. The fixes in 17.1.2 should address the greatest needs for this.

**Comment by cathy810218** [comment]
@aaronbrethorst So I read through all the comments ^ 
If I understand it correctly, the images you posted are the new design. Is that correct?

**Comment by aaronbrethorst** [comment]
mooted by regions bug fixes.
