### ISSUE TITLE
Display service alerts

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-iphone#968]
Displaying service alerts or reroutes from agencies would be helpful for the user. The OBA-API seems to already support this with [`<situation/>`](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/elements/situation.html) however I'm unsure if `OBAKit` have support. Just dumping some stuff here, will expand on this after I resolve other issues

**Comment by aaronbrethorst** [comment]
https://github.com/OneBusAway/onebusaway-iphone/blob/develop/OBAKit/Services/OBAModelFactory.m#L373

But that doesn't do any good unless your transit provider offers up service alerts. 

Hence: https://github.com/OneBusAway/onebusaway-iphone/issues/881
