### ISSUE TITLE
Walking row no longer appearing in latest build

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#971]
Per @sethfri 

![click png](https://cloud.githubusercontent.com/assets/2254/22672789/ef661ef4-ec8a-11e6-8043-c3610a34278d.jpeg)

**Comment by devinbraun** [comment]
My walking row is showing up fine in 20170206.15.  Maybe because the battery is so low that GPS is turned off?

**Comment by devinbraun** [comment]
![img_6580](https://cloud.githubusercontent.com/assets/5028299/22673197/8f74b8c2-ec8d-11e6-8b84-642d9057cf2e.PNG)

**Comment by sethfri** [comment]
I don't think iOS ever turns your GPS *off* haha. I frequently let my
battery get dangerously low and other location services work fine. My blue
dot on the map with bearing, for instance, work fine on the latest build.

**Comment by aaronbrethorst** [comment]
Whew, showing up for me too. Being a bit slow for whatever reason, though. I'll keep this open as I may very well have messed something up.

**Comment by sethfri** [comment]
Ok so I actually am seeing these appear, but they're very slow (takes 15-20
seconds to appear on current Wi-Fi speed of 150 Mbps). Wasn't leaving the
stop open long enough before.

Definitely a latency regression, though, so we should leave this open (and
also consider writing some performance tests to proactively catch this in
the future)

**Comment by sethfri** [comment]
I've tried this on 5-6 stops now btw. All are similarly slow

**Comment by aaronbrethorst** [comment]
I am actively working on this.
