### ISSUE TITLE
Arrival and Departure: Pan the table to move the map split up and down

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#976]
### Expected behavior

I should be able to hide or show more of the arrival and departure map by panning on the top part of th table.

### Actual behavior

This doesn't exist. Instead, there's only the expand/contract button.

### Steps to reproduce the behavior

Open Arrival and Departure controller, try panning.

### Screenshot of the issue (if applicable)

![mock](https://cloud.githubusercontent.com/assets/2254/22713719/6da8d65e-ed3e-11e6-8dd7-b47f09635ec0.png)

**Comment by ualch9** [comment]
Began working on this. [link](https://github.com/ualch9/onebusaway-iphone/commits/develop)
