### ISSUE TITLE
Remove "STOP" label to stop annotations

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-iphone#982]
There's really not much use to displaying "STOP" to each annotation because there isn't anything else other than stops. How about like this?
![img_0005](https://cloud.githubusercontent.com/assets/22162410/22718095/457f46b2-ed53-11e6-846b-dcf6c4203741.jpg)

**Comment by devinbraun** [comment]
It kind of looks like buses (vehicles) on the streets and the current directions they are traveling if you take the STOP text out of the icon.

**Comment by barbeau** [comment]
That was a complaint we had about OBA Android v1, and one of the reasons I
removed the bus image from the stop icon in v2.

On Feb 7, 2017 7:38 PM, "devinbraun" <notifications@github.com> wrote:

It kind of looks like buses (vehicles) on the streets and the current
directions they are traveling if you take the STOP text out of the icon.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OneBusAway/onebusaway-iphone/issues/982#issuecomment-278192085>,
or mute the thread

**Comment by ualch9** [comment]
I think the glyphs should stay there (or at least not appear for busses) to differentiate other stops (e.g. light rail, train...)

--
Alan Chu
ualch9@gmail.com

**Comment by barbeau** [comment]
Yeah, in OBA Android v1 bus images were used for all stops, so we didn't lose any information by getting rid of the image. That's different with iOS. It's been on my TODO list to figure out how to distinguish modes at stops given the current icon  but I haven't gotten that far :).

**Comment by ualch9** [comment]
how about something like this? with the glyph changing according. 
@dotTechnopath

--
Alan Chu
ualch9@gmail.com <mailto:ualch9@gmail.com>

**Comment by ualch9** [comment]
oops, forgot to attach image
![image1](https://cloud.githubusercontent.com/assets/22162410/22722493/400e53e4-ed6c-11e6-8b32-fb11bfa0c12a.png)

**Comment by dotTechnopath** [comment]
another idea is to copy how Apple maps shows their bus stops
![image](https://cloud.githubusercontent.com/assets/9895341/22722524/7b4cc9cc-ed6c-11e6-818f-2af31f7d54c9.png)

**Comment by ualch9** [comment]
@dotTechnopath I think these will confuse the user @barbeau was talking about.  maybe that's just me...

**Comment by barbeau** [comment]
@dotTechnopath Just remember that Apple Maps isn't showing any realtime yet. When they do, they might rethink this imagery.

**Comment by ualch9** [comment]
hmmmm.....
<img src="https://cloud.githubusercontent.com/assets/22162410/22723698/6039f804-ed75-11e6-835f-13b1c948aa78.png" height=480>

**Comment by aaronbrethorst** [comment]
I appreciate the stop sign symbolism but I think it'll be lost on users.

**Comment by ualch9** [comment]
@aaronbrethorst agreed. going to close this issue for now, current icon seems okay.
