### ISSUE TITLE
Arrival and Departure: Disable pulse animation/change color on vehicles where we lack real-time data

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#986]
### Expected behavior

- [ ] A pulsing indicator on a bus should only appear when we have real time data.
- [ ] Buses are ringed with black, perhaps, instead of blue when they lack real time data.
- [ ] A warning is display on/near the map indicating that the bus location is only approximate.

### Actual behavior

It always shows up regardless.

### Steps to reproduce the behavior

Choose a bus with 'scheduled arrival'. It pulses. It shouldn't.

**Comment by victorray84** [comment]
@aaronbrethorst I want to work on this issue. Do you want the pulse animation to be disabled only for the case 'scheduled arrival' or any other case?

**Comment by aaronbrethorst** [comment]
OK, it's yours. Only disabled in the case of 'scheduled arrival'
