### ISSUE TITLE
The actions don't work when arrivals list is sorted by route

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-iphone#994]
If the arrivals list is sorted by route, when pressing the green circle on the line to open up actions such as bookmark and reminder, nothing happens.  

Version 17.2.0 (20170206.21)

**Comment by aaronbrethorst** [comment]
Thanks, Devin. I'll make sure this gets fixed.

**Comment by aaronbrethorst** [comment]
@victorray84 sounds good

**Comment by aaronbrethorst** [comment]
Fixed in #1010
