### ISSUE TITLE
Alarms cannot be set

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-iphone#999]
Version: 20170314.23 (TestFlight)

Tried using both WiFi and cellular connections, failed on both occasions, however, **may just be an isolated problem**. Logs show nothing out of the ordinary, just basic HTTP stuff. See attached screenshots. 

![img_0897](https://cloud.githubusercontent.com/assets/22162410/23954459/9251405e-0954-11e7-8d27-9f77da56ef90.PNG)
![img_0899](https://cloud.githubusercontent.com/assets/22162410/23954567/e5706b66-0954-11e7-949a-853e455854a6.PNG)

**Comment by aaronbrethorst** [comment]
Fixed with https://github.com/OneBusAway/onebusaway-deep-links/pull/22

**Comment by aaronbrethorst** [comment]
Also, I've opened up #1000 to improve the messaging in this alert. @ualch9, if you have any free time, this should be an easy enhancement to knock out. Thanks for your bug report!

**Comment by ualch9** [comment]
@aaronbrethorst sure thing, i'll take a look when i get the chance.
